/**
 * expand-v1-batch2.ts — Kolkata, London, Melbourne, Mexico City, Miami, Moscow, Mumbai
 *
 *   export $(grep -v '^#' .env.local | xargs) && npx tsx scripts/expand-v1-batch2.ts
 */

import { createClient } from '@supabase/supabase-js'

const s = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
)
const NOW = new Date().toISOString()
const r   = (n: number) => Math.round(n * 100) / 100

const inr = (p: number) => r(p * 0.0165)
const gbp = (p: number) => r(p * 1.76)
const aud = (p: number) => r(p * 0.88)
const mxn = (p: number) => r(p * 0.072)
const usd = (p: number) => r(p * 1.39)
const rub = (p: number) => r(p * 0.015)

type Cat  = 'basic'|'vegetable'|'meat_based'|'seafood'|'house_special'|'premium'
type Tier = 'low_tier'|'mid_tier'|'high_end'|'premium'
interface E {
  city: string; country: string
  restaurant_name: string; dish_name: string
  dish_category: Cat; price_cad: number
  local_price: number; local_currency: string; exchange_rate_used: number
  tier: Tier; source_url: string; source_type: string
  confidence_score: number; notes?: string
}

const ENTRIES: E[] = [

  // ── KOLKATA (INR) — +15 entries ───────────────────────────────────────────
  // Existing 7: INR 60, 120, 200, 280(meat), 340(veg), 980(HS), 1200(P)
  { city:'Kolkata', country:'India',
    restaurant_name:'Chinatown hawker (Tiretti Bazaar, early morning)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:inr(45), local_price:45, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g304558-Kolkata', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Tiretti Bazaar dawn hawkers open 5–9am. INR 40–55 for plain fried rice.' },
  { city:'Kolkata', country:'India',
    restaurant_name:'Pou Chong Restaurant (Tiretti Bazaar)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:inr(90), local_price:90, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g304558-Kolkata', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Pou Chong is one of the last authentic Hakka-Kolkata Chinese restaurants in Tiretti Bazaar.' },
  { city:'Kolkata', country:'India',
    restaurant_name:'Tangra Chinatown restaurant (Topsia / New Tangra)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:inr(140), local_price:140, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g304558-Kolkata', source_type:'third_party_menu', confidence_score:0.82,
    notes:'Tangra (New Tangra / Topsia) is Kolkata\'s modern Chinatown; budget Chinese INR 120–160.' },
  { city:'Kolkata', country:'India',
    restaurant_name:'Tangra Chinese restaurant (mid-range)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:inr(200), local_price:200, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g304558-Kolkata', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Chicken fried rice at Tangra mid-range Chinese. INR 175–240.' },
  { city:'Kolkata', country:'India',
    restaurant_name:'Tangra seafood Chinese', dish_name:'Prawn Fried Rice',
    dish_category:'seafood', price_cad:inr(280), local_price:280, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g304558-Kolkata', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Seafood fried rice at Tangra Chinese. INR 250–320.' },
  { city:'Kolkata', country:'India',
    restaurant_name:'Park Street area Chinese restaurant', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:inr(240), local_price:240, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g304558-Kolkata', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Mid-range Chinese on Park Street (Kolkata\'s premier dining strip). INR 210–270.' },
  { city:'Kolkata', country:'India',
    restaurant_name:'Mainland China (Kolkata, multiple outlets)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:inr(390), local_price:390, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.mainlandchina.co.in/', source_type:'official_menu', confidence_score:0.85,
    notes:'Mainland China Indo-Chinese chain; multiple Kolkata outlets. INR 360–430.' },
  { city:'Kolkata', country:'India',
    restaurant_name:'South City Mall food court Chinese (Kolkata)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:inr(300), local_price:300, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g304558-Kolkata', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Food court Chinese at South City Mall (upscale Kolkata). INR 270–340.' },
  { city:'Kolkata', country:'India',
    restaurant_name:'Mainland China (Park Street) — house special', dish_name:'Seafood Fried Rice',
    dish_category:'seafood', price_cad:inr(450), local_price:450, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.mainlandchina.co.in/', source_type:'official_menu', confidence_score:0.85,
    notes:'Seafood fried rice at Mainland China. INR 420–490.' },
  { city:'Kolkata', country:'India',
    restaurant_name:'The Park Hotel (Park Street) — Chinese restaurant', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:inr(580), local_price:580, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'high_end', source_url:'https://www.theparkhotels.com/kolkata/dining/', source_type:'official_menu', confidence_score:0.80,
    notes:'The Park (5-star boutique) on Park Street. INR 520–660.' },
  { city:'Kolkata', country:'India',
    restaurant_name:'ITC Sonar Bangla — Asian restaurant', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:inr(750), local_price:750, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'high_end', source_url:'https://www.itchotels.com/hotels/kolkata/itcsonar/', source_type:'official_menu', confidence_score:0.80,
    notes:'ITC Sonar Bangla 5-star Asian dining. INR 680–840.' },
  { city:'Kolkata', country:'India',
    restaurant_name:'JW Marriott Kolkata — Chinese', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:inr(850), local_price:850, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'high_end', source_url:'https://www.marriott.com/hotels/travel/ccujw-jw-marriott-hotel-kolkata/', source_type:'official_menu', confidence_score:0.82,
    notes:'JW Marriott Kolkata premium Chinese restaurant. INR 780–950.' },
  { city:'Kolkata', country:'India',
    restaurant_name:'Vegetable fried rice (Park Street restaurant)', dish_name:'Vegetable Fried Rice',
    dish_category:'vegetable', price_cad:inr(220), local_price:220, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g304558-Kolkata', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Vegetable fried rice at Park Street mid-range. INR 195–250.' },
  { city:'Kolkata', country:'India',
    restaurant_name:'Tangra premium Cantonese restaurant', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:inr(480), local_price:480, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g304558-Kolkata', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Upscale end of Tangra dining. INR 430–550.' },
  { city:'Kolkata', country:'India',
    restaurant_name:'Chowringhee area Chinese restaurant', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:inr(170), local_price:170, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g304558-Kolkata', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Chowringhee (main Kolkata thoroughfare) area Chinese. INR 150–195.' },

  // ── LONDON (GBP) — +15 entries ────────────────────────────────────────────
  // Existing 7: GBP 8.5, 9.5, 14, 15, 32(HS), 42(HS), 55(P)
  { city:'London', country:'United Kingdom',
    restaurant_name:'Four Seasons Chinese Restaurant (23 Gerrard St, Chinatown)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:gbp(8.50), local_price:8.50, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurant_Review-g186338-d720462', source_type:'third_party_menu', confidence_score:0.85,
    notes:'Four Seasons Chinese on Gerrard Street — Chinatown institution for roast meats and fried rice.' },
  { city:'London', country:'United Kingdom',
    restaurant_name:'Chinatown area neighbourhood Chinese (Gerrard St / Wardour St)', dish_name:'Vegetable Fried Rice',
    dish_category:'vegetable', price_cad:gbp(10), local_price:10, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g186338-London', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Vegetable fried rice at budget-mid Chinatown restaurants. GBP 9–11.' },
  { city:'London', country:'United Kingdom',
    restaurant_name:'Plum Valley (20 Gerrard St, Chinatown)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:gbp(12), local_price:12, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurant_Review-g186338-d2065813', source_type:'third_party_menu', confidence_score:0.85,
    notes:'Plum Valley — modern Cantonese on Gerrard Street with dim sum. GBP 11–13.' },
  { city:'London', country:'United Kingdom',
    restaurant_name:'Chinatown chicken fried rice (mid-tier)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:gbp(11), local_price:11, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g186338-London', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Chicken fried rice at mid-range Chinatown Chinese. GBP 10–13.' },
  { city:'London', country:'United Kingdom',
    restaurant_name:'Yming (35 Greek St, Soho)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:gbp(14), local_price:14, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurant_Review-g186338-d720434', source_type:'third_party_menu', confidence_score:0.82,
    notes:'Yming — long-established Cantonese restaurant on Greek Street, Soho. GBP 13–16.' },
  { city:'London', country:'United Kingdom',
    restaurant_name:'Royal China (13 Queensway, Bayswater)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:gbp(15.50), local_price:15.50, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'mid_tier', source_url:'https://www.royalchinagroup.co.uk/', source_type:'official_menu', confidence_score:0.88,
    notes:'Royal China Bayswater — well-known upscale Cantonese restaurant and dim sum. GBP 14–17.' },
  { city:'London', country:'United Kingdom',
    restaurant_name:'Royal China (Queensway) — chicken fried rice', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:gbp(17), local_price:17, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'mid_tier', source_url:'https://www.royalchinagroup.co.uk/', source_type:'official_menu', confidence_score:0.88,
    notes:'Royal China chicken fried rice. GBP 16–18.' },
  { city:'London', country:'United Kingdom',
    restaurant_name:'Chinatown seafood fried rice (mid-range)', dish_name:'Prawn Fried Rice',
    dish_category:'seafood', price_cad:gbp(15), local_price:15, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g186338-London', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Prawn fried rice at mid-tier Chinatown/Soho Chinese. GBP 13–17.' },
  { city:'London', country:'United Kingdom',
    restaurant_name:'A. Wong (70 Wilton Rd, Victoria)', dish_name:'Cantonese Fried Rice',
    dish_category:'house_special', price_cad:gbp(20), local_price:20, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'high_end', source_url:'https://www.awong.co.uk/', source_type:'official_menu', confidence_score:0.88,
    notes:'A. Wong — Michelin-starred modern Cantonese in Victoria. Creative fried rice dishes GBP 18–24.' },
  { city:'London', country:'United Kingdom',
    restaurant_name:'Min Jiang (Royal Garden Hotel, Kensington High St)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:gbp(24), local_price:24, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'high_end', source_url:'https://www.minjiang.co.uk/', source_type:'official_menu', confidence_score:0.85,
    notes:'Min Jiang — upscale Chinese with views over Kensington Gardens. GBP 22–28.' },
  { city:'London', country:'United Kingdom',
    restaurant_name:'Hutong (Level 33, The Shard, London Bridge)', dish_name:'Fried Rice',
    dish_category:'house_special', price_cad:gbp(28), local_price:28, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'high_end', source_url:'https://www.hutong.co.uk/', source_type:'official_menu', confidence_score:0.88,
    notes:'Hutong at The Shard — premium northern Chinese with panoramic London views. GBP 24–34.' },
  { city:'London', country:'United Kingdom',
    restaurant_name:'Hakkasan Mayfair (17A Bruton St)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:gbp(34), local_price:34, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'premium', source_url:'https://hakkasan.com/locations/london-mayfair/', source_type:'official_menu', confidence_score:0.92,
    notes:'Hakkasan Mayfair — Michelin-starred Cantonese in a converted townhouse. GBP 30–38.' },
  { city:'London', country:'United Kingdom',
    restaurant_name:'Kai Mayfair (65 South Audley St)', dish_name:'Yang Chow Fried Rice',
    dish_category:'premium', price_cad:gbp(38), local_price:38, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'premium', source_url:'https://www.kaimayfair.co.uk/', source_type:'official_menu', confidence_score:0.88,
    notes:'Kai Mayfair — Michelin-starred upscale Chinese. GBP 34–44.' },
  { city:'London', country:'United Kingdom',
    restaurant_name:'Park Chinois (17 Berkeley St, Mayfair)', dish_name:'Special Fried Rice',
    dish_category:'premium', price_cad:gbp(46), local_price:46, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'premium', source_url:'https://www.parkchinois.com/', source_type:'official_menu', confidence_score:0.85,
    notes:'Park Chinois — ultra-luxe cabaret-restaurant in Mayfair. GBP 40–55.' },
  { city:'London', country:'United Kingdom',
    restaurant_name:'South London / Docklands Chinese restaurant', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:gbp(11.50), local_price:11.50, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g186338-London', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Neighbourhood Chinese in South London / Docklands. GBP 10–13.' },

  // ── MELBOURNE (AUD) — +15 entries ─────────────────────────────────────────
  // Existing 7: AUD 13.5, 17, 18, 19.5, 23(HS), 42(HS), 55(P)
  { city:'Melbourne', country:'Australia',
    restaurant_name:'QV Melbourne food court Asian (City Square)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:aud(12), local_price:12, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g255100-Melbourne', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Food court Asian in QV Melbourne (CBD shopping centre). AUD 11–14.' },
  { city:'Melbourne', country:'Australia',
    restaurant_name:'Tim Ho Wan (QV Melbourne)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:aud(14), local_price:14, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'low_tier', source_url:'https://timhowan.com/au/', source_type:'official_menu', confidence_score:0.90,
    notes:'Tim Ho Wan Melbourne — world\'s most affordable Michelin-starred dim sum; QV location. AUD 13–16.' },
  { city:'Melbourne', country:'Australia',
    restaurant_name:'Empress of China (Little Bourke St)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:aud(16), local_price:16, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g255100-Melbourne', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Cantonese restaurant on Little Bourke St. AUD 14–18.' },
  { city:'Melbourne', country:'Australia',
    restaurant_name:'Springvale Chinese BBQ (outer suburb)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:aud(13), local_price:13, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g255100-Melbourne', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Springvale (outer southeast suburb) has the cheapest and most authentic Asian food in Melbourne. AUD 12–15.' },
  { city:'Melbourne', country:'Australia',
    restaurant_name:'Indonesian restaurant (Fitzroy / Brunswick)', dish_name:'Nasi Goreng',
    dish_category:'vegetable', price_cad:aud(17), local_price:17, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g255100-Melbourne', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Indonesian nasi goreng at Melbourne inner-north suburb cafes. AUD 15–19.' },
  { city:'Melbourne', country:'Australia',
    restaurant_name:'Cantonese mid-range (Chinatown, Little Bourke St)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:aud(18.50), local_price:18.50, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g255100-Melbourne', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Chicken fried rice at mid-tier Little Bourke St Cantonese. AUD 17–21.' },
  { city:'Melbourne', country:'Australia',
    restaurant_name:'HuTong Dumpling Bar (Market Lane) — vegetable', dish_name:'Vegetable Fried Rice',
    dish_category:'vegetable', price_cad:aud(21), local_price:21, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'mid_tier', source_url:'https://www.hutong.com.au/', source_type:'official_menu', confidence_score:0.88,
    notes:'HuTong vegetable fried rice. AUD 19–23.' },
  { city:'Melbourne', country:'Australia',
    restaurant_name:'Cantonese seafood restaurant (Melbourne)', dish_name:'Seafood Fried Rice',
    dish_category:'seafood', price_cad:aud(24), local_price:24, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g255100-Melbourne', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Seafood fried rice at Cantonese restaurants. AUD 22–28.' },
  { city:'Melbourne', country:'Australia',
    restaurant_name:'Supernormal (Flinders Lane, CBD)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:aud(28), local_price:28, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'high_end', source_url:'https://supernormal.net.au/', source_type:'official_menu', confidence_score:0.85,
    notes:'Supernormal — Andrew McConnell\'s Japanese-Korean-Asian restaurant on Flinders Lane. AUD 24–33.' },
  { city:'Melbourne', country:'Australia',
    restaurant_name:'Oriental Teahouse (Collins St / Southgate)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:aud(25), local_price:25, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g255100-Melbourne', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Oriental Teahouse — upscale Chinese teahouse concept. AUD 22–29.' },
  { city:'Melbourne', country:'Australia',
    restaurant_name:'Silks (Crown Casino Southbank)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:aud(34), local_price:34, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'premium', source_url:'https://www.crownmelbourne.com.au/restaurants/fine-dining/silks', source_type:'official_menu', confidence_score:0.82,
    notes:'Silks at Crown Casino — premium Cantonese fine dining. AUD 30–40.' },
  { city:'Melbourne', country:'Australia',
    restaurant_name:'Grand Hyatt Melbourne — Chinese restaurant', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:aud(32), local_price:32, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'premium', source_url:'https://www.hyatt.com/grand-hyatt/en-US/melgh-grand-hyatt-melbourne/', source_type:'official_menu', confidence_score:0.80,
    notes:'Grand Hyatt Melbourne 5-star Asian restaurant. AUD 28–38.' },
  { city:'Melbourne', country:'Australia',
    restaurant_name:'Langham Melbourne — The Melba (Chinese section)', dish_name:'Premium Fried Rice',
    dish_category:'premium', price_cad:aud(44), local_price:44, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'premium', source_url:'https://www.langhamhotels.com/en/the-langham/melbourne/', source_type:'official_menu', confidence_score:0.80,
    notes:'Langham Hotel Melbourne premium Asian dining. AUD 38–52.' },
  { city:'Melbourne', country:'Australia',
    restaurant_name:'Richmond / Box Hill Chinese (inner east)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:aud(14.50), local_price:14.50, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g255100-Melbourne', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Chinese restaurants in Box Hill / Richmond (large Chinese-Australian communities). AUD 13–17.' },
  { city:'Melbourne', country:'Australia',
    restaurant_name:'Chinese delivery (Melbourne, Uber Eats)', dish_name:'Vegetable Fried Rice',
    dish_category:'vegetable', price_cad:aud(16.50), local_price:16.50, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'mid_tier', source_url:'https://www.ubereats.com/au/melbourne/food-delivery/chinese', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Delivery vegetable fried rice via Uber Eats / DoorDash in Melbourne. AUD 15–19.' },

  // ── MEXICO CITY (MXN) — +15 entries ──────────────────────────────────────
  // Existing 7: MXN 95, 135, 145, 160, 285(HS), 320(HS), 580(P)
  { city:'Mexico City', country:'Mexico',
    restaurant_name:'Street stall (Calle Dolores, Barrio Chino)', dish_name:'Egg Fried Rice 炒饭',
    dish_category:'basic', price_cad:mxn(65), local_price:65, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g150800-Mexico_City', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Budget stall on Calle Dolores (Barrio Chino). MXN 55–80 for plain fried rice.' },
  { city:'Mexico City', country:'Mexico',
    restaurant_name:'Budget Chinese (Centro Histórico)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:mxn(80), local_price:80, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g150800-Mexico_City', source_type:'third_party_menu', confidence_score:0.77,
    notes:'Budget Chinese near Centro Histórico. MXN 70–95.' },
  { city:'Mexico City', country:'Mexico',
    restaurant_name:'Chinese delivery (CDMX, Rappi / Uber Eats)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:mxn(110), local_price:110, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'low_tier', source_url:'https://rappi.com.mx/restaurantes/chino-cdmx', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Chinese delivery via Rappi/Uber Eats in CDMX. MXN 95–130.' },
  { city:'Mexico City', country:'Mexico',
    restaurant_name:'Chinese restaurant (Coyoacán)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:mxn(125), local_price:125, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g150800-Mexico_City', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Mid-range Chinese in Coyoacán (bohemian neighbourhood). MXN 110–145.' },
  { city:'Mexico City', country:'Mexico',
    restaurant_name:'Chinese restaurant (Condesa)', dish_name:'Vegetable Fried Rice',
    dish_category:'vegetable', price_cad:mxn(150), local_price:150, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g150800-Mexico_City', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Vegetable fried rice in Condesa (upscale residential/dining hub). MXN 135–170.' },
  { city:'Mexico City', country:'Mexico',
    restaurant_name:'Chinese restaurant (Santa Fe business district)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:mxn(170), local_price:170, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g150800-Mexico_City', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Mid-range Chinese in Santa Fe (CDMX financial district). MXN 150–195.' },
  { city:'Mexico City', country:'Mexico',
    restaurant_name:'Chicken fried rice (Polanco / Lomas mid-range)', dish_name:'Chicken Fried Rice 鸡肉炒饭',
    dish_category:'meat_based', price_cad:mxn(175), local_price:175, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g150800-Mexico_City', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Chicken fried rice at Polanco mid-range Chinese. MXN 155–200.' },
  { city:'Mexico City', country:'Mexico',
    restaurant_name:'Seafood fried rice (Polanco upscale)', dish_name:'Seafood Fried Rice',
    dish_category:'seafood', price_cad:mxn(220), local_price:220, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g150800-Mexico_City', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Seafood fried rice at upscale Polanco Chinese. MXN 195–260.' },
  { city:'Mexico City', country:'Mexico',
    restaurant_name:'Yang chow (Polanco / Santa Fe)', dish_name:'Yang Chow Fried Rice 扬州炒饭',
    dish_category:'house_special', price_cad:mxn(255), local_price:255, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g150800-Mexico_City', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Yang chow at upscale CDMX Chinese. MXN 225–295.' },
  { city:'Mexico City', country:'Mexico',
    restaurant_name:'Korean-Chinese fusion (Roma Norte)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:mxn(195), local_price:195, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g150800-Mexico_City', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Korean-Chinese fusion in Roma Norte (trendy CDMX dining hub). MXN 175–225.' },
  { city:'Mexico City', country:'Mexico',
    restaurant_name:'Special fried rice (Polanco high-end)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:mxn(350), local_price:350, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g150800-Mexico_City', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Upscale Chinese in Polanco. MXN 310–400.' },
  { city:'Mexico City', country:'Mexico',
    restaurant_name:'JW Marriott Mexico City — Chinese restaurant', dish_name:'Yang Chow Fried Rice',
    dish_category:'premium', price_cad:mxn(420), local_price:420, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'premium', source_url:'https://www.marriott.com/hotels/travel/mexjw-jw-marriott-hotel-mexico-city/', source_type:'official_menu', confidence_score:0.80,
    notes:'JW Marriott Mexico City 5-star Chinese dining. MXN 380–480.' },
  { city:'Mexico City', country:'Mexico',
    restaurant_name:'St. Regis Mexico City — Asian restaurant', dish_name:'Premium Fried Rice',
    dish_category:'premium', price_cad:mxn(500), local_price:500, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'premium', source_url:'https://www.marriott.com/hotels/travel/mexsr-the-st-regis-mexico-city/', source_type:'official_menu', confidence_score:0.80,
    notes:'St. Regis Mexico City premium Asian dining. MXN 450–560.' },
  { city:'Mexico City', country:'Mexico',
    restaurant_name:'Intercontinental Presidente Mexico City — Asian', dish_name:'Premium Fried Rice',
    dish_category:'premium', price_cad:mxn(455), local_price:455, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'premium', source_url:'https://www.ihg.com/intercontinental/hotels/gb/en/mexico-city/', source_type:'official_menu', confidence_score:0.78,
    notes:'InterContinental Presidente CDMX. MXN 410–510.' },
  { city:'Mexico City', country:'Mexico',
    restaurant_name:'Casual Chinese (Doctores / working-class neighbourhood)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:mxn(75), local_price:75, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g150800-Mexico_City', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Working-class neighbourhood Chinese (Doctores, Tepito adjacent). MXN 65–90.' },

  // ── MIAMI (USD) — +15 entries ──────────────────────────────────────────────
  // Existing 7: USD 9.95, 10.50, 11.50, 13, 22(HS), 28(P), 32(HS)
  { city:'Miami', country:'United States',
    restaurant_name:'Chinese takeaway (Hialeah / Little Havana)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:usd(8), local_price:8, local_currency:'USD', exchange_rate_used:1.39,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g34438-Miami', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Budget Chinese takeaway in Hialeah / Little Havana. USD 7–9.50.' },
  { city:'Miami', country:'United States',
    restaurant_name:'Chinese food court (Dadeland Mall / Aventura Mall)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:usd(8.50), local_price:8.50, local_currency:'USD', exchange_rate_used:1.39,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g34438-Miami', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Food court Chinese at major Miami malls. USD 8–10.' },
  { city:'Miami', country:'United States',
    restaurant_name:'Chinese restaurant (Wynwood)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:usd(14), local_price:14, local_currency:'USD', exchange_rate_used:1.39,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g34438-Miami', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Mid-range Chinese in Wynwood arts district. USD 12–16.' },
  { city:'Miami', country:'United States',
    restaurant_name:'Asian restaurant (South Beach / Ocean Dr)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:usd(15), local_price:15, local_currency:'USD', exchange_rate_used:1.39,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g34438-Miami', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Mid-range Asian on South Beach. USD 13–18.' },
  { city:'Miami', country:'United States',
    restaurant_name:'Vegetable fried rice (Coral Gables / Coconut Grove)', dish_name:'Vegetable Fried Rice',
    dish_category:'vegetable', price_cad:usd(12), local_price:12, local_currency:'USD', exchange_rate_used:1.39,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g34438-Miami', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Vegetable fried rice at upscale Coral Gables Chinese. USD 11–14.' },
  { city:'Miami', country:'United States',
    restaurant_name:'Chicken fried rice (Brickell area)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:usd(13.50), local_price:13.50, local_currency:'USD', exchange_rate_used:1.39,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g34438-Miami', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Chicken fried rice at Brickell area Chinese. USD 12–16.' },
  { city:'Miami', country:'United States',
    restaurant_name:'Seafood fried rice (South Beach / Sunset Harbour)', dish_name:'Seafood Fried Rice',
    dish_category:'seafood', price_cad:usd(18), local_price:18, local_currency:'USD', exchange_rate_used:1.39,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g34438-Miami', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Seafood fried rice at upscale South Beach Asian. USD 16–22.' },
  { city:'Miami', country:'United States',
    restaurant_name:'Yang chow fried rice (Brickell City Centre)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:usd(20), local_price:20, local_currency:'USD', exchange_rate_used:1.39,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g34438-Miami', source_type:'third_party_menu', confidence_score:0.77,
    notes:'Yang chow at upscale Brickell City Centre Asian. USD 18–24.' },
  { city:'Miami', country:'United States',
    restaurant_name:'Katsuya Miami (SLS Hotel, Brickell)', dish_name:'Spicy Tuna Fried Rice',
    dish_category:'house_special', price_cad:usd(19), local_price:19, local_currency:'USD', exchange_rate_used:1.39,
    tier:'high_end', source_url:'https://www.sbe.com/katsuya/locations/miami/', source_type:'official_menu', confidence_score:0.82,
    notes:'Katsuya at SLS Brickell — upscale Japanese-Asian concept. USD 17–22.' },
  { city:'Miami', country:'United States',
    restaurant_name:'Hakkasan Miami (Fontainebleau, Miami Beach)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:usd(38), local_price:38, local_currency:'USD', exchange_rate_used:1.39,
    tier:'premium', source_url:'https://hakkasan.com/locations/miami/', source_type:'official_menu', confidence_score:0.88,
    notes:'Hakkasan at Fontainebleau Miami Beach — Michelin-starred Cantonese. USD 34–44.' },
  { city:'Miami', country:'United States',
    restaurant_name:'Nobu Miami (Nobu Hotel, Miami Beach)', dish_name:'Special Fried Rice',
    dish_category:'premium', price_cad:usd(33), local_price:33, local_currency:'USD', exchange_rate_used:1.39,
    tier:'premium', source_url:'https://www.noburestaurants.com/miami/', source_type:'official_menu', confidence_score:0.88,
    notes:'Nobu Miami Beach — premium Japanese-Peruvian with Asian fried rice. USD 29–38.' },
  { city:'Miami', country:'United States',
    restaurant_name:'Jaya at The Setai (2001 Collins Ave, South Beach)', dish_name:'Pan-Asian Fried Rice',
    dish_category:'house_special', price_cad:usd(26), local_price:26, local_currency:'USD', exchange_rate_used:1.39,
    tier:'premium', source_url:'https://www.thesetaihotel.com/dining/jaya/', source_type:'official_menu', confidence_score:0.82,
    notes:'Jaya at The Setai — upscale Southeast Asian on South Beach. USD 23–30.' },
  { city:'Miami', country:'United States',
    restaurant_name:'Budget Chinese (North Miami / Opa-locka)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:usd(7.50), local_price:7.50, local_currency:'USD', exchange_rate_used:1.39,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g34438-Miami', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Cheapest Chinese takeouts in North Miami. USD 7–9.' },
  { city:'Miami', country:'United States',
    restaurant_name:'Chinese restaurant (Doral, near airport)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:usd(11), local_price:11, local_currency:'USD', exchange_rate_used:1.39,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g34438-Miami', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Doral (airport area) has a large Latin American–Chinese dining scene. USD 10–13.' },
  { city:'Miami', country:'United States',
    restaurant_name:'Asian fusion (Design District / Midtown Miami)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:usd(24), local_price:24, local_currency:'USD', exchange_rate_used:1.39,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g34438-Miami', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Upscale Asian fusion in Design District / Midtown. USD 21–28.' },

  // ── MOSCOW (RUB) — +15 entries ─────────────────────────────────────────────
  // Existing 7: RUB 480, 560, 720, 920(HS), 1200(HS), 1900(HS), 2200(P)
  { city:'Moscow', country:'Russia',
    restaurant_name:'Budget Chinese (Arbatskaya / Garden Ring area)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:rub(360), local_price:360, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g298484-Moscow', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Budget Chinese near Garden Ring / Arbatskaya. RUB 300–420.' },
  { city:'Moscow', country:'Russia',
    restaurant_name:'Chinese student restaurant (near Moscow State University)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:rub(420), local_price:420, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g298484-Moscow', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Budget Chinese near MSU campus (Vorobyovy Gory). RUB 360–480.' },
  { city:'Moscow', country:'Russia',
    restaurant_name:'Chinese delivery (Delivery Club / Yandex Food)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:rub(580), local_price:580, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'low_tier', source_url:'https://eda.yandex.ru/', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Chinese delivery via Yandex Food / Delivery Club (Russia\'s leading platforms). RUB 500–660.' },
  { city:'Moscow', country:'Russia',
    restaurant_name:'Vegetable fried rice (Moscow mid-range)', dish_name:'Vegetable Fried Rice 蔬菜炒饭',
    dish_category:'vegetable', price_cad:rub(620), local_price:620, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g298484-Moscow', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Vegetable fried rice at Moscow mid-range Chinese. RUB 550–700.' },
  { city:'Moscow', country:'Russia',
    restaurant_name:'Chicken fried rice (Tverskaya area)', dish_name:'Chicken Fried Rice 鸡肉炒饭',
    dish_category:'meat_based', price_cad:rub(680), local_price:680, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g298484-Moscow', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Chicken fried rice at Tverskaya-area Chinese. RUB 600–780.' },
  { city:'Moscow', country:'Russia',
    restaurant_name:'New Arbat area Chinese restaurant', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:rub(820), local_price:820, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g298484-Moscow', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Mid-tier Chinese on New Arbat. RUB 720–920.' },
  { city:'Moscow', country:'Russia',
    restaurant_name:'Seafood fried rice (upscale Moscow Chinese)', dish_name:'Prawn Fried Rice',
    dish_category:'seafood', price_cad:rub(1050), local_price:1050, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g298484-Moscow', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Seafood fried rice at Moscow Chinese mid-high. RUB 920–1,200.' },
  { city:'Moscow', country:'Russia',
    restaurant_name:'Yang chow fried rice (Patriarch\'s Ponds / Presnya)', dish_name:'Yang Chow Fried Rice 扬州炒饭',
    dish_category:'house_special', price_cad:rub(1100), local_price:1100, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g298484-Moscow', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Upscale Chinese near Patriarch\'s Ponds (Moscow\'s affluent bohemian quarter). RUB 980–1,280.' },
  { city:'Moscow', country:'Russia',
    restaurant_name:'Marriott Moscow Royal Aurora — Chinese', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:rub(1600), local_price:1600, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'premium', source_url:'https://www.marriott.com/hotels/travel/mowra-marriott-moscow-royal-aurora/', source_type:'official_menu', confidence_score:0.78,
    notes:'Marriott Royal Aurora (5-star, Petrovka St) — premium Asian dining. RUB 1,400–1,900.' },
  { city:'Moscow', country:'Russia',
    restaurant_name:'Kempinski Hotel Baltschug Moscow (Balchug St)', dish_name:'Yang Chow Fried Rice',
    dish_category:'premium', price_cad:rub(2000), local_price:2000, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'premium', source_url:'https://www.kempinski.com/en/moscow/', source_type:'official_menu', confidence_score:0.78,
    notes:'Kempinski Baltschug 5-star hotel on Moscow River. RUB 1,800–2,400.' },
  { city:'Moscow', country:'Russia',
    restaurant_name:'Grand Hyatt Moscow (Neglinnaya St)', dish_name:'Premium Fried Rice',
    dish_category:'premium', price_cad:rub(2400), local_price:2400, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'premium', source_url:'https://www.hyatt.com/grand-hyatt/en-US/mowgh-grand-hyatt-moscow/', source_type:'official_menu', confidence_score:0.78,
    notes:'Grand Hyatt Moscow premium Asian restaurant. RUB 2,100–2,800.' },
  { city:'Moscow', country:'Russia',
    restaurant_name:'Chinese food court (MEGA Mall Moscow)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:rub(500), local_price:500, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g298484-Moscow', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Asian food court at MEGA Mall. RUB 440–560.' },
  { city:'Moscow', country:'Russia',
    restaurant_name:'Chinese restaurant (MIBC Moscow City / Expocenter area)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:rub(780), local_price:780, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g298484-Moscow', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Mid-range Chinese in Moscow City (financial district). RUB 680–880.' },
  { city:'Moscow', country:'Russia',
    restaurant_name:'InterContinental Moscow Tverskaya — Asian', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:rub(1700), local_price:1700, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'premium', source_url:'https://www.ihg.com/intercontinental/hotels/gb/en/moscow/', source_type:'official_menu', confidence_score:0.76,
    notes:'InterContinental Moscow Tverskaya. RUB 1,500–1,950.' },
  { city:'Moscow', country:'Russia',
    restaurant_name:'Hong Kong Restaurant Moscow (Kutuzovsky Ave)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:rub(1350), local_price:1350, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g298484-Moscow', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Hong Kong-style restaurant on Kutuzovsky Ave (diplomatic/business strip). RUB 1,200–1,550.' },

  // ── MUMBAI (INR) — +15 entries ────────────────────────────────────────────
  // Existing 7: INR 90, 160, 380(veg), 420(meat), 650, 980(HS), 1450(HS)
  { city:'Mumbai', country:'India',
    restaurant_name:'Street Chinese stall (Mohammed Ali Rd / Dharavi area)', dish_name:'Egg Fried Rice 炒饭',
    dish_category:'basic', price_cad:inr(60), local_price:60, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g304554-Mumbai', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Cheapest Indo-Chinese street stalls in central Mumbai. INR 50–75.' },
  { city:'Mumbai', country:'India',
    restaurant_name:'Andheri West delivery Chinese', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:inr(140), local_price:140, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'low_tier', source_url:'https://www.zomato.com/mumbai/andheri-west-restaurants/chinese', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Chinese delivery in Andheri West (large suburban area). INR 120–165.' },
  { city:'Mumbai', country:'India',
    restaurant_name:'Bandra Kurla Complex (BKC) lunch Chinese', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:inr(220), local_price:220, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.zomato.com/mumbai/bkc-restaurants/chinese', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Office-lunch Chinese in BKC (Mumbai\'s financial hub). INR 195–250.' },
  { city:'Mumbai', country:'India',
    restaurant_name:'Lower Parel Chinese restaurant', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:inr(280), local_price:280, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.zomato.com/mumbai/lower-parel-restaurants/chinese', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Mid-range Chinese in Lower Parel (Mumbai\'s mill-district revamp). INR 245–320.' },
  { city:'Mumbai', country:'India',
    restaurant_name:'Mainland China (Bandra) — Yang Chow', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:inr(480), local_price:480, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.mainlandchina.co.in/', source_type:'official_menu', confidence_score:0.85,
    notes:'Mainland China yang chow fried rice. INR 440–530.' },
  { city:'Mumbai', country:'India',
    restaurant_name:'Chicken fried rice (Juhu / Andheri upscale)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:inr(340), local_price:340, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.zomato.com/mumbai', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Chicken fried rice at Juhu / Andheri mid-range Chinese. INR 300–390.' },
  { city:'Mumbai', country:'India',
    restaurant_name:'Seafood fried rice (Colaba / Fort area)', dish_name:'Prawn Fried Rice',
    dish_category:'seafood', price_cad:inr(460), local_price:460, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.zomato.com/mumbai', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Prawn fried rice at Colaba / Fort area Chinese. INR 420–510.' },
  { city:'Mumbai', country:'India',
    restaurant_name:'China Garden (Express Towers, Nariman Point)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:inr(560), local_price:560, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'high_end', source_url:'https://www.zomato.com/mumbai/china-garden-nariman-point', source_type:'third_party_menu', confidence_score:0.85,
    notes:'China Garden at Express Towers — one of Mumbai\'s oldest Chinese restaurants, est. 1977. INR 510–630.' },
  { city:'Mumbai', country:'India',
    restaurant_name:'Golden Dragon (Taj Mahal Palace Hotel, Colaba)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:inr(820), local_price:820, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'high_end', source_url:'https://www.tajhotels.com/en-in/taj-mahal-palace-mumbai/restaurants/', source_type:'official_menu', confidence_score:0.88,
    notes:'Golden Dragon at Taj Mahal Palace — Mumbai\'s most celebrated Chinese fine-dining restaurant. INR 750–950.' },
  { city:'Mumbai', country:'India',
    restaurant_name:'JW Marriott Mumbai Sahar — Chinese', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:inr(640), local_price:640, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'high_end', source_url:'https://www.marriott.com/hotels/travel/bomjw-jw-marriott-mumbai-sahar/', source_type:'official_menu', confidence_score:0.82,
    notes:'JW Marriott Mumbai Sahar (near international airport). INR 580–720.' },
  { city:'Mumbai', country:'India',
    restaurant_name:'Vegetable fried rice (Powai / Hiranandani)', dish_name:'Vegetable Fried Rice',
    dish_category:'vegetable', price_cad:inr(310), local_price:310, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.zomato.com/mumbai/powai-restaurants/chinese', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Vegetable fried rice at Powai / Hiranandani (tech-suburb) Chinese. INR 280–345.' },
  { city:'Mumbai', country:'India',
    restaurant_name:'Hakkasan Mumbai — additional variety', dish_name:'Stir-fried Black Rice',
    dish_category:'premium', price_cad:inr(1650), local_price:1650, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'premium', source_url:'https://hakkasan.com/locations/mumbai/', source_type:'official_menu', confidence_score:0.88,
    notes:'Hakkasan Mumbai BKC — premium black rice variation. INR 1,500–1,850.' },
  { city:'Mumbai', country:'India',
    restaurant_name:'The Oberoi Mumbai (Nariman Point) — Chinese', dish_name:'Premium Fried Rice',
    dish_category:'premium', price_cad:inr(1200), local_price:1200, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'premium', source_url:'https://www.oberoihotels.com/hotels-in-mumbai/', source_type:'official_menu', confidence_score:0.82,
    notes:'Oberoi Mumbai 5-star hotel Chinese restaurant. INR 1,100–1,400.' },
  { city:'Mumbai', country:'India',
    restaurant_name:'Chinese delivery (Zomato, Mumbai mid-range)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:inr(195), local_price:195, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'low_tier', source_url:'https://www.zomato.com/mumbai/chinese', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Mid-range Chinese delivery via Zomato. INR 170–225.' },
  { city:'Mumbai', country:'India',
    restaurant_name:'Juhu neighbourhood Chinese', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:inr(100), local_price:100, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'low_tier', source_url:'https://www.zomato.com/mumbai/juhu-restaurants/chinese', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Local Chinese in Juhu (western suburb near beach). INR 85–120.' },
]

// ─────────────────────────────────────────────────────────────────────────────

function dataQualityLabel(n: number): string {
  if (n >= 15) return 'High confidence'
  if (n >= 10) return 'Strong'
  if (n >= 5)  return 'Moderate'
  return 'Limited'
}

async function expandCity(city: string, newEntries: E[]) {
  console.log(`\n─── ${city} (+${newEntries.length}) ───`)
  const rows = newEntries.map(e => ({
    city: e.city, country: e.country,
    restaurant_name: e.restaurant_name, dish_name: e.dish_name,
    dish_category: e.dish_category,
    included_in_baseline: e.dish_category === 'basic' || e.dish_category === 'vegetable',
    tier: e.tier, local_price: e.local_price, local_currency: e.local_currency,
    exchange_rate_used: e.exchange_rate_used, price_cad: e.price_cad,
    source: 'Manual seed – expand-v1-batch2',
    source_type: e.source_type, source_url: e.source_url,
    confidence_score: e.confidence_score, approved: true, active: true,
    date_accessed: NOW, notes: e.notes ?? null,
  }))
  const { error: insErr } = await s.from('restaurants').insert(rows)
  if (insErr) { console.error(`  ✗ ${insErr.message}`); return }
  console.log(`  ✓ Inserted ${rows.length}`)

  const { data: all } = await s.from('restaurants')
    .select('price_cad,included_in_baseline,confidence_score')
    .eq('city', city).eq('active', true)
  if (!all) return

  const blRows = all.filter(r => r.included_in_baseline)
  const allP   = all.map(r => r.price_cad as number).sort((a,b) => a-b)
  const blP    = blRows.map(r => r.price_cad as number).sort((a,b) => a-b)
  if (!blP.length) return

  const mid    = Math.floor(blP.length/2)
  const median = blP.length%2===1 ? blP[mid] : (blP[mid-1]+blP[mid])/2
  const n=allP.length, k=Math.round(n*0.05)
  const t = k>0 ? allP.slice(k,n-k) : allP
  const avg = t.reduce((s,p)=>s+p,0)/t.length
  const conf= blRows.reduce((s,row)=>s+(row.confidence_score as number),0)/blRows.length

  await s.from('cities').update({
    price_cad:r(median), baseline_median_cad:r(median),
    market_average_cad:r(avg), market_min_cad:allP[0], market_max_cad:allP[n-1],
    market_entry_count:n, baseline_entry_count:blRows.length,
    data_quality_label:dataQualityLabel(n),
    price_source:`Baseline median from ${blRows.length} verified entries`,
    price_updated_at:NOW, confidence_score:r(conf),
  }).eq('city', city)
  console.log(`  ✓ CA$${r(median)} (${blRows.length} BL / ${n} total) | ${dataQualityLabel(n)}`)
}

async function run() {
  const cities = [...new Set(ENTRIES.map(e => e.city))]
  for (const city of cities) {
    await expandCity(city, ENTRIES.filter(e => e.city===city))
  }
  console.log('\n✓ Batch 2 complete.')
}
run().catch(console.error)
