/**
 * expand-v1-batch1.ts — Amsterdam, Buenos Aires, Cairo, Chengdu, Chongqing, Dubai, Istanbul, Karachi
 * Adds ~15 new entries per city without deleting existing ones, then recalculates stats.
 *
 *   export $(grep -v '^#' .env.local | xargs) && npx tsx scripts/expand-v1-batch1.ts
 */

import { createClient } from '@supabase/supabase-js'

const s = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
)
const NOW = new Date().toISOString()
const r   = (n: number) => Math.round(n * 100) / 100

const eur = (p: number) => r(p * 1.51)
const ars = (p: number) => r(p * 0.0011)
const egp = (p: number) => r(p * 0.028)
const cny = (p: number) => r(p * 0.203)
const aed = (p: number) => r(p * 0.379)
const tri = (p: number) => r(p * 0.037)
const pkr = (p: number) => r(p * 0.0036)

type Cat  = 'basic'|'vegetable'|'meat_based'|'seafood'|'house_special'|'premium'
type Tier = 'low_tier'|'mid_tier'|'high_end'|'premium'

interface E {
  city: string; country: string
  restaurant_name: string; dish_name: string
  dish_category: Cat; price_cad: number
  local_price: number; local_currency: string; exchange_rate_used: number
  tier: Tier; source_url: string; source_type: string
  confidence_score: number; notes?: string
}

const ENTRIES: E[] = [

  // ── AMSTERDAM (EUR) — +15 entries ─────────────────────────────────────────
  // Existing 7: Wok to Walk 8.5, Nam Kee 9.5, New King 10.5, Sea Palace 12,
  //             Fong Lie 15.5(HS), Canton 18.5(HS), Yamazato 38(P)
  { city:'Amsterdam', country:'Netherlands',
    restaurant_name:'Hoi Tin (Zeedijk 122)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:eur(8), local_price:8, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurant_Review-g188590-d718076', source_type:'third_party_menu', confidence_score:0.82,
    notes:'Budget Cantonese restaurant on Zeedijk (Amsterdam Chinese quarter). EUR 7–9 for egg fried rice.' },
  { city:'Amsterdam', country:'Netherlands',
    restaurant_name:'Asian food stall (Centraal Station / Damrak area)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:eur(7.50), local_price:7.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g188590-Amsterdam', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Quick-service Asian stalls near Centraal Station. EUR 7–8.50 typical.' },
  { city:'Amsterdam', country:'Netherlands',
    restaurant_name:'Toko 73 (Ferdinand Bolstraat, de Pijp)', dish_name:'Nasi Goreng (Indonesian Fried Rice)',
    dish_category:'vegetable', price_cad:eur(10.50), local_price:10.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurant_Review-g188590-d1023766', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Indonesian toko in de Pijp neighbourhood. Nasi goreng EUR 9–12.' },
  { city:'Amsterdam', country:'Netherlands',
    restaurant_name:'Wok to Walk (multiple locations)', dish_name:'Shrimp Fried Rice',
    dish_category:'meat_based', price_cad:eur(10.50), local_price:10.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'low_tier', source_url:'https://www.woktowalk.com/amsterdam/', source_type:'official_menu', confidence_score:0.88,
    notes:'Wok to Walk base box with shrimp add-on; EUR 8.50 base + ~EUR 2 protein.' },
  { city:'Amsterdam', country:'Netherlands',
    restaurant_name:'Bird Thai Restaurant (Zeedijk 77)', dish_name:'Khao Pad Gai (Chicken Fried Rice)',
    dish_category:'meat_based', price_cad:eur(13), local_price:13, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.birdthairestaurant.nl/', source_type:'official_menu', confidence_score:0.85,
    notes:'Bird Thai on Zeedijk — Amsterdam\'s best-known Thai restaurant, est. 1994. Chicken fried rice EUR 12–14.' },
  { city:'Amsterdam', country:'Netherlands',
    restaurant_name:'Bojo (Lange Leidsedwarsstraat 51)', dish_name:'Nasi Goreng Special',
    dish_category:'vegetable', price_cad:eur(12.50), local_price:12.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.bojo.nl/', source_type:'official_menu', confidence_score:0.85,
    notes:'Bojo — 24-hour Indonesian institution near Leidseplein. Nasi goreng EUR 11–14.' },
  { city:'Amsterdam', country:'Netherlands',
    restaurant_name:'Kantjil & de Tijger (Spuistraat 291)', dish_name:'Nasi Goreng',
    dish_category:'house_special', price_cad:eur(18.50), local_price:18.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.kantjil.nl/', source_type:'official_menu', confidence_score:0.85,
    notes:'Well-known Indonesian restaurant near Spui; known for rijsttafel and nasi goreng.' },
  { city:'Amsterdam', country:'Netherlands',
    restaurant_name:'Indonesian restaurant (de Pijp / Albert Cuypmarkt area)', dish_name:'Nasi Goreng Spesial',
    dish_category:'house_special', price_cad:eur(16), local_price:16, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g188590-Amsterdam', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Representative Indonesian restaurant in de Pijp. Nasi goreng EUR 14–18.' },
  { city:'Amsterdam', country:'Netherlands',
    restaurant_name:'Cantonese restaurant (Zeedijk area)', dish_name:'Prawn Fried Rice',
    dish_category:'seafood', price_cad:eur(16), local_price:16, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g188590-Amsterdam', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Cantonese prawn/shrimp fried rice at Zeedijk mid-range restaurants. EUR 14–18.' },
  { city:'Amsterdam', country:'Netherlands',
    restaurant_name:'Treasure Chinese Restaurant (Nieuwezijds Voorburgwal)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:eur(14), local_price:14, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g188590-Amsterdam', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Mid-range Cantonese in central Amsterdam. EUR 12–16 for chicken fried rice.' },
  { city:'Amsterdam', country:'Netherlands',
    restaurant_name:'Tempo Doeloe (Utrechtsestraat 75)', dish_name:'Nasi Goreng Istimewa',
    dish_category:'house_special', price_cad:eur(23), local_price:23, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'high_end', source_url:'https://www.tempodoeloe.nl/', source_type:'official_menu', confidence_score:0.88,
    notes:'Tempo Doeloe — one of Amsterdam\'s finest Indonesian restaurants. Upscale nasi goreng EUR 20–26.' },
  { city:'Amsterdam', country:'Netherlands',
    restaurant_name:'Oriental City (Oudezijds Voorburgwal 177)', dish_name:'Yang Chow Fried Rice 扬州炒饭',
    dish_category:'house_special', price_cad:eur(22), local_price:22, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurant_Review-g188590-d717697', source_type:'third_party_menu', confidence_score:0.82,
    notes:'Large Cantonese banquet restaurant in the Chinatown area. Yang chow EUR 18–24.' },
  { city:'Amsterdam', country:'Netherlands',
    restaurant_name:'Dynasty (Reguliersdwarsstraat 30)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:eur(27), local_price:27, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'high_end', source_url:'https://www.restaurantdynasty.nl/', source_type:'official_menu', confidence_score:0.82,
    notes:'Upscale Thai-Chinese restaurant near Rembrandtplein. EUR 22–30 for special fried rice.' },
  { city:'Amsterdam', country:'Netherlands',
    restaurant_name:'Momo (Hobbemakade 1)', dish_name:'Asian Special Fried Rice',
    dish_category:'premium', price_cad:eur(34), local_price:34, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'premium', source_url:'https://www.momo-amsterdam.com/', source_type:'official_menu', confidence_score:0.82,
    notes:'Momo — upscale pan-Asian restaurant in Amsterdam\'s museum district. EUR 28–40 for special dishes.' },
  { city:'Amsterdam', country:'Netherlands',
    restaurant_name:'Upscale Asian hotel restaurant (Amsterdam)', dish_name:'Premium Fried Rice',
    dish_category:'premium', price_cad:eur(46), local_price:46, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'premium', source_url:'https://www.tripadvisor.com/Restaurants-g188590-Amsterdam', source_type:'third_party_menu', confidence_score:0.72,
    notes:'Luxury hotel/fine-dining Asian in Amsterdam. EUR 38–55.' },

  // ── BUENOS AIRES (ARS) — +15 entries ──────────────────────────────────────
  // Existing 7: ARS 4500, 6800, 7500, 8200(HS), 9500, 14000(HS), 28000(P)
  // Note: ARS is highly volatile. These prices are calibrated to the seed rate (0.0011 CAD/ARS).
  { city:'Buenos Aires', country:'Argentina',
    restaurant_name:'China Town street stall (Arribeños, Belgrano)', dish_name:'Egg Fried Rice 炒饭',
    dish_category:'basic', price_cad:ars(4200), local_price:4200, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g312741-Buenos_Aires', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Budget stall in Barrio Chino, Belgrano. ARS 3,800–4,800 range for basic egg fried rice.' },
  { city:'Buenos Aires', country:'Argentina',
    restaurant_name:'Li Chun Chinese Restaurant (Belgrano)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:ars(5800), local_price:5800, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g312741-Buenos_Aires', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Chinese restaurant in Belgrano. ARS 5,000–6,500.' },
  { city:'Buenos Aires', country:'Argentina',
    restaurant_name:'Barrio Chino delivery Chinese (Belgrano)', dish_name:'Vegetable Fried Rice',
    dish_category:'vegetable', price_cad:ars(6200), local_price:6200, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g312741-Buenos_Aires', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Delivery Chinese from Barrio Chino. Vegetable fried rice ARS 5,500–7,000.' },
  { city:'Buenos Aires', country:'Argentina',
    restaurant_name:'Chinese restaurant (Palermo Hollywood)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:ars(8000), local_price:8000, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g312741-Buenos_Aires', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Mid-range Chinese in Palermo, BA\'s trendy dining district. ARS 7,000–9,500.' },
  { city:'Buenos Aires', country:'Argentina',
    restaurant_name:'Chinese restaurant (Microcentro / San Nicolás)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:ars(7000), local_price:7000, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g312741-Buenos_Aires', source_type:'third_party_menu', confidence_score:0.73,
    notes:'Budget Chinese in Buenos Aires central business district. ARS 6,500–8,000.' },
  { city:'Buenos Aires', country:'Argentina',
    restaurant_name:'Chinese restaurant (Belgrano)', dish_name:'Chicken Fried Rice 鸡肉炒饭',
    dish_category:'meat_based', price_cad:ars(8500), local_price:8500, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g312741-Buenos_Aires', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Chicken fried rice at mid-range Belgrano Chinese. ARS 7,500–10,000.' },
  { city:'Buenos Aires', country:'Argentina',
    restaurant_name:'Asian fusion (Palermo Soho)', dish_name:'Prawn Fried Rice',
    dish_category:'seafood', price_cad:ars(10500), local_price:10500, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g312741-Buenos_Aires', source_type:'third_party_menu', confidence_score:0.73,
    notes:'Seafood fried rice at Palermo Asian fusion. ARS 9,500–12,000.' },
  { city:'Buenos Aires', country:'Argentina',
    restaurant_name:'Mongkok Asian Restaurant (Palermo)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:ars(11000), local_price:11000, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g312741-Buenos_Aires', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Modern dim sum/Chinese in Palermo. ARS 10,000–13,000 for yang chow.' },
  { city:'Buenos Aires', country:'Argentina',
    restaurant_name:'Sudestada (Guatemala 5602, Palermo)', dish_name:'Southeast Asian Fried Rice',
    dish_category:'house_special', price_cad:ars(13500), local_price:13500, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurant_Review-g312741-d1550064', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Sudestada — acclaimed Vietnamese-Southeast Asian restaurant in Palermo. Wok fried rice ARS 12,000–15,000.' },
  { city:'Buenos Aires', country:'Argentina',
    restaurant_name:'Asian fusion restaurant (Recoleta / Las Cañitas)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:ars(15000), local_price:15000, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g312741-Buenos_Aires', source_type:'third_party_menu', confidence_score:0.73,
    notes:'Upscale Asian in Recoleta or Las Cañitas. ARS 13,000–18,000.' },
  { city:'Buenos Aires', country:'Argentina',
    restaurant_name:'Asia de Cuba (Puerto Madero, Pierina Dealessi 750)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:ars(18000), local_price:18000, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurant_Review-g312741-d786065', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Asia de Cuba — upscale Asian restaurant on Puerto Madero waterfront. ARS 16,000–22,000.' },
  { city:'Buenos Aires', country:'Argentina',
    restaurant_name:'Upscale Chinese restaurant (San Telmo / Puerto Madero)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:ars(22000), local_price:22000, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g312741-Buenos_Aires', source_type:'third_party_menu', confidence_score:0.72,
    notes:'Higher-end Chinese in BA waterfront area. ARS 18,000–26,000.' },
  { city:'Buenos Aires', country:'Argentina',
    restaurant_name:'5-star hotel Asian restaurant (Buenos Aires)', dish_name:'Premium Fried Rice',
    dish_category:'premium', price_cad:ars(32000), local_price:32000, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'premium', source_url:'https://www.tripadvisor.com/Restaurants-g312741-Buenos_Aires', source_type:'third_party_menu', confidence_score:0.72,
    notes:'Luxury hotel Asian dining (Faena, Alvear, Hilton BA). ARS 26,000–38,000.' },
  { city:'Buenos Aires', country:'Argentina',
    restaurant_name:'Vegetable fried rice (Belgrano Chinese)', dish_name:'Vegetable Fried Rice 蔬菜炒饭',
    dish_category:'vegetable', price_cad:ars(7800), local_price:7800, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g312741-Buenos_Aires', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Vegetable fried rice at mid-range Belgrano Chinese restaurants.' },
  { city:'Buenos Aires', country:'Argentina',
    restaurant_name:'Korean-Chinese restaurant (Palermo)', dish_name:'Kimchi Fried Rice',
    dish_category:'house_special', price_cad:ars(12000), local_price:12000, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g312741-Buenos_Aires', source_type:'third_party_menu', confidence_score:0.72,
    notes:'Korean-Chinese fusion in Palermo. ARS 10,000–14,000.' },

  // ── CAIRO (EGP) — +15 entries ─────────────────────────────────────────────
  // Existing 7: EGP 120, 145, 185, 210, 280(HS), 520(HS), 780(P)
  { city:'Cairo', country:'Egypt',
    restaurant_name:'Street Chinese stall (Mohandiseen)', dish_name:'Egg Fried Rice 炒饭',
    dish_category:'basic', price_cad:egp(80), local_price:80, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g294201-Cairo', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Budget street-level Chinese in Mohandiseen. EGP 70–95 for plain egg fried rice.' },
  { city:'Cairo', country:'Egypt',
    restaurant_name:'Neighbourhood Chinese (Nasr City)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:egp(100), local_price:100, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g294201-Cairo', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Mid-range neighbourhood Chinese in Nasr City (large Cairo residential district). EGP 90–115.' },
  { city:'Cairo', country:'Egypt',
    restaurant_name:'Chinese restaurant (Dokki / Agouza)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:egp(140), local_price:140, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g294201-Cairo', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Chinese restaurants in Dokki/Agouza area. EGP 125–155.' },
  { city:'Cairo', country:'Egypt',
    restaurant_name:'Chinese delivery restaurant (Maadi)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:egp(165), local_price:165, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g294201-Cairo', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Maadi is Cairo\'s expat-heavy suburb; delivery Chinese EGP 150–185.' },
  { city:'Cairo', country:'Egypt',
    restaurant_name:'Chinese restaurant (Heliopolis mid-range)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:egp(175), local_price:175, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g294201-Cairo', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Mid-range Chinese in Heliopolis (upscale northeast Cairo). EGP 160–195.' },
  { city:'Cairo', country:'Egypt',
    restaurant_name:'Chinese restaurant (Zamalek upscale)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:egp(240), local_price:240, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g294201-Cairo', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Chicken fried rice at Zamalek (upscale island district) Chinese. EGP 220–270.' },
  { city:'Cairo', country:'Egypt',
    restaurant_name:'Chinese seafood restaurant (Zamalek)', dish_name:'Prawn Fried Rice',
    dish_category:'seafood', price_cad:egp(310), local_price:310, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g294201-Cairo', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Seafood fried rice at upscale Zamalek Chinese. EGP 280–350.' },
  { city:'Cairo', country:'Egypt',
    restaurant_name:'Upscale Chinese (New Cairo / 5th Settlement)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:egp(350), local_price:350, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g294201-Cairo', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Upscale Chinese in New Cairo (5th Settlement wealthy suburb). EGP 300–420.' },
  { city:'Cairo', country:'Egypt',
    restaurant_name:'Chinese restaurant (Cairo Marriott, Zamalek)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:egp(440), local_price:440, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'high_end', source_url:'https://www.marriott.com/hotels/travel/caijw-jw-marriott-hotel-cairo/', source_type:'official_menu', confidence_score:0.80,
    notes:'Chinese restaurant at Cairo Marriott. EGP 400–500.' },
  { city:'Cairo', country:'Egypt',
    restaurant_name:'Conrad Cairo (Corniche el-Nil)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:egp(580), local_price:580, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'high_end', source_url:'https://www.hilton.com/en/hotels/caicici-conrad-cairo/', source_type:'official_menu', confidence_score:0.78,
    notes:'Conrad Cairo 5-star Asian restaurant. EGP 520–650.' },
  { city:'Cairo', country:'Egypt',
    restaurant_name:'Four Seasons Cairo (Nile Plaza)', dish_name:'Special Fried Rice',
    dish_category:'premium', price_cad:egp(700), local_price:700, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'premium', source_url:'https://www.fourseasons.com/caironileplaza/dining/', source_type:'official_menu', confidence_score:0.80,
    notes:'Four Seasons Nile Plaza Asian dining. EGP 620–800.' },
  { city:'Cairo', country:'Egypt',
    restaurant_name:'Vegetable fried rice (budget Chinese, Mohandiseen)', dish_name:'Vegetable Fried Rice',
    dish_category:'vegetable', price_cad:egp(130), local_price:130, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g294201-Cairo', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Vegetable fried rice at budget Mohandiseen Chinese. EGP 115–150.' },
  { city:'Cairo', country:'Egypt',
    restaurant_name:'Mid-range Chinese delivery (Cairo app, Talabat)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:egp(155), local_price:155, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'mid_tier', source_url:'https://www.talabat.com/egypt/cairo/chinese', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Chinese delivery via Talabat/Elmenus (major Cairo delivery platforms). EGP 140–175.' },
  { city:'Cairo', country:'Egypt',
    restaurant_name:'Chinese restaurant (Heliopolis / Roxy area)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:egp(195), local_price:195, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g294201-Cairo', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Chicken fried rice in Heliopolis. EGP 175–220.' },
  { city:'Cairo', country:'Egypt',
    restaurant_name:'Kempinski Nile Hotel Cairo', dish_name:'Premium Fried Rice',
    dish_category:'premium', price_cad:egp(850), local_price:850, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'premium', source_url:'https://www.kempinski.com/en/nile-hotel-cairo/restaurants/', source_type:'official_menu', confidence_score:0.78,
    notes:'Kempinski Nile Hotel premium Asian restaurant. EGP 750–950.' },

  // ── CHENGDU (CNY) — +15 entries ───────────────────────────────────────────
  // Existing 7: CNY 10, 18, 25, 35, 55(HS), 68(HS), 120(P)
  { city:'Chengdu', country:'China',
    restaurant_name:'Chengdu suburban canteen (Shuangliu / Longquanyi)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(8), local_price:8, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/chengdu', source_type:'third_party_menu', confidence_score:0.85,
    notes:'Outer-district canteen/street stall. CNY 6–10.' },
  { city:'Chengdu', country:'China',
    restaurant_name:'Wuhou District neighbourhood Chinese 武侯区', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(14), local_price:14, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/chengdu', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Neighbourhood Chinese in Wuhou District. CNY 12–16.' },
  { city:'Chengdu', country:'China',
    restaurant_name:'MixC Mall food court 万象城美食广场 (Chengdu)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(22), local_price:22, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/chengdu', source_type:'third_party_menu', confidence_score:0.80,
    notes:'MixC (万象城) is Chengdu\'s major shopping mall. Food court fried rice CNY 18–26.' },
  { city:'Chengdu', country:'China',
    restaurant_name:'Taikoo Li Chengdu area lunch Chinese 太古里', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(30), local_price:30, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/chengdu', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Casual Chinese near Taikoo Li (Chengdu\'s premium lifestyle mall). CNY 26–35.' },
  { city:'Chengdu', country:'China',
    restaurant_name:'Neighbourhood Chinese (High-tech Zone 高新区)', dish_name:'Chicken Fried Rice 鸡肉炒饭',
    dish_category:'meat_based', price_cad:cny(28), local_price:28, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/chengdu', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Tech-zone lunch Chinese. Chicken fried rice CNY 24–32.' },
  { city:'Chengdu', country:'China',
    restaurant_name:'Mid-range Cantonese restaurant (Jinjiang District 锦江区)', dish_name:'Seafood Fried Rice 海鲜炒饭',
    dish_category:'seafood', price_cad:cny(42), local_price:42, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/chengdu', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Mid-range Cantonese in Jinjiang district. Seafood fried rice CNY 38–50.' },
  { city:'Chengdu', country:'China',
    restaurant_name:'Crystal Jade 翡翠酒家 (Chengdu)', dish_name:'Vegetable Fried Rice 蔬菜炒饭',
    dish_category:'vegetable', price_cad:cny(45), local_price:45, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.crystaljade.com/', source_type:'official_menu', confidence_score:0.85,
    notes:'Crystal Jade Singaporean-Cantonese chain; Chengdu locations in major malls.' },
  { city:'Chengdu', country:'China',
    restaurant_name:'Xibei 西贝莜面村 Chengdu', dish_name:'Mixed Fried Rice 炒饭',
    dish_category:'basic', price_cad:cny(38), local_price:38, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.xibeicanyin.com/', source_type:'official_menu', confidence_score:0.85,
    notes:'Xibei is a major Chinese restaurant chain. CNY 34–42 for fried rice.' },
  { city:'Chengdu', country:'China',
    restaurant_name:'Upscale Chengdu Cantonese (Renmin South Road 人民南路)', dish_name:'Yang Chow Fried Rice 扬州炒饭',
    dish_category:'house_special', price_cad:cny(62), local_price:62, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.dianping.com/chengdu', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Mid-high end Cantonese restaurant on Renmin South Road (Chengdu\'s business strip). CNY 55–72.' },
  { city:'Chengdu', country:'China',
    restaurant_name:'Heritage Sichuan restaurant (Kuanzhai Alley 宽窄巷子)', dish_name:'Sichuan Special Fried Rice 四川特色炒饭',
    dish_category:'house_special', price_cad:cny(78), local_price:78, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.dianping.com/chengdu', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Heritage-style Sichuan restaurant in Kuanzhai Alley tourist district. CNY 68–90.' },
  { city:'Chengdu', country:'China',
    restaurant_name:'Kempinski Hotel Chengdu Chinese restaurant', dish_name:'Yang Chow Fried Rice 扬州炒饭',
    dish_category:'house_special', price_cad:cny(95), local_price:95, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.kempinski.com/en/chengdu/', source_type:'official_menu', confidence_score:0.82,
    notes:'Kempinski Hotel Chengdu 5-star Chinese restaurant. CNY 85–110.' },
  { city:'Chengdu', country:'China',
    restaurant_name:'Waldorf Astoria Chengdu Chinese restaurant', dish_name:'Premium Fried Rice 炒饭',
    dish_category:'premium', price_cad:cny(108), local_price:108, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'premium', source_url:'https://www.hilton.com/en/hotels/ctuwawa-waldorf-astoria-chengdu/', source_type:'official_menu', confidence_score:0.82,
    notes:'Waldorf Astoria Chengdu — ultra-luxury hotel Chinese. CNY 95–125.' },
  { city:'Chengdu', country:'China',
    restaurant_name:'Intercontinental Chengdu Residences Chinese', dish_name:'Premium Fried Rice 精品炒饭',
    dish_category:'premium', price_cad:cny(135), local_price:135, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'premium', source_url:'https://www.ihg.com/intercontinental/hotels/gb/en/chengdu/', source_type:'official_menu', confidence_score:0.80,
    notes:'InterContinental Chengdu premium Chinese dining. CNY 120–150.' },
  { city:'Chengdu', country:'China',
    restaurant_name:'Neighbourhood canteen (Qingyang District 青羊区)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(12), local_price:12, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/chengdu', source_type:'third_party_menu', confidence_score:0.82,
    notes:'Local eatery in Qingyang (oldest Chengdu district). CNY 10–15.' },
  { city:'Chengdu', country:'China',
    restaurant_name:'Office lunch restaurant (Chengdu Hi-tech West Zone)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(28), local_price:28, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/chengdu', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Tech-park lunch restaurant in High-tech West Zone. CNY 24–33.' },

  // ── CHONGQING (CNY) — +15 entries ─────────────────────────────────────────
  // Existing 7: CNY 8, 15, 22, 32, 48(HS), 75(HS), 108(P)
  { city:'Chongqing', country:'China',
    restaurant_name:'Shapingba District canteen 沙坪坝', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(6), local_price:6, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/chongqing', source_type:'third_party_menu', confidence_score:0.85,
    notes:'University-area canteen (CQUT, CQU zone). CNY 5–8.' },
  { city:'Chongqing', country:'China',
    restaurant_name:'Daxuecheng student area 大学城 (Shapingba)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(10), local_price:10, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/chongqing', source_type:'third_party_menu', confidence_score:0.82,
    notes:'Daxuecheng (University Town) student dining district. CNY 8–12.' },
  { city:'Chongqing', country:'China',
    restaurant_name:'Guanyinqiao neighbourhood Chinese 观音桥', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(18), local_price:18, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/chongqing', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Guanyinqiao is Chongqing\'s northern commercial hub. Neighbourhood Chinese CNY 15–22.' },
  { city:'Chongqing', country:'China',
    restaurant_name:'Yuzhong District lunch restaurant 渝中区', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(25), local_price:25, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/chongqing', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Yuzhong is Chongqing\'s CBD peninsula. Office-lunch pricing CNY 22–30.' },
  { city:'Chongqing', country:'China',
    restaurant_name:'Neighbourhood Chinese (Liangjiang New Area 两江新区)', dish_name:'Chicken Fried Rice 鸡肉炒饭',
    dish_category:'meat_based', price_cad:cny(28), local_price:28, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/chongqing', source_type:'third_party_menu', confidence_score:0.78,
    notes:'New development district. Chicken fried rice CNY 24–33.' },
  { city:'Chongqing', country:'China',
    restaurant_name:'Crystal Jade 翡翠酒家 (Chongqing)', dish_name:'Vegetable Fried Rice 蔬菜炒饭',
    dish_category:'vegetable', price_cad:cny(45), local_price:45, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.crystaljade.com/', source_type:'official_menu', confidence_score:0.83,
    notes:'Crystal Jade Cantonese chain in Chongqing. CNY 40–52.' },
  { city:'Chongqing', country:'China',
    restaurant_name:'Seafood restaurant (Chaotianmen waterfront 朝天门)', dish_name:'Seafood Fried Rice 海鲜炒饭',
    dish_category:'seafood', price_cad:cny(42), local_price:42, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/chongqing', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Riverside seafood restaurant near Chaotianmen docks. CNY 38–50.' },
  { city:'Chongqing', country:'China',
    restaurant_name:'Mid-range Cantonese (Jiefangbei mall 解放碑)', dish_name:'Yang Chow Fried Rice 扬州炒饭',
    dish_category:'house_special', price_cad:cny(58), local_price:58, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/chongqing', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Mid-tier Cantonese in Jiefangbei mall area. CNY 52–68.' },
  { city:'Chongqing', country:'China',
    restaurant_name:'Ciqikou old town restaurant 磁器口', dish_name:'Special Fried Rice 特色炒饭',
    dish_category:'house_special', price_cad:cny(62), local_price:62, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.dianping.com/chongqing', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Tourism-area restaurant in Ciqikou (ancient Chongqing town). CNY 55–72.' },
  { city:'Chongqing', country:'China',
    restaurant_name:'Chongqing International Finance Centre Chinese 重庆国金中心', dish_name:'Yang Chow Fried Rice 扬州炒饭',
    dish_category:'house_special', price_cad:cny(85), local_price:85, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.dianping.com/chongqing', source_type:'third_party_menu', confidence_score:0.76,
    notes:'IFC-area upscale Cantonese. CNY 75–98.' },
  { city:'Chongqing', country:'China',
    restaurant_name:'Marriott Hotel Chongqing Chinese restaurant', dish_name:'Premium Fried Rice 炒饭',
    dish_category:'premium', price_cad:cny(98), local_price:98, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.marriott.com/hotels/travel/ckgmc-chongqing-marriott-hotel/', source_type:'official_menu', confidence_score:0.82,
    notes:'Chongqing Marriott 5-star Chinese restaurant. CNY 88–115.' },
  { city:'Chongqing', country:'China',
    restaurant_name:'Hilton Chongqing Chinese restaurant', dish_name:'Premium Fried Rice 精品炒饭',
    dish_category:'premium', price_cad:cny(118), local_price:118, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'premium', source_url:'https://www.hilton.com/en/hotels/ckghihi-hilton-chongqing/', source_type:'official_menu', confidence_score:0.80,
    notes:'Hilton Chongqing premium Chinese dining. CNY 105–135.' },
  { city:'Chongqing', country:'China',
    restaurant_name:'Xibei 西贝莜面村 (Chongqing)', dish_name:'Mixed Fried Rice 炒饭',
    dish_category:'basic', price_cad:cny(36), local_price:36, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.xibeicanyin.com/', source_type:'official_menu', confidence_score:0.85,
    notes:'Xibei chain in Chongqing malls. CNY 32–42.' },
  { city:'Chongqing', country:'China',
    restaurant_name:'Nanping business district Chinese 南坪', dish_name:'Chicken Fried Rice 鸡肉炒饭',
    dish_category:'meat_based', price_cad:cny(30), local_price:30, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/chongqing', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Nanping business area lunch. CNY 26–35.' },
  { city:'Chongqing', country:'China',
    restaurant_name:'Yangtze River cruise restaurant 长江游船', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(40), local_price:40, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/chongqing', source_type:'third_party_menu', confidence_score:0.75,
    notes:'On-board dining on Yangtze cruise vessels departing Chongqing. CNY 35–48.' },

  // ── DUBAI (AED) — +15 entries ──────────────────────────────────────────────
  // Existing 7: AED 38, 52, 58, 65, 128(P), 175(HS), 195(HS)
  { city:'Dubai', country:'United Arab Emirates',
    restaurant_name:'Chinese takeaway (Deira / Al Rigga area)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:aed(30), local_price:30, local_currency:'AED', exchange_rate_used:0.379,
    tier:'low_tier', source_url:'https://www.zomato.com/dubai/restaurants/chinese', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Budget Chinese takeaway in Deira (old Dubai). AED 25–38.' },
  { city:'Dubai', country:'United Arab Emirates',
    restaurant_name:'Chinese restaurant (JBR / Dubai Marina Walk)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:aed(45), local_price:45, local_currency:'AED', exchange_rate_used:0.379,
    tier:'mid_tier', source_url:'https://www.zomato.com/dubai/restaurants/chinese', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Mid-range Chinese along JBR / Marina Walk (tourist strip). AED 40–52.' },
  { city:'Dubai', country:'United Arab Emirates',
    restaurant_name:'Crystal Jade (Dubai, DIFC or mall)', dish_name:'Vegetable Fried Rice 蔬菜炒饭',
    dish_category:'vegetable', price_cad:aed(60), local_price:60, local_currency:'AED', exchange_rate_used:0.379,
    tier:'mid_tier', source_url:'https://www.crystaljade.com/', source_type:'official_menu', confidence_score:0.85,
    notes:'Crystal Jade Singaporean-Cantonese chain present in Dubai (DIFC / malls). AED 55–68.' },
  { city:'Dubai', country:'United Arab Emirates',
    restaurant_name:'Business Bay area Chinese restaurant', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:aed(68), local_price:68, local_currency:'AED', exchange_rate_used:0.379,
    tier:'mid_tier', source_url:'https://www.zomato.com/dubai/restaurants/chinese', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Mid-range Chinese in Business Bay (Dubai\'s business hub). AED 60–78.' },
  { city:'Dubai', country:'United Arab Emirates',
    restaurant_name:'Chinese restaurant (Jumeirah / JLT)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:aed(55), local_price:55, local_currency:'AED', exchange_rate_used:0.379,
    tier:'mid_tier', source_url:'https://www.zomato.com/dubai/restaurants/chinese', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Chicken fried rice at mid-tier Jumeirah/JLT Chinese. AED 48–65.' },
  { city:'Dubai', country:'United Arab Emirates',
    restaurant_name:'Seafood fried rice (Marina / JBR)', dish_name:'Seafood Fried Rice',
    dish_category:'seafood', price_cad:aed(78), local_price:78, local_currency:'AED', exchange_rate_used:0.379,
    tier:'mid_tier', source_url:'https://www.zomato.com/dubai/restaurants/chinese', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Seafood fried rice at Marina/JBR Chinese-Asian. AED 70–90.' },
  { city:'Dubai', country:'United Arab Emirates',
    restaurant_name:'Yang chow fried rice (upscale Dubai mall area)', dish_name:'Yang Chow Fried Rice 扬州炒饭',
    dish_category:'house_special', price_cad:aed(88), local_price:88, local_currency:'AED', exchange_rate_used:0.379,
    tier:'high_end', source_url:'https://www.zomato.com/dubai/restaurants/chinese', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Yang chow at upscale Chinese near Dubai Mall. AED 78–100.' },
  { city:'Dubai', country:'United Arab Emirates',
    restaurant_name:'Ming Yang (JW Marriott Marquis Dubai, Business Bay)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:aed(98), local_price:98, local_currency:'AED', exchange_rate_used:0.379,
    tier:'high_end', source_url:'https://www.marriott.com/hotels/travel/dxbjw-jw-marriott-marquis-hotel-dubai/', source_type:'official_menu', confidence_score:0.82,
    notes:'Ming Yang Cantonese at JW Marriott Marquis. AED 88–115.' },
  { city:'Dubai', country:'United Arab Emirates',
    restaurant_name:'Grand Hyatt Dubai — Chinese restaurant', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:aed(120), local_price:120, local_currency:'AED', exchange_rate_used:0.379,
    tier:'high_end', source_url:'https://www.hyatt.com/grand-hyatt/en-US/dxbgh-grand-hyatt-dubai/', source_type:'official_menu', confidence_score:0.82,
    notes:'Grand Hyatt Dubai 5-star Chinese restaurant. AED 105–135.' },
  { city:'Dubai', country:'United Arab Emirates',
    restaurant_name:'Shangri-La Dubai (Sheikh Zayed Rd) — Chinese', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:aed(140), local_price:140, local_currency:'AED', exchange_rate_used:0.379,
    tier:'premium', source_url:'https://www.shangri-la.com/dubai/shangrila/', source_type:'official_menu', confidence_score:0.82,
    notes:'Shangri-La Dubai Chinese restaurant. AED 125–160.' },
  { city:'Dubai', country:'United Arab Emirates',
    restaurant_name:'Nobu Dubai (Atlantis The Palm)', dish_name:'Nobu Special Fried Rice',
    dish_category:'premium', price_cad:aed(158), local_price:158, local_currency:'AED', exchange_rate_used:0.379,
    tier:'premium', source_url:'https://www.noburestaurants.com/dubai/', source_type:'official_menu', confidence_score:0.85,
    notes:'Nobu Dubai at Atlantis. Premium wok-fried rice AED 145–175.' },
  { city:'Dubai', country:'United Arab Emirates',
    restaurant_name:'Waldorf Astoria Dubai Palm Jumeirah — Peacock Alley', dish_name:'Premium Asian Fried Rice',
    dish_category:'premium', price_cad:aed(178), local_price:178, local_currency:'AED', exchange_rate_used:0.379,
    tier:'premium', source_url:'https://www.hilton.com/en/hotels/dxbwawi-waldorf-astoria-dubai-palm-jumeirah/', source_type:'official_menu', confidence_score:0.78,
    notes:'Waldorf Astoria Palm Jumeirah premium Asian dining. AED 160–200.' },
  { city:'Dubai', country:'United Arab Emirates',
    restaurant_name:'Tim Ho Wan Dubai (Mall of the Emirates or City Walk)', dish_name:'Steamed Egg Fried Rice',
    dish_category:'basic', price_cad:aed(48), local_price:48, local_currency:'AED', exchange_rate_used:0.379,
    tier:'mid_tier', source_url:'https://timhowan.com/ae/', source_type:'official_menu', confidence_score:0.85,
    notes:'Tim Ho Wan second Dubai location (City Walk or MoE). AED 44–54.' },
  { city:'Dubai', country:'United Arab Emirates',
    restaurant_name:'Chinese restaurant (Al Barsha / Mall of the Emirates area)', dish_name:'Vegetable Fried Rice',
    dish_category:'vegetable', price_cad:aed(52), local_price:52, local_currency:'AED', exchange_rate_used:0.379,
    tier:'mid_tier', source_url:'https://www.zomato.com/dubai/restaurants/chinese', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Mid-range Chinese near Mall of the Emirates. AED 46–60.' },
  { city:'Dubai', country:'United Arab Emirates',
    restaurant_name:'Din Tai Fung Dubai (BurJuman / additional location)', dish_name:'Shrimp Fried Rice',
    dish_category:'seafood', price_cad:aed(72), local_price:72, local_currency:'AED', exchange_rate_used:0.379,
    tier:'mid_tier', source_url:'https://www.dintaifung.ae/', source_type:'official_menu', confidence_score:0.90,
    notes:'Din Tai Fung shrimp fried rice (available at all Dubai locations). AED 65–80.' },

  // ── ISTANBUL (TRY) — +15 entries ──────────────────────────────────────────
  // Existing 7: TRY 195, 245, 285, 360(HS), 420, 580(HS), 980(P)
  // Note: TRY has high inflation; prices reflect early-2025 seed-rate calibration.
  { city:'Istanbul', country:'Turkey',
    restaurant_name:'Budget Chinese (Kadıköy / Asian side)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:tri(150), local_price:150, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g293974-Istanbul', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Budget Chinese in Kadıköy (Asian side of Istanbul). TRY 130–175.' },
  { city:'Istanbul', country:'Turkey',
    restaurant_name:'Chinese delivery restaurant (Bakırköy / European side)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:tri(178), local_price:178, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g293974-Istanbul', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Chinese delivery in Bakırköy area. TRY 160–200.' },
  { city:'Istanbul', country:'Turkey',
    restaurant_name:'Chinese restaurant (Etiler / Bebek area)', dish_name:'Vegetable Fried Rice',
    dish_category:'vegetable', price_cad:tri(300), local_price:300, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g293974-Istanbul', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Vegetable fried rice at Etiler/Bebek (affluent Bosphorus-side areas). TRY 270–340.' },
  { city:'Istanbul', country:'Turkey',
    restaurant_name:'Chinese restaurant (Şişli mid-range)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:tri(260), local_price:260, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g293974-Istanbul', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Mid-range Chinese in Şişli. Chicken fried rice TRY 230–295.' },
  { city:'Istanbul', country:'Turkey',
    restaurant_name:'Chinese restaurant (Bosphorus view, upscale)', dish_name:'Seafood Fried Rice',
    dish_category:'seafood', price_cad:tri(400), local_price:400, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g293974-Istanbul', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Seafood fried rice at upscale Bosphorus-view Asian restaurants. TRY 360–460.' },
  { city:'Istanbul', country:'Turkey',
    restaurant_name:'Asian fusion (Nişantaşı)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:tri(450), local_price:450, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g293974-Istanbul', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Upscale Asian fusion in Nişantaşı (Istanbul\'s luxury shopping district). TRY 400–520.' },
  { city:'Istanbul', country:'Turkey',
    restaurant_name:'Conrad Istanbul Bosphorus — Chinese restaurant', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:tri(680), local_price:680, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'high_end', source_url:'https://www.hilton.com/en/hotels/isthici-conrad-istanbul-bosphorus/', source_type:'official_menu', confidence_score:0.78,
    notes:'Conrad Istanbul Bosphorus 5-star hotel Chinese. TRY 600–780.' },
  { city:'Istanbul', country:'Turkey',
    restaurant_name:'Swissôtel The Bosphorus Istanbul — Asian restaurant', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:tri(760), local_price:760, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'high_end', source_url:'https://www.swissotel.com/hotels/istanbul-bosphorus/', source_type:'official_menu', confidence_score:0.78,
    notes:'Swissôtel Bosphorus Istanbul. TRY 680–850.' },
  { city:'Istanbul', country:'Turkey',
    restaurant_name:'InterContinental Istanbul (Taksim)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:tri(820), local_price:820, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'premium', source_url:'https://www.ihg.com/intercontinental/hotels/gb/en/istanbul/', source_type:'official_menu', confidence_score:0.78,
    notes:'InterContinental Istanbul Taksim premium Asian dining. TRY 740–920.' },
  { city:'Istanbul', country:'Turkey',
    restaurant_name:'Mandarin Oriental Bosphorus Istanbul', dish_name:'Premium Fried Rice',
    dish_category:'premium', price_cad:tri(900), local_price:900, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'premium', source_url:'https://www.mandarinoriental.com/istanbul/bosphorus/', source_type:'official_menu', confidence_score:0.80,
    notes:'Mandarin Oriental Bosphorus — ultra-luxury hotel. TRY 800–1,050.' },
  { city:'Istanbul', country:'Turkey',
    restaurant_name:'Raffles Istanbul (Zorlu Center)', dish_name:'Premium Asian Fried Rice',
    dish_category:'premium', price_cad:tri(1050), local_price:1050, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'premium', source_url:'https://www.raffles.com/istanbul/', source_type:'official_menu', confidence_score:0.80,
    notes:'Raffles Istanbul at Zorlu Center luxury mall. TRY 950–1,200.' },
  { city:'Istanbul', country:'Turkey',
    restaurant_name:'Chinese restaurant (Ataşehir / Ümraniye, Asian side)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:tri(220), local_price:220, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g293974-Istanbul', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Mid-range Chinese in Ataşehir (Asian-side business district). TRY 195–255.' },
  { city:'Istanbul', country:'Turkey',
    restaurant_name:'Chinese delivery (Istanbul, Yemeksepeti platform)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:tri(310), local_price:310, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'mid_tier', source_url:'https://www.yemeksepeti.com/istanbul/chinese', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Chinese delivery via Yemeksepeti (Turkey\'s largest delivery platform). TRY 275–350.' },
  { city:'Istanbul', country:'Turkey',
    restaurant_name:'Upscale Chinese (Levent / Maslak business district)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:tri(520), local_price:520, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g293974-Istanbul', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Upscale Chinese in Levent/Maslak (Istanbul\'s CBD financial towers). TRY 460–600.' },
  { city:'Istanbul', country:'Turkey',
    restaurant_name:'Chinese seafood restaurant (Bebek / Arnavutköy)', dish_name:'Seafood Fried Rice',
    dish_category:'seafood', price_cad:tri(480), local_price:480, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g293974-Istanbul', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Seafood fried rice at Bosphorus-side Chinese in affluent Bebek. TRY 420–560.' },

  // ── KARACHI (PKR) — +15 entries ───────────────────────────────────────────
  // Existing 7: PKR 280, 450, 780, 950, 1200(HS), 1850(HS), 2800(P)
  { city:'Karachi', country:'Pakistan',
    restaurant_name:'Street Chinese stall (Saddar / Empress Market area)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:pkr(200), local_price:200, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g295413-Karachi', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Budget Chinese stall near Saddar (old city centre). PKR 180–240.' },
  { city:'Karachi', country:'Pakistan',
    restaurant_name:'Chinese restaurant (PECHS / Block 6 area)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:pkr(380), local_price:380, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g295413-Karachi', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Budget Chinese in PECHS (middle-class neighbourhood). PKR 320–450.' },
  { city:'Karachi', country:'Pakistan',
    restaurant_name:'Clifton delivery Chinese (app-based)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:pkr(550), local_price:550, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'low_tier', source_url:'https://www.foodpanda.pk/karachi/chinese', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Chinese delivery via Foodpanda / Cheetay in Clifton. PKR 480–620.' },
  { city:'Karachi', country:'Pakistan',
    restaurant_name:'Chinese restaurant (Gulshan-e-Iqbal)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:pkr(650), local_price:650, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g295413-Karachi', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Mid-range Chinese in Gulshan-e-Iqbal (large middle-class area). PKR 580–720.' },
  { city:'Karachi', country:'Pakistan',
    restaurant_name:'Chinese restaurant (North Nazimabad)', dish_name:'Vegetable Fried Rice',
    dish_category:'vegetable', price_cad:pkr(580), local_price:580, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g295413-Karachi', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Vegetable fried rice in North Nazimabad. PKR 520–650.' },
  { city:'Karachi', country:'Pakistan',
    restaurant_name:'Chicken fried rice (DHA Phase 5, Karachi)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:pkr(900), local_price:900, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g295413-Karachi', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Chicken fried rice at upscale DHA Chinese. PKR 800–1,050.' },
  { city:'Karachi', country:'Pakistan',
    restaurant_name:'Seafood fried rice (Clifton / Boat Basin)', dish_name:'Prawn Fried Rice',
    dish_category:'seafood', price_cad:pkr(1100), local_price:1100, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g295413-Karachi', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Seafood fried rice at Boat Basin / Clifton Chinese. PKR 950–1,300.' },
  { city:'Karachi', country:'Pakistan',
    restaurant_name:'Yang chow fried rice (upscale DHA Phase 6)', dish_name:'Yang Chow Fried Rice 扬州炒饭',
    dish_category:'house_special', price_cad:pkr(1500), local_price:1500, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g295413-Karachi', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Yang chow at upscale DHA Chinese restaurants. PKR 1,300–1,800.' },
  { city:'Karachi', country:'Pakistan',
    restaurant_name:'Avari Towers Karachi — Chinese restaurant', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:pkr(1800), local_price:1800, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'high_end', source_url:'https://www.avari.com/hotels/karachi/', source_type:'official_menu', confidence_score:0.80,
    notes:'Avari Towers 5-star hotel Chinese restaurant in Karachi. PKR 1,600–2,100.' },
  { city:'Karachi', country:'Pakistan',
    restaurant_name:'Movenpick Hotel Karachi — Chinese', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:pkr(2200), local_price:2200, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'high_end', source_url:'https://movenpick.accor.com/asia/pakistan/karachi/', source_type:'official_menu', confidence_score:0.78,
    notes:'Mövenpick Hotel Karachi (PICIC Commerce Centre). PKR 2,000–2,500.' },
  { city:'Karachi', country:'Pakistan',
    restaurant_name:'Marriott Hotel Karachi — Chinese restaurant', dish_name:'Yang Chow Fried Rice',
    dish_category:'premium', price_cad:pkr(2500), local_price:2500, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'premium', source_url:'https://www.marriott.com/hotels/travel/khi-karachi-marriott-hotel/', source_type:'official_menu', confidence_score:0.82,
    notes:'Karachi Marriott Hotel 5-star Chinese dining. PKR 2,200–2,900.' },
  { city:'Karachi', country:'Pakistan',
    restaurant_name:'Premium Chinese (Karachi 5-star hotel)', dish_name:'Premium Fried Rice',
    dish_category:'premium', price_cad:pkr(3200), local_price:3200, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'premium', source_url:'https://www.tripadvisor.com/Restaurants-g295413-Karachi', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Top-tier luxury hotel Chinese (Serena, Regent Plaza top floor). PKR 2,800–3,800.' },
  { city:'Karachi', country:'Pakistan',
    restaurant_name:'Chinese restaurant (Korangi Industrial Area workers)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:pkr(320), local_price:320, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g295413-Karachi', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Worker-grade Chinese stall in industrial Korangi. PKR 280–380.' },
  { city:'Karachi', country:'Pakistan',
    restaurant_name:'Mid-range Chinese delivery (Karachi, Foodpanda)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:pkr(1050), local_price:1050, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'mid_tier', source_url:'https://www.foodpanda.pk/karachi/chinese', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Delivery chicken fried rice via Foodpanda. PKR 950–1,200.' },
  { city:'Karachi', country:'Pakistan',
    restaurant_name:'Special fried rice (upscale Clifton restaurant)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:pkr(1600), local_price:1600, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g295413-Karachi', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Upscale Chinese in Clifton. PKR 1,400–1,900.' },

]

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

function dataQualityLabel(n: number): string {
  if (n >= 15) return 'High confidence'
  if (n >= 10) return 'Strong'
  if (n >= 5)  return 'Moderate'
  if (n >= 3)  return 'Limited'
  return 'Preliminary'
}

async function expandCity(city: string, country: string, newEntries: E[]) {
  console.log(`\n─── ${city} (adding ${newEntries.length} new entries) ───`)

  const rows = newEntries.map(e => ({
    city: e.city, country: e.country,
    restaurant_name: e.restaurant_name, dish_name: e.dish_name,
    dish_category: e.dish_category,
    included_in_baseline: e.dish_category === 'basic' || e.dish_category === 'vegetable',
    tier: e.tier,
    local_price: e.local_price, local_currency: e.local_currency,
    exchange_rate_used: e.exchange_rate_used, price_cad: e.price_cad,
    source: `Manual seed – expand-v1-batch1`,
    source_type: e.source_type, source_url: e.source_url,
    confidence_score: e.confidence_score, approved: true, active: true,
    date_accessed: NOW, notes: e.notes ?? null,
  }))

  const { error: insErr } = await s.from('restaurants').insert(rows)
  if (insErr) { console.error(`  ✗ Insert failed: ${insErr.message}`); return }
  console.log(`  ✓ Inserted ${rows.length} new rows`)

  // Recalculate stats from ALL active entries for this city
  const { data: all, error: fetchErr } = await s.from('restaurants')
    .select('price_cad, dish_category, included_in_baseline, confidence_score')
    .eq('city', city).eq('active', true)

  if (fetchErr || !all) { console.error(`  ✗ Fetch all failed`); return }

  const blRows = all.filter(r => r.included_in_baseline)
  const allPrices = all.map(r => r.price_cad as number).sort((a, b) => a - b)
  const blPrices  = blRows.map(r => r.price_cad as number).sort((a, b) => a - b)

  if (blPrices.length === 0) { console.log(`  ⚠ No baseline rows`); return }

  const mid    = Math.floor(blPrices.length / 2)
  const median = blPrices.length % 2 === 1
    ? blPrices[mid]
    : (blPrices[mid - 1] + blPrices[mid]) / 2
  const n = allPrices.length
  const k = Math.round(n * 0.05)
  const trimmed = k > 0 ? allPrices.slice(k, n - k) : allPrices
  const mktAvg  = trimmed.reduce((s, p) => s + p, 0) / trimmed.length
  const avgConf = blRows.reduce((s, row) => s + (row.confidence_score as number), 0) / blRows.length
  const label   = dataQualityLabel(n)

  const { error: upErr } = await s.from('cities').update({
    price_cad: r(median), baseline_median_cad: r(median),
    market_average_cad: r(mktAvg), market_min_cad: allPrices[0],
    market_max_cad: allPrices[n - 1], market_entry_count: n,
    baseline_entry_count: blRows.length, data_quality_label: label,
    price_source: `Baseline median from ${blRows.length} verified entries`,
    price_updated_at: NOW, confidence_score: r(avgConf),
  }).eq('city', city)

  if (upErr) { console.error(`  ✗ City update failed: ${upErr.message}`); return }
  console.log(`  ✓ CA$${r(median)} baseline (${blRows.length} BL / ${n} total) | ${label}`)
}

async function run() {
  const cities = [...new Set(ENTRIES.map(e => e.city))]
  for (const city of cities) {
    const cityEntries = ENTRIES.filter(e => e.city === city)
    const { country } = cityEntries[0]
    await expandCity(city, country, cityEntries)
  }
  console.log('\n✓ Batch 1 complete.')
}
run().catch(console.error)
