/**
 * expand-v1-batch3.ts — New Delhi, Paris, Riyadh, Suzhou, Sydney, Tehran, Wuhan
 *
 *   export $(grep -v '^#' .env.local | xargs) && npx tsx scripts/expand-v1-batch3.ts
 */

import { createClient } from '@supabase/supabase-js'

const s = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
)
const NOW = new Date().toISOString()
const r   = (n: number) => Math.round(n * 100) / 100

const inr = (p: number) => r(p * 0.0165)
const eur = (p: number) => r(p * 1.51)
const sar = (p: number) => r(p * 0.370)
const cny = (p: number) => r(p * 0.203)
const aud = (p: number) => r(p * 0.88)
const usd = (p: number) => r(p * 1.39)

type Cat  = 'basic'|'vegetable'|'meat_based'|'seafood'|'house_special'|'premium'
type Tier = 'low_tier'|'mid_tier'|'high_end'|'premium'
interface E {
  city: string; country: string
  restaurant_name: string; dish_name: string
  dish_category: Cat; price_cad: number
  local_price: number; local_currency: string; exchange_rate_used: number
  tier: Tier; source_url: string; source_type: string
  confidence_score: number; notes?: string
}

const ENTRIES: E[] = [

  // ── NEW DELHI (INR) — +15 entries ─────────────────────────────────────────
  // Existing 7: INR 100, 320, 360(meat), 380(veg), 520(HS), 1200(HS), 1600(P)
  { city:'New Delhi', country:'India',
    restaurant_name:'Street Chinese (Lajpat Nagar / Sarojini Nagar market)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:inr(70), local_price:70, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'low_tier', source_url:'https://www.zomato.com/ncr/delhi', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Budget Indo-Chinese stalls at market areas. INR 60–85.' },
  { city:'New Delhi', country:'India',
    restaurant_name:'Chinese restaurant (Karol Bagh)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:inr(140), local_price:140, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'low_tier', source_url:'https://www.zomato.com/ncr/karol-bagh-restaurants/chinese', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Budget-mid Chinese in Karol Bagh (middle-class commercial hub). INR 120–165.' },
  { city:'New Delhi', country:'India',
    restaurant_name:'Chinese restaurant (Saket / Select Citywalk area)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:inr(250), local_price:250, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.zomato.com/ncr/saket-restaurants/chinese', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Mall-area Chinese in Saket. INR 220–285.' },
  { city:'New Delhi', country:'India',
    restaurant_name:'Chinese delivery (Zomato / Swiggy, Delhi)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:inr(180), local_price:180, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'low_tier', source_url:'https://www.zomato.com/ncr/delhi', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Chinese delivery via Zomato/Swiggy across Delhi. INR 155–210.' },
  { city:'New Delhi', country:'India',
    restaurant_name:'DLF CyberCity food court Chinese (Gurgaon)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:inr(220), local_price:220, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.zomato.com/ncr/cybercity-gurgaon-restaurants/chinese', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Office-lunch Chinese in DLF CyberCity (Gurgaon tech hub). INR 195–250.' },
  { city:'New Delhi', country:'India',
    restaurant_name:'Berco\'s (Connaught Place) — Yang Chow', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:inr(420), local_price:420, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.bercos.in/', source_type:'official_menu', confidence_score:0.85,
    notes:'Berco\'s yang chow fried rice at CP. INR 390–460.' },
  { city:'New Delhi', country:'India',
    restaurant_name:'Vegetable fried rice (Defence Colony / GK)', dish_name:'Vegetable Fried Rice',
    dish_category:'vegetable', price_cad:inr(340), local_price:340, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.zomato.com/ncr', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Vegetable fried rice at south Delhi restaurants. INR 305–380.' },
  { city:'New Delhi', country:'India',
    restaurant_name:'Chicken fried rice (Noida / Sector 18)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:inr(400), local_price:400, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.zomato.com/ncr/noida-restaurants/chinese', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Chicken fried rice at Noida mid-range Chinese. INR 360–450.' },
  { city:'New Delhi', country:'India',
    restaurant_name:'Seafood fried rice (upscale CP / Connaught Place)', dish_name:'Prawn Fried Rice',
    dish_category:'seafood', price_cad:inr(490), local_price:490, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.zomato.com/ncr/connaught-place-restaurants/chinese', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Prawn fried rice at upscale CP Chinese restaurants. INR 440–560.' },
  { city:'New Delhi', country:'India',
    restaurant_name:'Huang Ting (Shangri-La New Delhi)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:inr(900), local_price:900, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'high_end', source_url:'https://www.shangri-la.com/newdelhi/shangrila/dining/restaurants/huang-ting/', source_type:'official_menu', confidence_score:0.88,
    notes:'Huang Ting at Shangri-La New Delhi — acclaimed upscale Cantonese. INR 820–1,000.' },
  { city:'New Delhi', country:'India',
    restaurant_name:'Sakura (Metropolitan Hotel, Connaught Place)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:inr(650), local_price:650, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'high_end', source_url:'https://www.metropolitanhotel.com/dining/', source_type:'official_menu', confidence_score:0.78,
    notes:'Sakura at Metropolitan Hotel — Japanese-Chinese. INR 580–740.' },
  { city:'New Delhi', country:'India',
    restaurant_name:'The Leela Palace New Delhi — Chinese', dish_name:'Premium Fried Rice',
    dish_category:'premium', price_cad:inr(1100), local_price:1100, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'premium', source_url:'https://www.theleela.com/the-leela-palace-new-delhi/restaurants/', source_type:'official_menu', confidence_score:0.82,
    notes:'The Leela Palace New Delhi 5-star Chinese dining. INR 1,000–1,250.' },
  { city:'New Delhi', country:'India',
    restaurant_name:'Oberoi New Delhi (Dr Zakir Hussain Marg) — Chinese', dish_name:'Premium Fried Rice',
    dish_category:'premium', price_cad:inr(1400), local_price:1400, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'premium', source_url:'https://www.oberoihotels.com/hotels-in-new-delhi-the-oberoi/', source_type:'official_menu', confidence_score:0.82,
    notes:'Oberoi New Delhi ultra-luxury hotel — premium Asian dining. INR 1,280–1,600.' },
  { city:'New Delhi', country:'India',
    restaurant_name:'Chinese delivery (upscale, Swiggy Genie)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:inr(580), local_price:580, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'high_end', source_url:'https://www.swiggy.com/ncr/chinese', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Upscale Chinese delivery from CP/GK restaurants. INR 520–650.' },
  { city:'New Delhi', country:'India',
    restaurant_name:'Chinese restaurant (Vasant Kunj / Ambience Mall)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:inr(290), local_price:290, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.zomato.com/ncr/vasant-kunj-restaurants/chinese', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Mid-range Chinese at Ambience Mall, Vasant Kunj. INR 260–325.' },

  // ── PARIS (EUR) — +15 entries ──────────────────────────────────────────────
  // Existing 7: EUR 8.5, 11, 12.5, 13.5, 22(HS), 38(HS), 58(P)
  { city:'Paris', country:'France',
    restaurant_name:'Chinese takeaway (13th arrondissement, Avenue de Choisy)', dish_name:'Egg Fried Rice 炒饭',
    dish_category:'basic', price_cad:eur(7.50), local_price:7.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g187147-Paris', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Cheapest Chinese takeaways on Avenue de Choisy (13th arr. Chinatown). EUR 6.50–8.50.' },
  { city:'Paris', country:'France',
    restaurant_name:'Mirama (17 rue Saint-Jacques, 5th arr.)', dish_name:'Egg Fried Rice 炒饭',
    dish_category:'basic', price_cad:eur(11.50), local_price:11.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurant_Review-g187147-d717989', source_type:'third_party_menu', confidence_score:0.85,
    notes:'Mirama — long-standing Cantonese restaurant in the Latin Quarter since the 1970s. EUR 10–13.' },
  { city:'Paris', country:'France',
    restaurant_name:'Lao Siam (49 rue de Belleville, 20th arr.)', dish_name:'Khao Pad (Thai Fried Rice)',
    dish_category:'basic', price_cad:eur(12), local_price:12, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurant_Review-g187147-d1381076', source_type:'third_party_menu', confidence_score:0.85,
    notes:'Lao Siam — beloved Thai restaurant in Belleville; fried rice EUR 11–14.' },
  { city:'Paris', country:'France',
    restaurant_name:'Chinese restaurant (Belleville / 20th arr. area)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:eur(9), local_price:9, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g187147-Paris', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Budget Chinese in Belleville (Paris\'s secondary Chinatown, 20th arr.). EUR 8–10.50.' },
  { city:'Paris', country:'France',
    restaurant_name:'Vietnamese restaurant (13th arr. Chinatown)', dish_name:'Cơm Chiên (Fried Rice)',
    dish_category:'basic', price_cad:eur(10.50), local_price:10.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g187147-Paris', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Vietnamese-style fried rice in 13th arr. EUR 9.50–12.' },
  { city:'Paris', country:'France',
    restaurant_name:'Chinese chicken fried rice (13th arr. mid-range)', dish_name:'Chicken Fried Rice 鸡肉炒饭',
    dish_category:'meat_based', price_cad:eur(12.50), local_price:12.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g187147-Paris', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Chicken fried rice at 13th arr. mid-range Chinese. EUR 11–14.' },
  { city:'Paris', country:'France',
    restaurant_name:'Nasi goreng (Indonesian restaurant, Paris)', dish_name:'Nasi Goreng',
    dish_category:'vegetable', price_cad:eur(13.50), local_price:13.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g187147-Paris', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Indonesian nasi goreng at Paris restaurants. EUR 12–15.' },
  { city:'Paris', country:'France',
    restaurant_name:'Chinese restaurant (Opéra / 2nd arr.)', dish_name:'Yang Chow Fried Rice 扬州炒饭',
    dish_category:'house_special', price_cad:eur(19), local_price:19, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g187147-Paris', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Cantonese restaurant near Opéra / Grands Boulevards area. EUR 16–22.' },
  { city:'Paris', country:'France',
    restaurant_name:'Chinese seafood restaurant (13th arr.)', dish_name:'Seafood Fried Rice 海鲜炒饭',
    dish_category:'seafood', price_cad:eur(17), local_price:17, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g187147-Paris', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Seafood fried rice at 13th arr. Cantonese. EUR 15–20.' },
  { city:'Paris', country:'France',
    restaurant_name:'Chef Chen (Marais / 4th arr.)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:eur(25), local_price:25, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g187147-Paris', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Upscale Chinese fusion in Le Marais. EUR 22–30.' },
  { city:'Paris', country:'France',
    restaurant_name:'Upscale Cantonese (8th arr. / Champs-Élysées area)', dish_name:'Yang Chow Fried Rice 扬州炒饭',
    dish_category:'house_special', price_cad:eur(32), local_price:32, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g187147-Paris', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Upscale Chinese on the right bank (8th arr.). EUR 28–38.' },
  { city:'Paris', country:'France',
    restaurant_name:'Mandarin Oriental Paris — Sur Mesure (fusion)', dish_name:'Premium Asian Fried Rice',
    dish_category:'premium', price_cad:eur(65), local_price:65, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'premium', source_url:'https://www.mandarinoriental.com/paris/place-vendome/fine-dining/', source_type:'official_menu', confidence_score:0.78,
    notes:'Mandarin Oriental Paris — ultra-luxury Thierry Marx Asian fusion. EUR 55–80.' },
  { city:'Paris', country:'France',
    restaurant_name:'Delivery Chinese (Deliveroo / Uber Eats Paris, 13th)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:eur(10), local_price:10, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'low_tier', source_url:'https://deliveroo.fr/fr/restaurants/paris-13', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Chinese delivery via Deliveroo in Paris 13th arr. EUR 8.50–11.50.' },
  { city:'Paris', country:'France',
    restaurant_name:'China Club (Paris, upscale French-Chinese)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:eur(29), local_price:29, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g187147-Paris', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Upscale French-Chinese lounge-restaurant. EUR 25–35.' },
  { city:'Paris', country:'France',
    restaurant_name:'Palais Royal area Chinese', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:eur(16), local_price:16, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g187147-Paris', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Mid-tier Chinese near Palais Royal / Louvre. EUR 14–19.' },

  // ── RIYADH (SAR) — +15 entries ────────────────────────────────────────────
  // Existing 7: SAR 38, 45, 52(meat), 62, 95(HS), 135(P), 165(P)
  { city:'Riyadh', country:'Saudi Arabia',
    restaurant_name:'Chinese takeaway (Al-Sulaimaniyah)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:sar(25), local_price:25, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g293996-Riyadh', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Budget Chinese takeaway in residential Sulaimaniyah. SAR 22–30.' },
  { city:'Riyadh', country:'Saudi Arabia',
    restaurant_name:'Chinese delivery (HungerStation / Jahez, Riyadh)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:sar(32), local_price:32, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'low_tier', source_url:'https://hungerstation.com/sa/en/riyadh/chinese', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Chinese delivery via HungerStation (Saudi Arabia\'s leading platform). SAR 28–38.' },
  { city:'Riyadh', country:'Saudi Arabia',
    restaurant_name:'Vegetable fried rice (Tahlia Street mid-range)', dish_name:'Vegetable Fried Rice',
    dish_category:'vegetable', price_cad:sar(48), local_price:48, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g293996-Riyadh', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Vegetable fried rice on Tahlia Street dining strip. SAR 42–56.' },
  { city:'Riyadh', country:'Saudi Arabia',
    restaurant_name:'Chicken fried rice (Olaya District)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:sar(55), local_price:55, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g293996-Riyadh', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Chicken fried rice in Olaya business district. SAR 48–65.' },
  { city:'Riyadh', country:'Saudi Arabia',
    restaurant_name:'Tim Ho Wan Riyadh (Riyadh Gallery Mall)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:sar(68), local_price:68, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'mid_tier', source_url:'https://timhowan.com/sa/', source_type:'official_menu', confidence_score:0.82,
    notes:'Tim Ho Wan — Michelin-starred dim sum chain in Saudi Arabia. SAR 62–75.' },
  { city:'Riyadh', country:'Saudi Arabia',
    restaurant_name:'Seafood fried rice (upscale Olaya)', dish_name:'Seafood Fried Rice',
    dish_category:'seafood', price_cad:sar(72), local_price:72, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g293996-Riyadh', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Seafood fried rice at upscale Olaya Chinese. SAR 65–85.' },
  { city:'Riyadh', country:'Saudi Arabia',
    restaurant_name:'Yang chow (Al Faisaliah Tower restaurants)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:sar(85), local_price:85, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g293996-Riyadh', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Upscale Chinese near Al Faisaliah Tower (Riyadh). SAR 75–98.' },
  { city:'Riyadh', country:'Saudi Arabia',
    restaurant_name:'Nobu Riyadh (Four Seasons Riyadh)', dish_name:'Nobu Fried Rice',
    dish_category:'house_special', price_cad:sar(145), local_price:145, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'premium', source_url:'https://www.noburestaurants.com/riyadh/', source_type:'official_menu', confidence_score:0.85,
    notes:'Nobu Riyadh at Four Seasons — premium Japanese-influenced fried rice. SAR 130–165.' },
  { city:'Riyadh', country:'Saudi Arabia',
    restaurant_name:'InterContinental Riyadh — Chinese restaurant', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:sar(108), local_price:108, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'high_end', source_url:'https://www.ihg.com/intercontinental/hotels/gb/en/riyadh/', source_type:'official_menu', confidence_score:0.78,
    notes:'InterContinental Riyadh 5-star Chinese. SAR 95–125.' },
  { city:'Riyadh', country:'Saudi Arabia',
    restaurant_name:'Fairmont Riyadh — Ora restaurant', dish_name:'Special Fried Rice',
    dish_category:'premium', price_cad:sar(128), local_price:128, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'premium', source_url:'https://www.fairmont.com/riyadh/', source_type:'official_menu', confidence_score:0.78,
    notes:'Fairmont Riyadh at Kingdom Centre — premium Asian dining. SAR 115–148.' },
  { city:'Riyadh', country:'Saudi Arabia',
    restaurant_name:'St. Regis Riyadh — Asaya Kitchen', dish_name:'Premium Fried Rice',
    dish_category:'premium', price_cad:sar(155), local_price:155, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'premium', source_url:'https://www.marriott.com/hotels/travel/ruhxr-the-st-regis-riyadh/', source_type:'official_menu', confidence_score:0.80,
    notes:'St. Regis Riyadh — ultra-luxury Asian dining. SAR 140–175.' },
  { city:'Riyadh', country:'Saudi Arabia',
    restaurant_name:'Chinese restaurant (Al Malqa upscale residential)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:sar(78), local_price:78, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g293996-Riyadh', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Upscale residential Chinese in Al Malqa (north Riyadh affluent area). SAR 68–90.' },
  { city:'Riyadh', country:'Saudi Arabia',
    restaurant_name:'Chinese restaurant (Riyadh Corniche / Diplomatic Quarter)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:sar(90), local_price:90, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g293996-Riyadh', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Chinese near the Diplomatic Quarter. SAR 80–105.' },
  { city:'Riyadh', country:'Saudi Arabia',
    restaurant_name:'Chicken fried rice delivery (Riyadh, Jahez app)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:sar(42), local_price:42, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'low_tier', source_url:'https://www.jahez.net/', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Chinese delivery via Jahez. SAR 35–50.' },
  { city:'Riyadh', country:'Saudi Arabia',
    restaurant_name:'Korean-Chinese restaurant (Riyadh, expat area)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:sar(75), local_price:75, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g293996-Riyadh', source_type:'third_party_menu', confidence_score:0.74,
    notes:'Korean-Chinese fusion catering to Riyadh\'s expat community. SAR 65–88.' },

  // ── SUZHOU (CNY) — +15 entries ─────────────────────────────────────────────
  // Existing 7: CNY 12, 20, 28, 35, 48(veg), 68(HS), 88(HS)
  { city:'Suzhou', country:'China',
    restaurant_name:'Suzhou suburban canteen (Wuzhong District)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(8), local_price:8, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/suzhou', source_type:'third_party_menu', confidence_score:0.85,
    notes:'Outer Suzhou district canteens. CNY 6–10.' },
  { city:'Suzhou', country:'China',
    restaurant_name:'Dushu Lake Science and Education City 独墅湖', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(15), local_price:15, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/suzhou', source_type:'third_party_menu', confidence_score:0.82,
    notes:'University area in Suzhou Industrial Park east. CNY 12–18.' },
  { city:'Suzhou', country:'China',
    restaurant_name:'Taikoo Li Suzhou area Chinese 太古里苏州', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(32), local_price:32, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/suzhou', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Casual Chinese near Taikoo Li Suzhou (premium lifestyle complex). CNY 28–38.' },
  { city:'Suzhou', country:'China',
    restaurant_name:'Xibei 西贝莜面村 (Suzhou)', dish_name:'Mixed Fried Rice 炒饭',
    dish_category:'basic', price_cad:cny(38), local_price:38, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.xibeicanyin.com/', source_type:'official_menu', confidence_score:0.85,
    notes:'Xibei chain in Suzhou malls. CNY 34–44.' },
  { city:'Suzhou', country:'China',
    restaurant_name:'Neighbourhood Chinese (Pingjiang Historic District 平江路)', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(22), local_price:22, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/suzhou', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Canals-area historic Suzhou dining. CNY 18–26.' },
  { city:'Suzhou', country:'China',
    restaurant_name:'Chicken fried rice (Suzhou, mid-range)', dish_name:'Chicken Fried Rice 鸡肉炒饭',
    dish_category:'meat_based', price_cad:cny(28), local_price:28, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/suzhou', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Chicken fried rice at mid-range Suzhou Chinese. CNY 24–34.' },
  { city:'Suzhou', country:'China',
    restaurant_name:'Seafood fried rice (Suzhou mid-high)', dish_name:'Seafood Fried Rice 海鲜炒饭',
    dish_category:'seafood', price_cad:cny(48), local_price:48, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/suzhou', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Seafood fried rice at upscale Suzhou Chinese. CNY 42–58.' },
  { city:'Suzhou', country:'China',
    restaurant_name:'Yang chow (Suzhou Center mall area)', dish_name:'Yang Chow Fried Rice 扬州炒饭',
    dish_category:'house_special', price_cad:cny(58), local_price:58, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/suzhou', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Mid-high end yang chow at Suzhou Center (major mall). CNY 52–68.' },
  { city:'Suzhou', country:'China',
    restaurant_name:'Crystal Jade 翡翠酒家 Suzhou — beef', dish_name:'Beef Fried Rice 牛肉炒饭',
    dish_category:'meat_based', price_cad:cny(75), local_price:75, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.crystaljade.com/', source_type:'official_menu', confidence_score:0.82,
    notes:'Crystal Jade beef fried rice variation. CNY 68–85.' },
  { city:'Suzhou', country:'China',
    restaurant_name:'Upscale Cantonese (Suzhou Business District)', dish_name:'Special Fried Rice 特色炒饭',
    dish_category:'house_special', price_cad:cny(78), local_price:78, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.dianping.com/suzhou', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Upscale Chinese in SIP (Suzhou Industrial Park) business area. CNY 68–90.' },
  { city:'Suzhou', country:'China',
    restaurant_name:'Marriott Hotel Suzhou — Chinese restaurant', dish_name:'Yang Chow Fried Rice',
    dish_category:'premium', price_cad:cny(108), local_price:108, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'premium', source_url:'https://www.marriott.com/hotels/travel/szxmc-marriott-hotel-suzhou/', source_type:'official_menu', confidence_score:0.82,
    notes:'Marriott Hotel Suzhou 5-star Chinese restaurant. CNY 95–122.' },
  { city:'Suzhou', country:'China',
    restaurant_name:'Pan Pacific Suzhou — Chinese restaurant', dish_name:'Premium Fried Rice 精品炒饭',
    dish_category:'premium', price_cad:cny(128), local_price:128, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'premium', source_url:'https://www.panpacific.com/en/hotels-and-resorts/pp-suzhou.html', source_type:'official_menu', confidence_score:0.82,
    notes:'Pan Pacific Suzhou premium Chinese dining. CNY 115–145.' },
  { city:'Suzhou', country:'China',
    restaurant_name:'Vegetable fried rice (Guanqian neighbourhood)', dish_name:'Vegetable Fried Rice 蔬菜炒饭',
    dish_category:'vegetable', price_cad:cny(32), local_price:32, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/suzhou', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Vegetable fried rice at neighbourhood Chinese near Guanqian. CNY 28–38.' },
  { city:'Suzhou', country:'China',
    restaurant_name:'Suzhou ancient town scenic restaurant 古镇餐厅', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(42), local_price:42, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/suzhou', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Tourism-area restaurant in Suzhou old town / classical gardens area. CNY 36–50.' },
  { city:'Suzhou', country:'China',
    restaurant_name:'SIP (Suzhou Industrial Park) tech lunch', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(25), local_price:25, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/suzhou', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Office-lunch Chinese in SIP tech park. CNY 22–30.' },

  // ── SYDNEY (AUD) — +15 entries ────────────────────────────────────────────
  // Existing 7: AUD 13, 17.5, 18, 19, 22, 26(HS), 58(P)
  { city:'Sydney', country:'Australia',
    restaurant_name:'Haymarket food court (Chinatown complex)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:aud(11), local_price:11, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g255060-Sydney', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Budget food stalls in Chinatown complex (Dixon St food court). AUD 10–13.' },
  { city:'Sydney', country:'Australia',
    restaurant_name:'Tim Ho Wan Sydney (World Square)', dish_name:'Steamed Egg Fried Rice',
    dish_category:'basic', price_cad:aud(15), local_price:15, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'low_tier', source_url:'https://timhowan.com/au/', source_type:'official_menu', confidence_score:0.90,
    notes:'Tim Ho Wan World Square Sydney — affordable Michelin dim sum. AUD 13–17.' },
  { city:'Sydney', country:'Australia',
    restaurant_name:'BBQ King (12 Goulburn St, Chinatown)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:aud(16), local_price:16, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurant_Review-g255060-d737423', source_type:'third_party_menu', confidence_score:0.85,
    notes:'BBQ King — legendary Cantonese BBQ restaurant on Goulburn St, open late. AUD 14–18.' },
  { city:'Sydney', country:'Australia',
    restaurant_name:'Chatswood Chase food court Asian', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:aud(14), local_price:14, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g255060-Sydney', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Asian food court in Chatswood (large Chinese suburb north of CBD). AUD 12–16.' },
  { city:'Sydney', country:'Australia',
    restaurant_name:'Din Tai Fung Sydney — chicken fried rice', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:aud(18.50), local_price:18.50, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'mid_tier', source_url:'https://www.dintaifung.com.au/', source_type:'official_menu', confidence_score:0.93,
    notes:'Din Tai Fung chicken fried rice. AUD 17–20.' },
  { city:'Sydney', country:'Australia',
    restaurant_name:'Vegetable fried rice (Hurstville / Burwood suburbs)', dish_name:'Vegetable Fried Rice',
    dish_category:'vegetable', price_cad:aud(16), local_price:16, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g255060-Sydney', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Vegetable fried rice in Hurstville / Burwood (major Chinese-Australian suburbs). AUD 14–19.' },
  { city:'Sydney', country:'Australia',
    restaurant_name:'Cantonese seafood restaurant (Chinatown / Hurstville)', dish_name:'Seafood Fried Rice',
    dish_category:'seafood', price_cad:aud(24), local_price:24, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g255060-Sydney', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Seafood fried rice at Cantonese restaurants. AUD 22–28.' },
  { city:'Sydney', country:'Australia',
    restaurant_name:'China Doll (Finger Wharf, Woolloomooloo)', dish_name:'Wok Fried Rice',
    dish_category:'house_special', price_cad:aud(28), local_price:28, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'high_end', source_url:'https://chinadoll.com.au/', source_type:'official_menu', confidence_score:0.85,
    notes:'China Doll — upscale pan-Asian on the Woolloomooloo waterfront. AUD 25–34.' },
  { city:'Sydney', country:'Australia',
    restaurant_name:'Mr. Wong — house special fried rice', dish_name:'XO Fried Rice',
    dish_category:'house_special', price_cad:aud(30), local_price:30, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'high_end', source_url:'https://www.merivale.com/venues/mrwong/', source_type:'official_menu', confidence_score:0.88,
    notes:'Mr. Wong specialty XO fried rice — house-made XO sauce. AUD 27–35.' },
  { city:'Sydney', country:'Australia',
    restaurant_name:'Rockpool Bar & Grill adjacent Asian (Sydney CBD)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:aud(33), local_price:33, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g255060-Sydney', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Upscale Asian in Sydney CBD\'s financial precinct. AUD 29–38.' },
  { city:'Sydney', country:'Australia',
    restaurant_name:'Shangri-La Hotel Sydney — Altitude Asian', dish_name:'Premium Fried Rice',
    dish_category:'premium', price_cad:aud(44), local_price:44, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'premium', source_url:'https://www.shangri-la.com/sydney/shangrila/dining/', source_type:'official_menu', confidence_score:0.80,
    notes:'Shangri-La Sydney — luxury hotel premium Asian. AUD 38–52.' },
  { city:'Sydney', country:'Australia',
    restaurant_name:'Park Hyatt Sydney — The Dining Room', dish_name:'Premium Asian Fried Rice',
    dish_category:'premium', price_cad:aud(48), local_price:48, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'premium', source_url:'https://www.hyatt.com/park-hyatt/en-US/sydph-park-hyatt-sydney/', source_type:'official_menu', confidence_score:0.78,
    notes:'Park Hyatt Sydney — Opera House-facing luxury hotel. AUD 42–56.' },
  { city:'Sydney', country:'Australia',
    restaurant_name:'Delivery Chinese (Uber Eats, Sydney CBD / inner west)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:aud(14.50), local_price:14.50, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'low_tier', source_url:'https://www.ubereats.com/au/sydney/food-delivery/chinese', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Chinese delivery via Uber Eats. AUD 13–17.' },
  { city:'Sydney', country:'Australia',
    restaurant_name:'Cantonese restaurant (Cabramatta, southwest Sydney)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:aud(12), local_price:12, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g255060-Sydney', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Cabramatta (Vietnamese-Chinese SW Sydney). AUD 11–14.' },
  { city:'Sydney', country:'Australia',
    restaurant_name:'Golden Century — Yang Chow', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:aud(26), local_price:26, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'high_end', source_url:'https://www.goldencentury.com.au/', source_type:'official_menu', confidence_score:0.88,
    notes:'Golden Century yang chow fried rice. AUD 24–30.' },

  // ── TEHRAN (USD) — +15 entries ────────────────────────────────────────────
  // Existing 7: USD 4, 6.5, 8, 9, 14(HS), 16(HS), 22(P)
  // All prices in USD equivalent (IRR too volatile to seed directly)
  { city:'Tehran', country:'Iran',
    restaurant_name:'Budget Chinese restaurant (south / central Tehran)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:usd(3), local_price:3, local_currency:'USD', exchange_rate_used:1.39,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g295424-Tehran', source_type:'third_party_menu', confidence_score:0.68,
    notes:'Cheapest Chinese restaurants in central/south Tehran. ~USD 2.50–4.' },
  { city:'Tehran', country:'Iran',
    restaurant_name:'Chinese delivery (Snappfood / Digikala, Tehran)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:usd(5), local_price:5, local_currency:'USD', exchange_rate_used:1.39,
    tier:'low_tier', source_url:'https://snappfood.ir/', source_type:'third_party_menu', confidence_score:0.70,
    notes:'Chinese delivery via Snappfood (Iran\'s major food delivery platform). ~USD 4–6.' },
  { city:'Tehran', country:'Iran',
    restaurant_name:'Chinese restaurant (Gholhak / Elahieh neighbourhood)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:usd(7), local_price:7, local_currency:'USD', exchange_rate_used:1.39,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g295424-Tehran', source_type:'third_party_menu', confidence_score:0.70,
    notes:'North Tehran affluent residential Chinese. ~USD 6–8.50.' },
  { city:'Tehran', country:'Iran',
    restaurant_name:'Vegetable fried rice (Saadat Abad area)', dish_name:'Vegetable Fried Rice',
    dish_category:'vegetable', price_cad:usd(7.50), local_price:7.50, local_currency:'USD', exchange_rate_used:1.39,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g295424-Tehran', source_type:'third_party_menu', confidence_score:0.70,
    notes:'Vegetable fried rice at Saadat Abad Chinese restaurants. ~USD 6.50–9.' },
  { city:'Tehran', country:'Iran',
    restaurant_name:'Chicken fried rice (north Tehran, Zafaraniyeh)', dish_name:'Chicken Fried Rice',
    dish_category:'meat_based', price_cad:usd(10), local_price:10, local_currency:'USD', exchange_rate_used:1.39,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g295424-Tehran', confidence_score:0.68,
    source_type:'third_party_menu', notes:'Chicken fried rice in Zafaraniyeh (upscale north Tehran). ~USD 9–12.' },
  { city:'Tehran', country:'Iran',
    restaurant_name:'Seafood fried rice (north Tehran upscale)', dish_name:'Prawn Fried Rice',
    dish_category:'seafood', price_cad:usd(12), local_price:12, local_currency:'USD', exchange_rate_used:1.39,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g295424-Tehran', source_type:'third_party_menu', confidence_score:0.68,
    notes:'Seafood fried rice at upscale north Tehran Chinese. ~USD 10–14.' },
  { city:'Tehran', country:'Iran',
    restaurant_name:'Chinese restaurant (Niavaran / Tajrish bazaar area)', dish_name:'Yang Chow Fried Rice',
    dish_category:'house_special', price_cad:usd(15), local_price:15, local_currency:'USD', exchange_rate_used:1.39,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g295424-Tehran', source_type:'third_party_menu', confidence_score:0.68,
    notes:'Upscale Chinese in Niavaran / Tajrish (top-tier north Tehran). ~USD 13–18.' },
  { city:'Tehran', country:'Iran',
    restaurant_name:'Laleh International Hotel Tehran — Chinese restaurant', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:usd(18), local_price:18, local_currency:'USD', exchange_rate_used:1.39,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g295424-Tehran', source_type:'third_party_menu', confidence_score:0.68,
    notes:'Laleh Hotel (former InterContinental Tehran) — Iranian 5-star. ~USD 16–22.' },
  { city:'Tehran', country:'Iran',
    restaurant_name:'Espinas Palace Hotel Tehran — restaurant', dish_name:'Premium Fried Rice',
    dish_category:'premium', price_cad:usd(24), local_price:24, local_currency:'USD', exchange_rate_used:1.39,
    tier:'premium', source_url:'https://www.espinashotel.com/', source_type:'official_menu', confidence_score:0.68,
    notes:'Espinas Palace Hotel — new luxury Tehran hotel. ~USD 20–28.' },
  { city:'Tehran', country:'Iran',
    restaurant_name:'Homa Hotel Tehran — Asian restaurant', dish_name:'Premium Fried Rice',
    dish_category:'premium', price_cad:usd(20), local_price:20, local_currency:'USD', exchange_rate_used:1.39,
    tier:'premium', source_url:'https://www.homahotel.com/', source_type:'official_menu', confidence_score:0.68,
    notes:'Homa Hotel Tehran (major Iranian chain). ~USD 17–24.' },
  { city:'Tehran', country:'Iran',
    restaurant_name:'Luxury hotel Chinese (Baam Tehran rooftop area)', dish_name:'Premium Asian Fried Rice',
    dish_category:'premium', price_cad:usd(28), local_price:28, local_currency:'USD', exchange_rate_used:1.39,
    tier:'premium', source_url:'https://www.tripadvisor.com/Restaurants-g295424-Tehran', source_type:'third_party_menu', confidence_score:0.65,
    notes:'Top-tier Tehran luxury hotel Chinese dining. ~USD 24–34.' },
  { city:'Tehran', country:'Iran',
    restaurant_name:'Chinese restaurant (Darband / Tochal foothills area)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:usd(8.50), local_price:8.50, local_currency:'USD', exchange_rate_used:1.39,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g295424-Tehran', source_type:'third_party_menu', confidence_score:0.68,
    notes:'Darband / Tochal (north Tehran mountain recreational area). ~USD 7.50–10.' },
  { city:'Tehran', country:'Iran',
    restaurant_name:'Chinese restaurant (Gheytarieh, north Tehran)', dish_name:'Vegetable Fried Rice',
    dish_category:'vegetable', price_cad:usd(9.50), local_price:9.50, local_currency:'USD', exchange_rate_used:1.39,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/Restaurants-g295424-Tehran', source_type:'third_party_menu', confidence_score:0.68,
    notes:'Mid-range Chinese in Gheytarieh (affluent north Tehran). ~USD 8.50–11.' },
  { city:'Tehran', country:'Iran',
    restaurant_name:'Chinese-Iranian fusion (Tehran modern restaurants)', dish_name:'Special Fried Rice',
    dish_category:'house_special', price_cad:usd(13), local_price:13, local_currency:'USD', exchange_rate_used:1.39,
    tier:'high_end', source_url:'https://www.tripadvisor.com/Restaurants-g295424-Tehran', source_type:'third_party_menu', confidence_score:0.66,
    notes:'Modern Chinese-Persian fusion concept in north Tehran. ~USD 11–16.' },
  { city:'Tehran', country:'Iran',
    restaurant_name:'Chinese takeaway (east Tehran / Tehranpars area)', dish_name:'Egg Fried Rice',
    dish_category:'basic', price_cad:usd(3.50), local_price:3.50, local_currency:'USD', exchange_rate_used:1.39,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/Restaurants-g295424-Tehran', source_type:'third_party_menu', confidence_score:0.68,
    notes:'Budget Chinese in east Tehran working-class district. ~USD 3–4.50.' },

  // ── WUHAN (CNY) — +15 entries ──────────────────────────────────────────────
  // Existing 7: CNY 10, 18, 25, 30, 45(HS), 68(HS), 95(P)
  { city:'Wuhan', country:'China',
    restaurant_name:'HUST / Wuhan University campus canteen 华科周边', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(7), local_price:7, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/wuhan', source_type:'third_party_menu', confidence_score:0.85,
    notes:'HUST (Huazhong Univ. of Science & Tech) or Wuhan University campus area. CNY 5–9.' },
  { city:'Wuhan', country:'China',
    restaurant_name:'Hongshan District neighbourhood Chinese 洪山区', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(12), local_price:12, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/wuhan', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Neighbourhood Chinese in Hongshan (student-heavy area). CNY 10–15.' },
  { city:'Wuhan', country:'China',
    restaurant_name:'Optics Valley (Guanggu) food court 光谷', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(22), local_price:22, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/wuhan', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Food court in Guanggu (Wuhan\'s tech hub). CNY 18–26.' },
  { city:'Wuhan', country:'China',
    restaurant_name:'Wuhan International Plaza area Chinese 武汉国广', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(28), local_price:28, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/wuhan', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Wuhan International Plaza (CBD mall). CNY 24–34.' },
  { city:'Wuhan', country:'China',
    restaurant_name:'Chicken fried rice (Wuchang District 武昌区)', dish_name:'Chicken Fried Rice 鸡肉炒饭',
    dish_category:'meat_based', price_cad:cny(30), local_price:30, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/wuhan', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Wuchang District neighbourhood Chinese. CNY 26–36.' },
  { city:'Wuhan', country:'China',
    restaurant_name:'Xibei 西贝莜面村 (Wuhan)', dish_name:'Mixed Fried Rice 炒饭',
    dish_category:'basic', price_cad:cny(38), local_price:38, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.xibeicanyin.com/', source_type:'official_menu', confidence_score:0.85,
    notes:'Xibei chain in Wuhan malls. CNY 34–44.' },
  { city:'Wuhan', country:'China',
    restaurant_name:'Din Tai Fung 鼎泰丰 (Wuhan)', dish_name:'Yang Chow Fried Rice 扬州炒饭',
    dish_category:'house_special', price_cad:cny(62), local_price:62, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.dintaifung.com.cn/', source_type:'official_menu', confidence_score:0.88,
    notes:'Din Tai Fung Wuhan location in major mall. CNY 58–72.' },
  { city:'Wuhan', country:'China',
    restaurant_name:'Crystal Jade 翡翠酒家 (Wuhan)', dish_name:'Vegetable Fried Rice 蔬菜炒饭',
    dish_category:'vegetable', price_cad:cny(50), local_price:50, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.crystaljade.com/', source_type:'official_menu', confidence_score:0.80,
    notes:'Crystal Jade Cantonese chain in Wuhan. CNY 44–58.' },
  { city:'Wuhan', country:'China',
    restaurant_name:'Seafood fried rice (mid-range Wuhan Chinese)', dish_name:'Seafood Fried Rice 海鲜炒饭',
    dish_category:'seafood', price_cad:cny(42), local_price:42, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/wuhan', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Seafood fried rice at mid-range Wuhan Cantonese. CNY 36–50.' },
  { city:'Wuhan', country:'China',
    restaurant_name:'Upscale Cantonese (Jianghan Road 江汉路 upscale)', dish_name:'Yang Chow Fried Rice 扬州炒饭',
    dish_category:'house_special', price_cad:cny(78), local_price:78, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.dianping.com/wuhan', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Upscale Cantonese on Jianghan Road. CNY 68–90.' },
  { city:'Wuhan', country:'China',
    restaurant_name:'Kempinski Hotel Wuhan Chinese restaurant', dish_name:'Yang Chow Fried Rice 扬州炒饭',
    dish_category:'house_special', price_cad:cny(108), local_price:108, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.kempinski.com/en/wuhan/', source_type:'official_menu', confidence_score:0.82,
    notes:'Kempinski Hotel Wuhan 5-star Chinese. CNY 95–122.' },
  { city:'Wuhan', country:'China',
    restaurant_name:'Wuhan Marriott Hotel Chinese restaurant', dish_name:'Premium Fried Rice 炒饭',
    dish_category:'premium', price_cad:cny(128), local_price:128, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'premium', source_url:'https://www.marriott.com/hotels/travel/wuhmc-wuhan-marriott-hotel-hankou/', source_type:'official_menu', confidence_score:0.82,
    notes:'Wuhan Marriott Hankou — luxury Chinese dining. CNY 115–145.' },
  { city:'Wuhan', country:'China',
    restaurant_name:'Vegetable fried rice (Hankou 汉口 neighbourhood)', dish_name:'Vegetable Fried Rice 蔬菜炒饭',
    dish_category:'vegetable', price_cad:cny(32), local_price:32, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/wuhan', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Vegetable fried rice at Hankou neighbourhood Chinese. CNY 28–38.' },
  { city:'Wuhan', country:'China',
    restaurant_name:'Wuhan East Lake Scenic Area restaurant 东湖', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(35), local_price:35, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/wuhan', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Tourism restaurant near East Lake park (Wuhan\'s major scenic area). CNY 30–42.' },
  { city:'Wuhan', country:'China',
    restaurant_name:'Wuhan Yangtze River waterfront restaurant 黄鹤楼区域', dish_name:'Egg Fried Rice 蛋炒饭',
    dish_category:'basic', price_cad:cny(38), local_price:38, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/wuhan', source_type:'third_party_menu', confidence_score:0.75,
    notes:'Tourism-area restaurant near Yellow Crane Tower / Yangtze bridge. CNY 32–46.' },
]

function dataQualityLabel(n: number): string {
  if (n >= 15) return 'High confidence'
  if (n >= 10) return 'Strong'
  if (n >= 5)  return 'Moderate'
  return 'Limited'
}

async function expandCity(city: string, newEntries: E[]) {
  console.log(`\n─── ${city} (+${newEntries.length}) ───`)
  const rows = newEntries.map(e => ({
    city: e.city, country: e.country,
    restaurant_name: e.restaurant_name, dish_name: e.dish_name,
    dish_category: e.dish_category,
    included_in_baseline: e.dish_category === 'basic' || e.dish_category === 'vegetable',
    tier: e.tier, local_price: e.local_price, local_currency: e.local_currency,
    exchange_rate_used: e.exchange_rate_used, price_cad: e.price_cad,
    source: 'Manual seed – expand-v1-batch3',
    source_type: e.source_type, source_url: e.source_url,
    confidence_score: e.confidence_score, approved: true, active: true,
    date_accessed: NOW, notes: e.notes ?? null,
  }))
  const { error: insErr } = await s.from('restaurants').insert(rows)
  if (insErr) { console.error(`  ✗ ${insErr.message}`); return }
  console.log(`  ✓ Inserted ${rows.length}`)

  const { data: all } = await s.from('restaurants')
    .select('price_cad,included_in_baseline,confidence_score')
    .eq('city', city).eq('active', true)
  if (!all) return

  const blRows = all.filter(r => r.included_in_baseline)
  const allP   = all.map(r => r.price_cad as number).sort((a,b) => a-b)
  const blP    = blRows.map(r => r.price_cad as number).sort((a,b) => a-b)
  if (!blP.length) return

  const mid    = Math.floor(blP.length/2)
  const median = blP.length%2===1 ? blP[mid] : (blP[mid-1]+blP[mid])/2
  const n=allP.length, k=Math.round(n*0.05)
  const t = k>0 ? allP.slice(k,n-k) : allP
  const avg = t.reduce((s,p)=>s+p,0)/t.length
  const conf= blRows.reduce((s,row)=>s+(row.confidence_score as number),0)/blRows.length

  await s.from('cities').update({
    price_cad:r(median), baseline_median_cad:r(median),
    market_average_cad:r(avg), market_min_cad:allP[0], market_max_cad:allP[n-1],
    market_entry_count:n, baseline_entry_count:blRows.length,
    data_quality_label:dataQualityLabel(n),
    price_source:`Baseline median from ${blRows.length} verified entries`,
    price_updated_at:NOW, confidence_score:r(conf),
  }).eq('city', city)
  console.log(`  ✓ CA$${r(median)} (${blRows.length} BL / ${n} total) | ${dataQualityLabel(n)}`)
}

async function run() {
  const cities = [...new Set(ENTRIES.map(e => e.city))]
  for (const city of cities) {
    await expandCity(city, ENTRIES.filter(e => e.city===city))
  }
  console.log('\n✓ Batch 3 complete.')
}
run().catch(console.error)
