/**
 * Seed script v9 — 22 new cities.
 *
 * Run with:
 *   export $(grep -v '^#' .env.local | xargs) && npx tsx scripts/seed-update-v9.ts
 *
 * Exchange rates (May 2026):
 *   USD 1.39  CNY 0.203  INR 0.0165  AUD 0.88   GBP 1.76
 *   EUR 1.51  RUB 0.015  AED 0.379   SAR 0.370  EGP 0.028
 *   PKR 0.0036  MXN 0.072  TRY 0.037  ARS 0.0011
 *   Tehran priced in USD (IRR too volatile to seed)
 */

import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
)
const NOW = new Date().toISOString()

const r   = (n: number) => Math.round(n * 100) / 100
const usd = (p: number) => r(p * 1.39)
const cny = (p: number) => r(p * 0.203)
const inr = (p: number) => r(p * 0.0165)
const aud = (p: number) => r(p * 0.88)
const gbp = (p: number) => r(p * 1.76)
const eur = (p: number) => r(p * 1.51)
const rub = (p: number) => r(p * 0.015)
const aed = (p: number) => r(p * 0.379)
const sar = (p: number) => r(p * 0.370)
const egp = (p: number) => r(p * 0.028)
const pkr = (p: number) => r(p * 0.0036)
const mxn = (p: number) => r(p * 0.072)
const tri = (p: number) => r(p * 0.037)   // TRY
const ars = (p: number) => r(p * 0.0011)

type DishCat = 'basic'|'vegetable'|'meat_based'|'seafood'|'house_special'|'premium'
type Tier    = 'low_tier'|'mid_tier'|'high_end'|'premium'

type Entry = {
  city: string; country: string
  restaurant_name: string; dish_name: string
  dish_category: DishCat
  price_cad: number; local_price: number; local_currency: string; exchange_rate_used: number
  tier: Tier
  source_url: string; source_type: string; confidence_score: number; notes?: string
}

type CityMeta = {
  city: string; country: string; region: string
  flag: string; latitude: number; longitude: number; population: string
  blurb: string
}

const CITY_META: CityMeta[] = [
  { city:'Mumbai',       country:'India',          region:'South Asia',
    flag:'🇮🇳', latitude:19.0760,  longitude:72.8777,  population:'12442373',
    blurb:"A megacity of 20 million on India's western coast and the financial capital of South Asia. Mumbai is home to Bollywood and India's largest stock exchange. It has a unique Indo-Chinese food culture — Hakka Chinese cuisine has been adapted over generations to Indian tastes, producing dishes like Hakka noodles and Manchurian that are distinctly Mumbaikar." },
  { city:'New Delhi',    country:'India',          region:'South Asia',
    flag:'🇮🇳', latitude:28.6139,  longitude:77.2090,  population:'11034555',
    blurb:"India's capital and a sprawling metropolis of over 30 million in the National Capital Territory. Delhi is the political and administrative centre of India, with a booming tech sector and a diverse culinary scene. Chinese-Indian cuisine is ubiquitous across the city's restaurants and street stalls, forming a major category in its own right." },
  { city:'Kolkata',      country:'India',          region:'South Asia',
    flag:'🇮🇳', latitude:22.5726,  longitude:88.3639,  population:'4631392',
    blurb:"The cultural capital of India and home to the country's oldest Chinese community, descended from Hakka immigrants who arrived in the 18th century. Kolkata's Chinatown in Tiretti Bazaar is the last surviving Chinese-Indian settlement in the country, and it produced a fusion cuisine that bears little resemblance to Chinese food anywhere else in the world." },
  { city:'Melbourne',    country:'Australia',      region:'Oceania',
    flag:'🇦🇺', latitude:-37.8136, longitude:144.9631, population:'5078193',
    blurb:"Australia's second-largest city and widely considered its cultural capital. A compact, walkable city known for its exceptional coffee culture, arts scene, and one of the highest densities of restaurants per capita in the world. Melbourne's Chinatown on Little Bourke Street is the oldest continuously operating Chinatown in the Western world." },
  { city:'Sydney',       country:'Australia',      region:'Oceania',
    flag:'🇦🇺', latitude:-33.8688, longitude:151.2093, population:'5312000',
    blurb:"Australia's largest city and a global finance and tourism hub built around one of the world's most famous harbour settings. Sydney has a large and diverse Asian population — particularly Chinese, Vietnamese, and Korean communities — concentrated in suburbs like Hurstville, Burwood, and Haymarket. Its Chinatown is one of the largest in the Southern Hemisphere." },
  { city:'London',       country:'United Kingdom', region:'Europe',
    flag:'🇬🇧', latitude:51.5074,  longitude:-0.1278,  population:'9002488',
    blurb:"A global metropolis and one of the world's leading financial, cultural, and creative capitals. London is one of the most ethnically diverse cities on earth, with significant Chinese, Indian, and Bangladeshi communities. Its Chinatown in Soho — centred on Gerrard Street — is small but internationally renowned for its density of Cantonese and regional Chinese restaurants." },
  { city:'Paris',        country:'France',         region:'Europe',
    flag:'🇫🇷', latitude:48.8566,  longitude:2.3522,   population:'2140526',
    blurb:"The cultural and political capital of France and one of the most visited cities in the world. Paris has a large Chinese and Southeast Asian immigrant population centred in the 13th arrondissement, which contains the largest Chinatown in Europe. The city's restaurant scene is among the world's most sophisticated, from Michelin-starred French cuisine to affordable Asian street food." },
  { city:'Moscow',       country:'Russia',         region:'Europe',
    flag:'🇷🇺', latitude:55.7558,  longitude:37.6173,  population:'12506468',
    blurb:"Russia's capital and largest city, with over 12 million people and the largest economy in Europe by purchasing power. Moscow's Chinese restaurant scene has grown significantly with deepening Chinese-Russian business ties. Despite geopolitical isolation from the West, the city retains a sophisticated dining culture with a growing number of Chinese-operated restaurants across all price tiers." },
  { city:'Amsterdam',    country:'Netherlands',    region:'Europe',
    flag:'🇳🇱', latitude:52.3676,  longitude:4.9041,   population:'921402',
    blurb:"A compact, cosmopolitan city that punches far above its weight economically. Amsterdam is a global hub for finance, tech, and creative industries with a famously high quality of life. Its Chinese community is centred around the Zeedijk street, known as the 'Chinese Neighbourhood,' with well-established Cantonese restaurants dating back to the post-war period." },
  { city:'Dubai',        country:'United Arab Emirates', region:'Middle East',
    flag:'🇦🇪', latitude:25.2048,  longitude:55.2708,  population:'3604713',
    blurb:"A city that barely existed 50 years ago and is now one of the most cosmopolitan places on earth. Dubai's population is over 90% expatriates, drawn by zero income tax, world-class infrastructure, and aggressive economic development. Chinese restaurants cluster in areas like JBR, DIFC, and the malls, serving both a large Chinese expat community and high-spending tourists." },
  { city:'Riyadh',       country:'Saudi Arabia',   region:'Middle East',
    flag:'🇸🇦', latitude:24.7136,  longitude:46.6753,  population:'7676654',
    blurb:"The capital and largest city of Saudi Arabia, undergoing rapid transformation through Vision 2030. A historically conservative city that has seen dramatic liberalisation in entertainment and dining since 2017. International restaurant chains and upscale dining have expanded rapidly, and Chinese restaurants serve both the expatriate community and a growing class of Saudi diners exploring international cuisine." },
  { city:'Cairo',        country:'Egypt',          region:'Africa',
    flag:'🇪🇬', latitude:30.0444,  longitude:31.2357,  population:'21323000',
    blurb:"Egypt's capital and the largest city in Africa and the Arab world. Cairo is a city of stark contrasts — ancient monuments and deep poverty alongside a rapidly growing middle class. Its Chinese restaurant scene is modest but growing, largely driven by Chinese investment in Egypt and a small but established expat community. Local restaurant prices remain very affordable by global standards." },
  { city:'Karachi',      country:'Pakistan',       region:'South Asia',
    flag:'🇵🇰', latitude:24.8607,  longitude:67.0011,  population:'16093786',
    blurb:"Pakistan's largest city and economic capital, with a population of 16 million. One of the world's most densely populated cities and a major industrial and commercial hub. Chinese restaurants are concentrated in upscale areas like Defence Housing Authority, serving Chinese-Pakistani businesspeople and a local clientele with a growing appetite for international cuisine." },
  { city:'Mexico City',  country:'Mexico',         region:'Latin America',
    flag:'🇲🇽', latitude:19.4326,  longitude:-99.1332, population:'9209944',
    blurb:"Latin America's most populous city and one of the world's great cultural capitals. Mexico City has undergone a dramatic culinary renaissance, regularly appearing on lists of the world's best restaurant cities. Its Barrio Chino on Dolores Street is the oldest Chinatown in Latin America, and the city's broader Chinese-food scene has expanded rapidly into its many neighbourhoods." },
  { city:'Istanbul',     country:'Turkey',         region:'Europe',
    flag:'🇹🇷', latitude:41.0082,  longitude:28.9784,  population:'15840900',
    blurb:"A city straddling two continents and one of history's most significant urban centres. With 15 million people, Istanbul is the largest city in Europe by population and the cultural and economic heart of Turkey. Chinese restaurants are concentrated in upscale districts like Nişantaşı and Beyoğlu, serving a business and expat clientele. Turkish street food dominates locally, making Chinese food a premium option." },
  { city:'Buenos Aires', country:'Argentina',      region:'Latin America',
    flag:'🇦🇷', latitude:-34.6037, longitude:-58.3816, population:'3075646',
    blurb:"The capital of Argentina and one of South America's most cosmopolitan cities. Buenos Aires has a strong European cultural heritage and an outsized reputation for nightlife, tango, steak, and wine. Its Barrio Chino in Belgrano is a vibrant hub of Chinese restaurants and Asian grocery stores, drawing both the Chinese community and local porteños seeking alternatives to Argentine cuisine." },
  { city:'Tehran',       country:'Iran',           region:'Middle East',
    flag:'🇮🇷', latitude:35.6892,  longitude:51.3890,  population:'9259009',
    blurb:"The capital of Iran and home to over 9 million people. Tehran is a mountainous, sprawling city of dramatic contrasts — ancient bazaars and modern shopping centres, conservative tradition and a sophisticated urban population. Chinese restaurants have established a foothold in affluent northern Tehran neighbourhoods, often frequented by the city's middle and upper classes as a marker of cosmopolitan taste." },
  { city:'Suzhou',       country:'China',          region:'East Asia',
    flag:'🇨🇳', latitude:31.2989,  longitude:120.5853, population:'10748630',
    blurb:"China's 'Venice of the East,' Suzhou is an ancient city of classical gardens and silk production, now fully integrated into the greater Shanghai economic zone. Its proximity to Shanghai (30 minutes by high-speed rail) means dining prices and culture mirror Shanghai closely. A major industrial and tech hub hosting large numbers of international companies and their employees." },
  { city:'Wuhan',        country:'China',          region:'East Asia',
    flag:'🇨🇳', latitude:30.5928,  longitude:114.3055, population:'12326518',
    blurb:"Central China's largest city and the capital of Hubei province, sitting at the confluence of the Yangtze and Han rivers. Wuhan is a major industrial, educational, and transportation hub with over a million university students — making affordable dining a cornerstone of its food culture. It has a distinctive local culinary tradition built around hot dry noodles and river fish." },
  { city:'Chongqing',    country:'China',          region:'East Asia',
    flag:'🇨🇳', latitude:29.5630,  longitude:106.5516, population:'31243200',
    blurb:"One of China's four direct-controlled municipalities and the most populous city proper on earth. Chongqing is the economic gateway to western China, perched dramatically on cliffs above the Yangtze River. It is the undisputed capital of Sichuan-style hot pot, and its street food culture is intense, cheap, and deeply spicy. A rapidly growing tech and manufacturing centre." },
  { city:'Chengdu',      country:'China',          region:'East Asia',
    flag:'🇨🇳', latitude:30.5723,  longitude:104.0665, population:'21000000',
    blurb:"The capital of Sichuan province and one of China's most liveable cities. Chengdu is famous for its laid-back café culture, giant panda research base, and the most celebrated spicy food tradition in China. It consistently ranks among the most affordable major Chinese cities for dining and housing, attracting talent from across the country with its quality of life and lower cost of living." },
  { city:'Miami',        country:'United States',  region:'North America',
    flag:'🇺🇸', latitude:25.7617,  longitude:-80.1918, population:'467963',
    blurb:"The southernmost major city in the continental United States and the gateway to Latin America. Miami is defined by its Cuban and Latin American heritage, spectacular beaches, and year-round warmth. It is a major finance and real estate hub attracting wealth from across the Americas. Its Chinese restaurant scene is concentrated in areas like Brickell and Coral Gables, serving a business-class and tourist clientele." },
]

// ─────────────────────────────────────────────────────────────────────────────
// ENTRIES — 7 per city
// ─────────────────────────────────────────────────────────────────────────────
const ENTRIES: Entry[] = [

  // ── MUMBAI (INR) ─────────────────────────────────────────────────────────
  { city:'Mumbai', country:'India', restaurant_name:'Mohammed Ali Road Street Chinese',
    dish_name:'Egg Fried Rice 炒饭', dish_category:'basic',
    price_cad:inr(90), local_price:90, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'low_tier', source_url:'https://www.zomato.com/mumbai', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Street Indo-Chinese stall near Mohammed Ali Road food district. INR 80–100 typical.' },
  { city:'Mumbai', country:'India', restaurant_name:'Nanking Restaurant (Crawford Market)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:inr(160), local_price:160, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'low_tier', source_url:'https://www.zomato.com/mumbai/nanking', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Old-school Hakka Chinese restaurant near Crawford Market, South Mumbai.' },
  { city:'Mumbai', country:'India', restaurant_name:'Mainland China (Bandra)',
    dish_name:'Vegetable Fried Rice', dish_category:'vegetable',
    price_cad:inr(380), local_price:380, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.mainlandchina.co.in/menu/', source_type:'official_menu', confidence_score:0.85,
    notes:'Mainland China is one of India\'s largest Indo-Chinese restaurant chains, with multiple Mumbai outlets.' },
  { city:'Mumbai', country:'India', restaurant_name:'Mainland China (Bandra)',
    dish_name:'Chicken Fried Rice', dish_category:'meat_based',
    price_cad:inr(420), local_price:420, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.mainlandchina.co.in/menu/', source_type:'official_menu', confidence_score:0.85 },
  { city:'Mumbai', country:'India', restaurant_name:'Ming Palace (Taj Lands End)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:inr(650), local_price:650, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'high_end', source_url:'https://www.tajhotels.com/mumbai/dining', source_type:'official_menu', confidence_score:0.80,
    notes:'Hotel Chinese restaurant at Taj Lands End, Bandra.' },
  { city:'Mumbai', country:'India', restaurant_name:'Hakkasan Mumbai (Bandra Kurla)',
    dish_name:'Yang Chow Fried Rice', dish_category:'house_special',
    price_cad:inr(1450), local_price:1450, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'premium', source_url:'https://hakkasan.com/locations/mumbai/', source_type:'official_menu', confidence_score:0.90,
    notes:'Hakkasan is the luxury Cantonese global chain; Mumbai BKC location.' },
  { city:'Mumbai', country:'India', restaurant_name:'The China House (Grand Hyatt Mumbai)',
    dish_name:'Special Fried Rice', dish_category:'house_special',
    price_cad:inr(980), local_price:980, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'high_end', source_url:'https://www.hyatt.com/grand-hyatt/mumbai/dining', source_type:'official_menu', confidence_score:0.82 },

  // ── NEW DELHI (INR) ──────────────────────────────────────────────────────
  { city:'New Delhi', country:'India', restaurant_name:'Lajpat Nagar Street Chinese',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:inr(100), local_price:100, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'low_tier', source_url:'https://www.zomato.com/delhi', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative street-level Indo-Chinese stall, Lajpat Nagar market area.' },
  { city:'New Delhi', country:'India', restaurant_name:'Berco\'s (Connaught Place)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:inr(320), local_price:320, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.bercos.in/menu/', source_type:'official_menu', confidence_score:0.85,
    notes:"Berco's is one of Delhi's most iconic Indo-Chinese chains, est. 1983, with multiple Connaught Place locations." },
  { city:'New Delhi', country:'India', restaurant_name:'China Garden (Defence Colony)',
    dish_name:'Vegetable Fried Rice', dish_category:'vegetable',
    price_cad:inr(380), local_price:380, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.zomato.com/delhi/china-garden', source_type:'third_party_menu', confidence_score:0.82 },
  { city:'New Delhi', country:'India', restaurant_name:'Berco\'s (Connaught Place)',
    dish_name:'Chicken Fried Rice', dish_category:'meat_based',
    price_cad:inr(360), local_price:360, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.bercos.in/menu/', source_type:'official_menu', confidence_score:0.85 },
  { city:'New Delhi', country:'India', restaurant_name:'Gung Ho (Greater Kailash)',
    dish_name:'Yang Chow Fried Rice', dish_category:'house_special',
    price_cad:inr(520), local_price:520, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.zomato.com/delhi/gung-ho', source_type:'third_party_menu', confidence_score:0.78 },
  { city:'New Delhi', country:'India', restaurant_name:'House of Ming (Taj Mahal Hotel)',
    dish_name:'Yang Chow Fried Rice', dish_category:'house_special',
    price_cad:inr(1200), local_price:1200, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'premium', source_url:'https://www.tajhotels.com/newdelhi/houseofming/', source_type:'official_menu', confidence_score:0.88,
    notes:'House of Ming at Taj Mahal Hotel is one of Delhi\'s most celebrated Chinese fine-dining restaurants.' },
  { city:'New Delhi', country:'India', restaurant_name:'China Kitchen (Hyatt Regency Delhi)',
    dish_name:'Premium Fried Rice', dish_category:'premium',
    price_cad:inr(1600), local_price:1600, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'premium', source_url:'https://www.hyatt.com/hyatt-regency/delhi/dining', source_type:'official_menu', confidence_score:0.85 },

  // ── KOLKATA (INR) ────────────────────────────────────────────────────────
  { city:'Kolkata', country:'India', restaurant_name:'Tiretti Bazaar Street Stall (Chinatown)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:inr(60), local_price:60, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'low_tier', source_url:'https://www.zomato.com/kolkata/tiretti-bazaar', source_type:'third_party_menu', confidence_score:0.82,
    notes:"Tiretti Bazaar (Kolkata's Chinatown) hawker stall. INR 50–70 typical for egg fried rice." },
  { city:'Kolkata', country:'India', restaurant_name:'Kim Fa Restaurant (Tiretti Bazaar)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:inr(120), local_price:120, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'low_tier', source_url:'https://www.zomato.com/kolkata/kim-fa', source_type:'third_party_menu', confidence_score:0.82,
    notes:'Classic Hakka-Kolkata Chinese restaurant in Tiretti Bazaar, run by the Chinese-Indian community.' },
  { city:'Kolkata', country:'India', restaurant_name:'Eau Chew Restaurant (Park Street)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:inr(200), local_price:200, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.zomato.com/kolkata/eau-chew', source_type:'third_party_menu', confidence_score:0.85,
    notes:'Eau Chew is a Kolkata institution for authentic Hakka-Kolkata Chinese cuisine, established decades ago.' },
  { city:'Kolkata', country:'India', restaurant_name:'Mainland China (Park Street)',
    dish_name:'Vegetable Fried Rice', dish_category:'vegetable',
    price_cad:inr(340), local_price:340, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.mainlandchina.co.in/menu/', source_type:'official_menu', confidence_score:0.85 },
  { city:'Kolkata', country:'India', restaurant_name:'Song Hay Restaurant (Nirmal Chandra St)',
    dish_name:'Chicken Fried Rice', dish_category:'meat_based',
    price_cad:inr(280), local_price:280, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'mid_tier', source_url:'https://www.zomato.com/kolkata/song-hay', source_type:'third_party_menu', confidence_score:0.80 },
  { city:'Kolkata', country:'India', restaurant_name:'Chinoiserie (Taj Bengal)',
    dish_name:'Yang Chow Fried Rice', dish_category:'house_special',
    price_cad:inr(980), local_price:980, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'high_end', source_url:'https://www.tajhotels.com/kolkata/chinoiserie/', source_type:'official_menu', confidence_score:0.85,
    notes:'Chinoiserie at Taj Bengal is Kolkata\'s most prestigious Chinese restaurant.' },
  { city:'Kolkata', country:'India', restaurant_name:'The China Town Restaurant (5-star)',
    dish_name:'Special Fried Rice', dish_category:'premium',
    price_cad:inr(1200), local_price:1200, local_currency:'INR', exchange_rate_used:0.0165,
    tier:'premium', source_url:'https://www.zomato.com/kolkata', source_type:'third_party_menu', confidence_score:0.75 },

  // ── MELBOURNE (AUD) ──────────────────────────────────────────────────────
  { city:'Melbourne', country:'Australia', restaurant_name:'Chinatown BBQ (Little Bourke St)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:aud(13.50), local_price:13.50, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'low_tier', source_url:'https://www.zomato.com/melbourne/chinatown', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Representative budget Cantonese BBQ restaurant, Melbourne Chinatown on Little Bourke St.' },
  { city:'Melbourne', country:'Australia', restaurant_name:'Shark Fin Inn (Little Bourke St)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:aud(17.00), local_price:17.00, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'mid_tier', source_url:'https://www.zomato.com/melbourne/shark-fin-inn', source_type:'third_party_menu', confidence_score:0.82,
    notes:'Shark Fin Inn is a Chinatown institution on Little Bourke Street, known for yum cha.' },
  { city:'Melbourne', country:'Australia', restaurant_name:'Din Tai Fung Melbourne (Emporium)',
    dish_name:'Vegetable & Mushroom Fried Rice', dish_category:'vegetable',
    price_cad:aud(18.00), local_price:18.00, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'mid_tier', source_url:'https://www.dintaifung.com.au/menu/', source_type:'official_menu', confidence_score:0.93 },
  { city:'Melbourne', country:'Australia', restaurant_name:'HuTong Dumpling Bar (Market Lane)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:aud(19.50), local_price:19.50, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'mid_tier', source_url:'https://www.hutong.com.au/menu/', source_type:'official_menu', confidence_score:0.88,
    notes:'HuTong is one of Melbourne\'s most celebrated Chinese restaurants, famed for its xiao long bao.' },
  { city:'Melbourne', country:'Australia', restaurant_name:'HuTong Dumpling Bar (Market Lane)',
    dish_name:'Yang Chow Fried Rice', dish_category:'house_special',
    price_cad:aud(23.00), local_price:23.00, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'mid_tier', source_url:'https://www.hutong.com.au/menu/', source_type:'official_menu', confidence_score:0.88 },
  { city:'Melbourne', country:'Australia', restaurant_name:'Flower Drum (Market Lane)',
    dish_name:'Yang Chow Fried Rice', dish_category:'house_special',
    price_cad:aud(42.00), local_price:42.00, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'high_end', source_url:'https://www.flowerdrum.melbourne/menu/', source_type:'official_menu', confidence_score:0.90,
    notes:'Flower Drum is Melbourne\'s most acclaimed Cantonese fine dining restaurant, operating since 1975.' },
  { city:'Melbourne', country:'Australia', restaurant_name:'Flower Drum (Market Lane)',
    dish_name:'Premium Egg White Fried Rice', dish_category:'premium',
    price_cad:aud(55.00), local_price:55.00, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'premium', source_url:'https://www.flowerdrum.melbourne/menu/', source_type:'official_menu', confidence_score:0.88 },

  // ── SYDNEY (AUD) ─────────────────────────────────────────────────────────
  { city:'Sydney', country:'Australia', restaurant_name:'Market City Food Court (Haymarket)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:aud(13.00), local_price:13.00, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'low_tier', source_url:'https://www.zomato.com/sydney/chinatown', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Market City food court in Haymarket (Sydney Chinatown); budget Chinese stalls AUD 12–15.' },
  { city:'Sydney', country:'Australia', restaurant_name:'Din Tai Fung Sydney (World Square)',
    dish_name:'Vegetable & Mushroom Fried Rice', dish_category:'vegetable',
    price_cad:aud(17.50), local_price:17.50, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'mid_tier', source_url:'https://www.dintaifung.com.au/menu/', source_type:'official_menu', confidence_score:0.93 },
  { city:'Sydney', country:'Australia', restaurant_name:'Golden Century Seafood (Haymarket)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:aud(18.00), local_price:18.00, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'mid_tier', source_url:'https://www.goldencentury.com.au/menu/', source_type:'official_menu', confidence_score:0.88,
    notes:'Golden Century is a Sydney Chinatown institution, famous for live seafood and late-night dining.' },
  { city:'Sydney', country:'Australia', restaurant_name:'Marigold Restaurant (World Square)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:aud(19.00), local_price:19.00, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'mid_tier', source_url:'https://www.marigold.com.au/menu/', source_type:'official_menu', confidence_score:0.82 },
  { city:'Sydney', country:'Australia', restaurant_name:'Mr. Wong (Bridge St, CBD)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:aud(22.00), local_price:22.00, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'high_end', source_url:'https://www.merivale.com/venues/mrwong/', source_type:'official_menu', confidence_score:0.88,
    notes:'Mr. Wong is one of Sydney\'s most popular upscale Cantonese restaurants in the CBD.' },
  { city:'Sydney', country:'Australia', restaurant_name:'Mr. Wong (Bridge St, CBD)',
    dish_name:'Yang Chow Fried Rice', dish_category:'house_special',
    price_cad:aud(26.00), local_price:26.00, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'high_end', source_url:'https://www.merivale.com/venues/mrwong/', source_type:'official_menu', confidence_score:0.88 },
  { city:'Sydney', country:'Australia', restaurant_name:'Lotus (Potts Point)',
    dish_name:'Premium Fried Rice', dish_category:'premium',
    price_cad:aud(58.00), local_price:58.00, local_currency:'AUD', exchange_rate_used:0.88,
    tier:'premium', source_url:'https://www.lotusrestaurant.com.au/', source_type:'official_menu', confidence_score:0.80 },

  // ── LONDON (GBP) ─────────────────────────────────────────────────────────
  { city:'London', country:'United Kingdom', restaurant_name:'New Loon Moon (Chinatown, Gerrard St)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:gbp(8.50), local_price:8.50, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'mid_tier', source_url:'https://www.newloonmoon.com/menu/', source_type:'official_menu', confidence_score:0.85,
    notes:'New Loon Moon is a classic Chinatown restaurant on Gerrard Street, one of the most affordable options.' },
  { city:'London', country:'United Kingdom', restaurant_name:'Dumplings\' Legend (Chinatown)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:gbp(9.50), local_price:9.50, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'mid_tier', source_url:'https://www.dumplingslegend.com/menu/', source_type:'official_menu', confidence_score:0.85 },
  { city:'London', country:'United Kingdom', restaurant_name:'Barshu (Soho)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:gbp(14.00), local_price:14.00, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'mid_tier', source_url:'https://www.bar-shu.co.uk/menu/', source_type:'official_menu', confidence_score:0.88,
    notes:'Barshu is one of London\'s most acclaimed Sichuan restaurants in Soho.' },
  { city:'London', country:'United Kingdom', restaurant_name:'Din Tai Fung London (Seven Dials)',
    dish_name:'Vegetable Fried Rice', dish_category:'vegetable',
    price_cad:gbp(15.00), local_price:15.00, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'mid_tier', source_url:'https://dintaifung.co.uk/menu/', source_type:'official_menu', confidence_score:0.93 },
  { city:'London', country:'United Kingdom', restaurant_name:'Hakkasan (Hanway Place, Fitzrovia)',
    dish_name:'Yang Chow Fried Rice', dish_category:'house_special',
    price_cad:gbp(32.00), local_price:32.00, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'high_end', source_url:'https://hakkasan.com/locations/london/', source_type:'official_menu', confidence_score:0.92,
    notes:'Hakkasan London — Michelin-starred Cantonese restaurant in Fitzrovia.' },
  { city:'London', country:'United Kingdom', restaurant_name:'Mr. Chow (Knightsbridge)',
    dish_name:'Yang Chow Fried Rice', dish_category:'house_special',
    price_cad:gbp(42.00), local_price:42.00, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'premium', source_url:'https://www.mrchow.com/london/', source_type:'official_menu', confidence_score:0.88,
    notes:'Mr. Chow in Knightsbridge — iconic luxury Chinese restaurant frequented by celebrities since 1968.' },
  { city:'London', country:'United Kingdom', restaurant_name:'China Tang (Dorchester Hotel)',
    dish_name:'Special Fried Rice', dish_category:'premium',
    price_cad:gbp(55.00), local_price:55.00, local_currency:'GBP', exchange_rate_used:1.76,
    tier:'premium', source_url:'https://www.chinatanglondon.com/menu/', source_type:'official_menu', confidence_score:0.85,
    notes:'China Tang at The Dorchester — one of London\'s most prestigious Cantonese dining rooms.' },

  // ── PARIS (EUR) ──────────────────────────────────────────────────────────
  { city:'Paris', country:'France', restaurant_name:'Tang Frères area restaurant (13th arr.)',
    dish_name:'Egg Fried Rice 蛋炒飯', dish_category:'basic',
    price_cad:eur(8.50), local_price:8.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/paris/13th-arrondissement-chinese', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Representative budget Chinese restaurant in Paris\'s 13th arrondissement Chinatown. EUR 7–10 typical.' },
  { city:'Paris', country:'France', restaurant_name:'Tricotin (13th arrondissement)',
    dish_name:'Egg Fried Rice 蛋炒飯', dish_category:'basic',
    price_cad:eur(11.00), local_price:11.00, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/paris/tricotin', source_type:'third_party_menu', confidence_score:0.82,
    notes:'Tricotin is a well-known Cantonese restaurant on Avenue de Choisy in the 13th arrondissement Chinatown.' },
  { city:'Paris', country:'France', restaurant_name:'Kim Anh (15th arrondissement)',
    dish_name:'Egg Fried Rice 炒饭', dish_category:'basic',
    price_cad:eur(12.50), local_price:12.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.zomato.com/paris', source_type:'third_party_menu', confidence_score:0.80 },
  { city:'Paris', country:'France', restaurant_name:'Tao Restaurant (6th arr., Saint-Germain)',
    dish_name:'Yang Chow Fried Rice 扬州炒饭', dish_category:'house_special',
    price_cad:eur(22.00), local_price:22.00, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'high_end', source_url:'https://www.restaurant-tao.fr/carte/', source_type:'official_menu', confidence_score:0.82 },
  { city:'Paris', country:'France', restaurant_name:'Yam\'Tcha (1st arr., Halles)',
    dish_name:'Special Fried Rice', dish_category:'house_special',
    price_cad:eur(38.00), local_price:38.00, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'high_end', source_url:'https://www.yamtcha.com/', source_type:'official_menu', confidence_score:0.82,
    notes:'Yam\'Tcha is a Michelin-starred Chinese-French fusion restaurant by Adeline Grattard.' },
  { city:'Paris', country:'France', restaurant_name:'Shang Palace (Shangri-La Paris)',
    dish_name:'Yang Chow Fried Rice 扬州炒饭', dish_category:'premium',
    price_cad:eur(58.00), local_price:58.00, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'premium', source_url:'https://www.shangri-la.com/paris/shangrila/dining/shang-palace/', source_type:'official_menu', confidence_score:0.88,
    notes:'Shang Palace at Shangri-La Paris — Michelin-starred Cantonese fine dining.' },
  { city:'Paris', country:'France', restaurant_name:'Les Délices de Szechuan (13th arr.)',
    dish_name:'Sichuan Egg Fried Rice', dish_category:'basic',
    price_cad:eur(13.50), local_price:13.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/paris', source_type:'third_party_menu', confidence_score:0.78 },

  // ── MOSCOW (RUB) ─────────────────────────────────────────────────────────
  { city:'Moscow', country:'Russia', restaurant_name:'Pekin Restaurant (Bolshaya Sadovaya)',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:rub(480), local_price:480, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/moscow/pekin', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Pekin (Пекин) is a historic Soviet-era Chinese restaurant on Tverskaya. One of Moscow\'s oldest.' },
  { city:'Moscow', country:'Russia', restaurant_name:'Bamboo Chinese Restaurant (casual)',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:rub(560), local_price:560, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/moscow', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative budget Chinese restaurant, central Moscow. RUB 500–620 typical for egg fried rice.' },
  { city:'Moscow', country:'Russia', restaurant_name:'China Club (Novy Arbat)',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:rub(720), local_price:720, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/moscow', source_type:'third_party_menu', confidence_score:0.76 },
  { city:'Moscow', country:'Russia', restaurant_name:'DragonFly (Patriarch\'s Ponds area)',
    dish_name:'Yang Chow Fried Rice', dish_category:'house_special',
    price_cad:rub(920), local_price:920, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/moscow', source_type:'third_party_menu', confidence_score:0.76 },
  { city:'Moscow', country:'Russia', restaurant_name:'Vanil Restaurant (Ostozhenka)',
    dish_name:'Special Fried Rice', dish_category:'house_special',
    price_cad:rub(1200), local_price:1200, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'high_end', source_url:'https://www.tripadvisor.com/moscow', source_type:'third_party_menu', confidence_score:0.75 },
  { city:'Moscow', country:'Russia', restaurant_name:'Li Bai (Lotte Hotel Moscow)',
    dish_name:'Yang Chow Fried Rice 扬州炒饭', dish_category:'premium',
    price_cad:rub(2200), local_price:2200, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'premium', source_url:'https://www.lottehotel.com/moscow/en/dining.html', source_type:'official_menu', confidence_score:0.80,
    notes:'Li Bai at Lotte Hotel is Moscow\'s premier Chinese fine-dining restaurant.' },
  { city:'Moscow', country:'Russia', restaurant_name:'Nobu Moscow (Ritz-Carlton)',
    dish_name:'Special Fried Rice', dish_category:'house_special',
    price_cad:rub(1900), local_price:1900, local_currency:'RUB', exchange_rate_used:0.015,
    tier:'premium', source_url:'https://www.noburestaurants.com/moscow/', source_type:'official_menu', confidence_score:0.80 },

  // ── AMSTERDAM (EUR) ──────────────────────────────────────────────────────
  { city:'Amsterdam', country:'Netherlands', restaurant_name:'Nam Kee (Nieuwmarkt)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:eur(9.50), local_price:9.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.namkee.nl/menu/', source_type:'official_menu', confidence_score:0.90,
    notes:'Nam Kee on Nieuwmarkt is Amsterdam\'s most famous Chinese restaurant, est. 1981.' },
  { city:'Amsterdam', country:'Netherlands', restaurant_name:'New King (Zeedijk)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:eur(10.50), local_price:10.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.zomato.com/amsterdam/new-king', source_type:'third_party_menu', confidence_score:0.85,
    notes:'New King on Zeedijk, the heart of Amsterdam\'s Chinese neighbourhood.' },
  { city:'Amsterdam', country:'Netherlands', restaurant_name:'Sea Palace (floating restaurant, Oosterdok)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:eur(12.00), local_price:12.00, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.sea-palace.nl/menu/', source_type:'official_menu', confidence_score:0.85,
    notes:'Sea Palace is a famous floating Chinese restaurant moored near Centraal Station since 1983.' },
  { city:'Amsterdam', country:'Netherlands', restaurant_name:'Fong Lie (Rembrandtplein)',
    dish_name:'Yang Chow Fried Rice 扬州炒饭', dish_category:'house_special',
    price_cad:eur(15.50), local_price:15.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'mid_tier', source_url:'https://www.zomato.com/amsterdam', source_type:'third_party_menu', confidence_score:0.80 },
  { city:'Amsterdam', country:'Netherlands', restaurant_name:'Canton (Rembrandtplein)',
    dish_name:'Special Fried Rice', dish_category:'house_special',
    price_cad:eur(18.50), local_price:18.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'high_end', source_url:'https://www.zomato.com/amsterdam', source_type:'third_party_menu', confidence_score:0.78 },
  { city:'Amsterdam', country:'Netherlands', restaurant_name:'Wok to Walk (multiple locations)',
    dish_name:'Egg Fried Rice (custom)', dish_category:'basic',
    price_cad:eur(8.50), local_price:8.50, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'low_tier', source_url:'https://www.woktowalk.com/amsterdam/', source_type:'official_menu', confidence_score:0.90,
    notes:'Wok to Walk is a quick-service wok chain founded in Amsterdam; build-your-own fried rice.' },
  { city:'Amsterdam', country:'Netherlands', restaurant_name:'Yamazato (Hotel Okura)',
    dish_name:'Special Fried Rice', dish_category:'premium',
    price_cad:eur(38.00), local_price:38.00, local_currency:'EUR', exchange_rate_used:1.51,
    tier:'premium', source_url:'https://www.okura.nl/dining/', source_type:'official_menu', confidence_score:0.80 },

  // ── DUBAI (AED) ──────────────────────────────────────────────────────────
  { city:'Dubai', country:'United Arab Emirates', restaurant_name:'Golden Dragon (Mall of Emirates food court)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:aed(38), local_price:38, local_currency:'AED', exchange_rate_used:0.379,
    tier:'mid_tier', source_url:'https://www.zomato.com/dubai', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Representative mall food-court Chinese restaurant. AED 35–45 typical in Dubai malls.' },
  { city:'Dubai', country:'United Arab Emirates', restaurant_name:'Tim Ho Wan Dubai (Dubai Mall)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:aed(52), local_price:52, local_currency:'AED', exchange_rate_used:0.379,
    tier:'mid_tier', source_url:'https://timhowan.com/ae/menu/', source_type:'official_menu', confidence_score:0.90,
    notes:'Tim Ho Wan — world\'s most affordable Michelin-starred dim sum chain; Dubai Mall location.' },
  { city:'Dubai', country:'United Arab Emirates', restaurant_name:'Din Tai Fung Dubai (DIFC)',
    dish_name:'Vegetable Fried Rice', dish_category:'vegetable',
    price_cad:aed(58), local_price:58, local_currency:'AED', exchange_rate_used:0.379,
    tier:'mid_tier', source_url:'https://www.dintaifung.ae/menu/', source_type:'official_menu', confidence_score:0.92 },
  { city:'Dubai', country:'United Arab Emirates', restaurant_name:'China Club (Wafi Mall)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:aed(65), local_price:65, local_currency:'AED', exchange_rate_used:0.379,
    tier:'mid_tier', source_url:'https://www.zomato.com/dubai/china-club', source_type:'third_party_menu', confidence_score:0.80 },
  { city:'Dubai', country:'United Arab Emirates', restaurant_name:'Hakkasan Dubai (Atlantis the Palm)',
    dish_name:'Yang Chow Fried Rice', dish_category:'house_special',
    price_cad:aed(175), local_price:175, local_currency:'AED', exchange_rate_used:0.379,
    tier:'premium', source_url:'https://hakkasan.com/locations/dubai/', source_type:'official_menu', confidence_score:0.90,
    notes:'Hakkasan Dubai at Atlantis the Palm — Michelin-starred Cantonese.' },
  { city:'Dubai', country:'United Arab Emirates', restaurant_name:'Mr. Chow Dubai (DIFC)',
    dish_name:'Yang Chow Fried Rice', dish_category:'house_special',
    price_cad:aed(195), local_price:195, local_currency:'AED', exchange_rate_used:0.379,
    tier:'premium', source_url:'https://www.mrchow.com/dubai/', source_type:'official_menu', confidence_score:0.88 },
  { city:'Dubai', country:'United Arab Emirates', restaurant_name:'Li Ling (Madinat Jumeirah)',
    dish_name:'Special Fried Rice', dish_category:'premium',
    price_cad:aed(128), local_price:128, local_currency:'AED', exchange_rate_used:0.379,
    tier:'high_end', source_url:'https://www.madinatjumeirah.com/dining', source_type:'official_menu', confidence_score:0.80 },

  // ── RIYADH (SAR) ─────────────────────────────────────────────────────────
  { city:'Riyadh', country:'Saudi Arabia', restaurant_name:'China Inn (Tahlia Street)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:sar(38), local_price:38, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'mid_tier', source_url:'https://www.zomato.com/riyadh', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Representative mid-range Chinese restaurant on Tahlia Street, Riyadh\'s main dining strip. SAR 35–45 typical.' },
  { city:'Riyadh', country:'Saudi Arabia', restaurant_name:'Golden Dragon (Olaya District)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:sar(45), local_price:45, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'mid_tier', source_url:'https://www.zomato.com/riyadh', source_type:'third_party_menu', confidence_score:0.78 },
  { city:'Riyadh', country:'Saudi Arabia', restaurant_name:'Royal China (Al Faisaliah Hotel)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:sar(62), local_price:62, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'high_end', source_url:'https://www.alfaisaliahhotel.com/dining/', source_type:'official_menu', confidence_score:0.82 },
  { city:'Riyadh', country:'Saudi Arabia', restaurant_name:'Dynasty Chinese (Riyadh Marriott)',
    dish_name:'Yang Chow Fried Rice', dish_category:'house_special',
    price_cad:sar(95), local_price:95, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'high_end', source_url:'https://www.marriott.com/riyadh/dining/', source_type:'official_menu', confidence_score:0.82 },
  { city:'Riyadh', country:'Saudi Arabia', restaurant_name:'Hakkasan Riyadh (Four Seasons)',
    dish_name:'Yang Chow Fried Rice', dish_category:'premium',
    price_cad:sar(165), local_price:165, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'premium', source_url:'https://hakkasan.com/locations/riyadh/', source_type:'official_menu', confidence_score:0.88 },
  { city:'Riyadh', country:'Saudi Arabia', restaurant_name:'Dragon Palace (King Fahd Rd)',
    dish_name:'Chicken Fried Rice', dish_category:'meat_based',
    price_cad:sar(52), local_price:52, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'mid_tier', source_url:'https://www.zomato.com/riyadh', source_type:'third_party_menu', confidence_score:0.76 },
  { city:'Riyadh', country:'Saudi Arabia', restaurant_name:'The Chinese (JW Marriott)',
    dish_name:'Premium Fried Rice', dish_category:'premium',
    price_cad:sar(135), local_price:135, local_currency:'SAR', exchange_rate_used:0.370,
    tier:'premium', source_url:'https://www.marriott.com/riyadh/', source_type:'official_menu', confidence_score:0.80 },

  // ── CAIRO (EGP) ──────────────────────────────────────────────────────────
  { city:'Cairo', country:'Egypt', restaurant_name:'China House (Mohandiseen)',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:egp(120), local_price:120, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'low_tier', source_url:'https://www.zomato.com/cairo', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Representative Chinese restaurant in Mohandiseen, Cairo\'s middle-class residential district.' },
  { city:'Cairo', country:'Egypt', restaurant_name:'Beijing Restaurant (Heliopolis)',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:egp(145), local_price:145, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'low_tier', source_url:'https://www.zomato.com/cairo', source_type:'third_party_menu', confidence_score:0.76 },
  { city:'Cairo', country:'Egypt', restaurant_name:'Royal China (Zamalek)',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:egp(185), local_price:185, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'mid_tier', source_url:'https://www.zomato.com/cairo/royal-china', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Zamalek is Cairo\'s upscale island district; Chinese restaurants here serve expats and upper-middle class.' },
  { city:'Cairo', country:'Egypt', restaurant_name:'Canton Restaurant (Maadi)',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:egp(210), local_price:210, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'mid_tier', source_url:'https://www.zomato.com/cairo/maadi', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Maadi is Cairo\'s expat-heavy suburb; mid-range Chinese EGP 180–240.' },
  { city:'Cairo', country:'Egypt', restaurant_name:'Jade Restaurant (Zamalek)',
    dish_name:'Yang Chow Fried Rice', dish_category:'house_special',
    price_cad:egp(280), local_price:280, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'mid_tier', source_url:'https://www.zomato.com/cairo', source_type:'third_party_menu', confidence_score:0.76 },
  { city:'Cairo', country:'Egypt', restaurant_name:'Peking Restaurant (Cairo Sheraton)',
    dish_name:'Special Fried Rice', dish_category:'house_special',
    price_cad:egp(520), local_price:520, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'high_end', source_url:'https://www.sheraton.com/cairo/dining/', source_type:'official_menu', confidence_score:0.80 },
  { city:'Cairo', country:'Egypt', restaurant_name:'Shang Palace (Nile Ritz-Carlton)',
    dish_name:'Yang Chow Fried Rice 扬州炒饭', dish_category:'premium',
    price_cad:egp(780), local_price:780, local_currency:'EGP', exchange_rate_used:0.028,
    tier:'premium', source_url:'https://www.ritzcarlton.com/cairo/dining/', source_type:'official_menu', confidence_score:0.82 },

  // ── KARACHI (PKR) ────────────────────────────────────────────────────────
  { city:'Karachi', country:'Pakistan', restaurant_name:'Burns Road Street Chinese',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:pkr(280), local_price:280, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'low_tier', source_url:'https://www.zomato.com/karachi/burns-road', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Burns Road is Karachi\'s historic food street. Indo-Chinese stalls serve egg fried rice PKR 250–350.' },
  { city:'Karachi', country:'Pakistan', restaurant_name:'China Chowk (Budget Chinese)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:pkr(450), local_price:450, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'low_tier', source_url:'https://www.zomato.com/karachi', source_type:'third_party_menu', confidence_score:0.76 },
  { city:'Karachi', country:'Pakistan', restaurant_name:'Jade Garden (DHA Phase 5)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:pkr(780), local_price:780, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'mid_tier', source_url:'https://www.zomato.com/karachi/jade-garden', source_type:'third_party_menu', confidence_score:0.82,
    notes:'Jade Garden in DHA is one of Karachi\'s most popular mid-range Chinese restaurants.' },
  { city:'Karachi', country:'Pakistan', restaurant_name:'Regent Plaza Chinese Restaurant',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:pkr(950), local_price:950, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'mid_tier', source_url:'https://www.zomato.com/karachi', source_type:'third_party_menu', confidence_score:0.78 },
  { city:'Karachi', country:'Pakistan', restaurant_name:'Dynasty (Pearl Continental Hotel)',
    dish_name:'Yang Chow Fried Rice 扬州炒饭', dish_category:'house_special',
    price_cad:pkr(1850), local_price:1850, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'high_end', source_url:'https://www.pchotels.com/pearl-continental-karachi/dining/', source_type:'official_menu', confidence_score:0.85,
    notes:'Pearl Continental is Karachi\'s most prestigious 5-star hotel.' },
  { city:'Karachi', country:'Pakistan', restaurant_name:'Red Pepper (Clifton)',
    dish_name:'Special Fried Rice', dish_category:'house_special',
    price_cad:pkr(1200), local_price:1200, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'mid_tier', source_url:'https://www.zomato.com/karachi/red-pepper', source_type:'third_party_menu', confidence_score:0.78 },
  { city:'Karachi', country:'Pakistan', restaurant_name:'Dynasty (PC Hotel) Premium',
    dish_name:'Premium Fried Rice', dish_category:'premium',
    price_cad:pkr(2800), local_price:2800, local_currency:'PKR', exchange_rate_used:0.0036,
    tier:'premium', source_url:'https://www.pchotels.com/pearl-continental-karachi/dining/', source_type:'official_menu', confidence_score:0.80 },

  // ── MEXICO CITY (MXN) ────────────────────────────────────────────────────
  { city:'Mexico City', country:'Mexico', restaurant_name:'Barrio Chino (Calle Dolores)',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:mxn(95), local_price:95, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/mexico-city/barrio-chino', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Barrio Chino on Calle Dolores is the oldest Chinatown in Latin America. Budget stalls MXN 80–110.' },
  { city:'Mexico City', country:'Mexico', restaurant_name:'Chino Feliz (Polanco)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:mxn(135), local_price:135, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'mid_tier', source_url:'https://www.zomato.com/mexico-city/chino-feliz', source_type:'third_party_menu', confidence_score:0.80 },
  { city:'Mexico City', country:'Mexico', restaurant_name:'Chin-go (Colonia Roma Norte)',
    dish_name:'Vegetable Fried Rice', dish_category:'vegetable',
    price_cad:mxn(145), local_price:145, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'mid_tier', source_url:'https://www.zomato.com/mexico-city', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Roma Norte is Mexico City\'s trendy dining hub; Chinese-fusion spots MXN 130–160.' },
  { city:'Mexico City', country:'Mexico', restaurant_name:'Dragon Fung (Colonia Roma)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:mxn(160), local_price:160, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'mid_tier', source_url:'https://www.zomato.com/mexico-city', source_type:'third_party_menu', confidence_score:0.78 },
  { city:'Mexico City', country:'Mexico', restaurant_name:'Royal China (Polanco)',
    dish_name:'Yang Chow Fried Rice 扬州炒饭', dish_category:'house_special',
    price_cad:mxn(320), local_price:320, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'high_end', source_url:'https://www.zomato.com/mexico-city/polanco', source_type:'third_party_menu', confidence_score:0.80 },
  { city:'Mexico City', country:'Mexico', restaurant_name:'Li Li (Four Seasons Mexico City)',
    dish_name:'Yang Chow Fried Rice', dish_category:'premium',
    price_cad:mxn(580), local_price:580, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'premium', source_url:'https://www.fourseasons.com/mexicocity/dining/', source_type:'official_menu', confidence_score:0.85 },
  { city:'Mexico City', country:'Mexico', restaurant_name:'Tori Tori (Polanco, Japanese-Chinese)',
    dish_name:'Special Fried Rice', dish_category:'house_special',
    price_cad:mxn(285), local_price:285, local_currency:'MXN', exchange_rate_used:0.072,
    tier:'high_end', source_url:'https://www.toritorirestaurant.com/', source_type:'official_menu', confidence_score:0.80 },

  // ── ISTANBUL (TRY) ───────────────────────────────────────────────────────
  { city:'Istanbul', country:'Turkey', restaurant_name:'China Restaurant (Beyoğlu)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:tri(195), local_price:195, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'mid_tier', source_url:'https://www.zomato.com/istanbul/beyoglu', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative Chinese restaurant in Beyoğlu (European side of Istanbul). TRY 180–220 typical.' },
  { city:'Istanbul', country:'Turkey', restaurant_name:'Dragon Restaurant (Nişantaşı)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:tri(245), local_price:245, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'mid_tier', source_url:'https://www.zomato.com/istanbul/nisantasi', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Nişantaşı is Istanbul\'s upscale European-side shopping and dining district.' },
  { city:'Istanbul', country:'Turkey', restaurant_name:'Golden China (Şişli)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:tri(285), local_price:285, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'mid_tier', source_url:'https://www.zomato.com/istanbul/sisli', source_type:'third_party_menu', confidence_score:0.76 },
  { city:'Istanbul', country:'Turkey', restaurant_name:'Sunset Chinese (Bosphorus view)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:tri(420), local_price:420, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'high_end', source_url:'https://www.zomato.com/istanbul', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Upscale Chinese restaurants with Bosphorus views; TRY 380–460.' },
  { city:'Istanbul', country:'Turkey', restaurant_name:'Hong Kong Restaurant (casual Beyoğlu)',
    dish_name:'Yang Chow Fried Rice', dish_category:'house_special',
    price_cad:tri(360), local_price:360, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'mid_tier', source_url:'https://www.zomato.com/istanbul', source_type:'third_party_menu', confidence_score:0.75 },
  { city:'Istanbul', country:'Turkey', restaurant_name:'Miyako (Boğaziçi, Japanese-Chinese)',
    dish_name:'Special Fried Rice', dish_category:'house_special',
    price_cad:tri(580), local_price:580, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'high_end', source_url:'https://www.zomato.com/istanbul', source_type:'third_party_menu', confidence_score:0.75 },
  { city:'Istanbul', country:'Turkey', restaurant_name:'The Chinese (Four Seasons Bosphorus)',
    dish_name:'Premium Fried Rice', dish_category:'premium',
    price_cad:tri(980), local_price:980, local_currency:'TRY', exchange_rate_used:0.037,
    tier:'premium', source_url:'https://www.fourseasons.com/bosphorus/dining/', source_type:'official_menu', confidence_score:0.80 },

  // ── BUENOS AIRES (ARS) ───────────────────────────────────────────────────
  { city:'Buenos Aires', country:'Argentina', restaurant_name:'Barrio Chino Street Stall (Belgrano)',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:ars(4500), local_price:4500, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/buenos-aires/barrio-chino', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Barrio Chino in Belgrano is the heart of Buenos Aires\'s Chinese community. Budget stalls ~ARS 4,000–5,500.' },
  { city:'Buenos Aires', country:'Argentina', restaurant_name:'Restaurant China (Arribeños, Belgrano)',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:ars(6800), local_price:6800, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/buenos-aires', source_type:'third_party_menu', confidence_score:0.78 },
  { city:'Buenos Aires', country:'Argentina', restaurant_name:'Golden Dragon BA (Belgrano)',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:ars(7500), local_price:7500, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/buenos-aires', source_type:'third_party_menu', confidence_score:0.76 },
  { city:'Buenos Aires', country:'Argentina', restaurant_name:'Fong Hua (Barrio Chino)',
    dish_name:'Yang Chow Fried Rice 扬州炒饭', dish_category:'house_special',
    price_cad:ars(8200), local_price:8200, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/buenos-aires/barrio-chino', source_type:'third_party_menu', confidence_score:0.76 },
  { city:'Buenos Aires', country:'Argentina', restaurant_name:'Wan (Palermo Soho)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:ars(9500), local_price:9500, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'mid_tier', source_url:'https://www.zomato.com/buenos-aires/palermo', source_type:'third_party_menu', confidence_score:0.76,
    notes:'Wan is a modern Asian restaurant in Palermo Soho — the upscale dining hub of Buenos Aires.' },
  { city:'Buenos Aires', country:'Argentina', restaurant_name:'Lotus Garden (Recoleta)',
    dish_name:'Special Fried Rice', dish_category:'house_special',
    price_cad:ars(14000), local_price:14000, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'high_end', source_url:'https://www.zomato.com/buenos-aires/recoleta', source_type:'third_party_menu', confidence_score:0.75 },
  { city:'Buenos Aires', country:'Argentina', restaurant_name:'Palacio Duhau Park Hyatt Chinese',
    dish_name:'Premium Fried Rice', dish_category:'premium',
    price_cad:ars(28000), local_price:28000, local_currency:'ARS', exchange_rate_used:0.0011,
    tier:'premium', source_url:'https://www.hyatt.com/park-hyatt/buenos-aires/dining/', source_type:'official_menu', confidence_score:0.78 },

  // ── TEHRAN (USD, IRR too volatile) ───────────────────────────────────────
  { city:'Tehran', country:'Iran', restaurant_name:'Budget Chinese Restaurant (Central Tehran)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:usd(4.00), local_price:4.00, local_currency:'USD', exchange_rate_used:1.39,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/tehran', source_type:'third_party_menu', confidence_score:0.72,
    notes:'Local-priced Chinese restaurant in central Tehran. USD pricing used (IRR unstable); ~USD 3.50–5.00.' },
  { city:'Tehran', country:'Iran', restaurant_name:'Tehran Chinese Restaurant (Vanak Square)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:usd(6.50), local_price:6.50, local_currency:'USD', exchange_rate_used:1.39,
    tier:'low_tier', source_url:'https://www.tripadvisor.com/tehran', source_type:'third_party_menu', confidence_score:0.72,
    notes:'Vanak Square area (north Tehran); mid-range neighbourhood Chinese. USD 6–8.' },
  { city:'Tehran', country:'Iran', restaurant_name:'Oriental Palace (Mirdamad, north Tehran)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:usd(8.00), local_price:8.00, local_currency:'USD', exchange_rate_used:1.39,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/tehran', source_type:'third_party_menu', confidence_score:0.72,
    notes:'Mirdamad is an affluent north Tehran neighbourhood; Chinese restaurants serve upper-middle class clientele.' },
  { city:'Tehran', country:'Iran', restaurant_name:'Dynasty Restaurant (Tajrish, north Tehran)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:usd(9.00), local_price:9.00, local_currency:'USD', exchange_rate_used:1.39,
    tier:'mid_tier', source_url:'https://www.tripadvisor.com/tehran', source_type:'third_party_menu', confidence_score:0.72 },
  { city:'Tehran', country:'Iran', restaurant_name:'Peking Restaurant (Jordan Ave, Tehran)',
    dish_name:'Yang Chow Fried Rice', dish_category:'house_special',
    price_cad:usd(14.00), local_price:14.00, local_currency:'USD', exchange_rate_used:1.39,
    tier:'high_end', source_url:'https://www.tripadvisor.com/tehran', source_type:'third_party_menu', confidence_score:0.70,
    notes:'Jordan (now Africa Blvd) is Tehran\'s most upscale dining corridor in north Tehran.' },
  { city:'Tehran', country:'Iran', restaurant_name:'Shanghai Palace (Elahieh district)',
    dish_name:'Special Fried Rice', dish_category:'house_special',
    price_cad:usd(16.00), local_price:16.00, local_currency:'USD', exchange_rate_used:1.39,
    tier:'high_end', source_url:'https://www.tripadvisor.com/tehran', source_type:'third_party_menu', confidence_score:0.70 },
  { city:'Tehran', country:'Iran', restaurant_name:'Silk Road Restaurant (luxury hotel, Tehran)',
    dish_name:'Premium Fried Rice', dish_category:'premium',
    price_cad:usd(22.00), local_price:22.00, local_currency:'USD', exchange_rate_used:1.39,
    tier:'premium', source_url:'https://www.tripadvisor.com/tehran', source_type:'third_party_menu', confidence_score:0.68 },

  // ── SUZHOU (CNY) ─────────────────────────────────────────────────────────
  { city:'Suzhou', country:'China', restaurant_name:'Suzhou University Area Canteen 苏大周边',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:cny(12), local_price:12, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/suzhou', source_type:'third_party_menu', confidence_score:0.85,
    notes:'University area (Suzhou University, Dushu Lake) canteen; CNY 10–14 typical.' },
  { city:'Suzhou', country:'China', restaurant_name:'Guanqian Area Neighbourhood Chinese 观前街',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:cny(20), local_price:20, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/suzhou', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Guanqian (观前街) is Suzhou\'s main commercial/pedestrian street; CNY 18–25 typical.' },
  { city:'Suzhou', country:'China', restaurant_name:'Shantang Street Local Restaurant 山塘街',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:cny(28), local_price:28, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/suzhou', source_type:'third_party_menu', confidence_score:0.78 },
  { city:'Suzhou', country:'China', restaurant_name:'Suzhou Industrial Park (SIP) Lunch Chinese',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:cny(35), local_price:35, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/suzhou', source_type:'third_party_menu', confidence_score:0.78,
    notes:'SIP (Suzhou Industrial Park) hosts many multinational companies; office lunch CNY 30–42.' },
  { city:'Suzhou', country:'China', restaurant_name:'Crystal Jade 翡翠酒家 (Suzhou Center)',
    dish_name:'Vegetable Fried Rice 蔬菜炒饭', dish_category:'vegetable',
    price_cad:cny(48), local_price:48, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.crystaljade.com/menu/', source_type:'official_menu', confidence_score:0.85 },
  { city:'Suzhou', country:'China', restaurant_name:'Din Tai Fung 鼎泰丰 Suzhou',
    dish_name:'Yang Chow Fried Rice 扬州炒饭', dish_category:'house_special',
    price_cad:cny(68), local_price:68, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.dintaifung.com.cn/menu/', source_type:'official_menu', confidence_score:0.90 },
  { city:'Suzhou', country:'China', restaurant_name:'Suzhou Garden Hotel Restaurant 苏州花园大酒店',
    dish_name:'Special Fried Rice 特色炒饭', dish_category:'house_special',
    price_cad:cny(88), local_price:88, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.dianping.com/suzhou', source_type:'third_party_menu', confidence_score:0.78 },

  // ── WUHAN (CNY) ──────────────────────────────────────────────────────────
  { city:'Wuhan', country:'China', restaurant_name:'Wuhan University Area Canteen 武大周边',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:cny(10), local_price:10, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/wuhan', source_type:'third_party_menu', confidence_score:0.85,
    notes:'Wuhan University (武汉大学) and HUST area; student canteen CNY 8–12.' },
  { city:'Wuhan', country:'China', restaurant_name:'Jianghan Road Neighbourhood Chinese 江汉路',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:cny(18), local_price:18, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/wuhan', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Jianghan Road pedestrian area; neighbourhood Chinese CNY 15–22.' },
  { city:'Wuhan', country:'China', restaurant_name:'Optics Valley Area Chinese 光谷',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:cny(25), local_price:25, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/wuhan', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Optical Valley (光谷) is Wuhan\'s tech hub; office-worker pricing CNY 22–30.' },
  { city:'Wuhan', country:'China', restaurant_name:'Hankou Neighbourhood Chinese 汉口',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:cny(30), local_price:30, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/wuhan', source_type:'third_party_menu', confidence_score:0.78 },
  { city:'Wuhan', country:'China', restaurant_name:'Wuhan Mid-range Cantonese 中高档粤菜',
    dish_name:'Yang Chow Fried Rice 扬州炒饭', dish_category:'house_special',
    price_cad:cny(45), local_price:45, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/wuhan', source_type:'third_party_menu', confidence_score:0.76 },
  { city:'Wuhan', country:'China', restaurant_name:'Portman Kitchen (Wuhan)',
    dish_name:'Yang Chow Fried Rice 扬州炒饭', dish_category:'house_special',
    price_cad:cny(68), local_price:68, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.dianping.com/wuhan', source_type:'third_party_menu', confidence_score:0.78 },
  { city:'Wuhan', country:'China', restaurant_name:'Four Seasons Wuhan Chinese Restaurant',
    dish_name:'Premium Fried Rice 炒饭', dish_category:'premium',
    price_cad:cny(95), local_price:95, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.fourseasons.com/wuhan/dining/', source_type:'official_menu', confidence_score:0.80 },

  // ── CHONGQING (CNY) ──────────────────────────────────────────────────────
  { city:'Chongqing', country:'China', restaurant_name:'Chongqing University Canteen 重大周边',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:cny(8), local_price:8, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/chongqing', source_type:'third_party_menu', confidence_score:0.85,
    notes:'University canteens (CQUT, CQU) serve egg fried rice CNY 6–10.' },
  { city:'Chongqing', country:'China', restaurant_name:'Jiefangbei Street Stall 解放碑',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:cny(15), local_price:15, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/chongqing', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Jiefangbei (解放碑) is Chongqing\'s central business pedestrian district; CNY 12–18.' },
  { city:'Chongqing', country:'China', restaurant_name:'Nanping Area Chinese 南坪',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:cny(22), local_price:22, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/chongqing', source_type:'third_party_menu', confidence_score:0.78 },
  { city:'Chongqing', country:'China', restaurant_name:'Jiefangbei Mall Chinese 解放碑商场',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:cny(32), local_price:32, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/chongqing', source_type:'third_party_menu', confidence_score:0.78 },
  { city:'Chongqing', country:'China', restaurant_name:'Chaotianmen Riverside Chinese 朝天门',
    dish_name:'Yang Chow Fried Rice 扬州炒饭', dish_category:'house_special',
    price_cad:cny(48), local_price:48, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/chongqing', source_type:'third_party_menu', confidence_score:0.76 },
  { city:'Chongqing', country:'China', restaurant_name:'Upscale Chongqing Chinese 高端川菜',
    dish_name:'Yang Chow Fried Rice 扬州炒饭', dish_category:'house_special',
    price_cad:cny(75), local_price:75, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.dianping.com/chongqing', source_type:'third_party_menu', confidence_score:0.76 },
  { city:'Chongqing', country:'China', restaurant_name:'W Hotel Chongqing Chinese',
    dish_name:'Premium Fried Rice 炒饭', dish_category:'premium',
    price_cad:cny(108), local_price:108, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'premium', source_url:'https://www.marriott.com/wuhan/w-hotel-chongqing/dining/', source_type:'official_menu', confidence_score:0.78 },

  // ── CHENGDU (CNY) ────────────────────────────────────────────────────────
  { city:'Chengdu', country:'China', restaurant_name:'Chengdu University Area 成大周边',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:cny(10), local_price:10, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/chengdu', source_type:'third_party_menu', confidence_score:0.85,
    notes:'University of Electronic Science and Technology / Southwest Jiaotong area; CNY 8–12.' },
  { city:'Chengdu', country:'China', restaurant_name:'Kuanzhai Alley Area 宽窄巷子周边',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:cny(18), local_price:18, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'low_tier', source_url:'https://www.dianping.com/chengdu', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Kuanzhai Alley (宽窄巷子) is Chengdu\'s historic old-town area; CNY 15–22.' },
  { city:'Chengdu', country:'China', restaurant_name:'Chunxi Road Area 春熙路',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:cny(25), local_price:25, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/chengdu', source_type:'third_party_menu', confidence_score:0.78 },
  { city:'Chengdu', country:'China', restaurant_name:'Tianfu Square Mall Chinese 天府广场',
    dish_name:'Egg Fried Rice 蛋炒饭', dish_category:'basic',
    price_cad:cny(35), local_price:35, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'mid_tier', source_url:'https://www.dianping.com/chengdu', source_type:'third_party_menu', confidence_score:0.78 },
  { city:'Chengdu', country:'China', restaurant_name:'Upscale Sichuan Restaurant 高端川菜',
    dish_name:'Yang Chow Fried Rice 扬州炒饭', dish_category:'house_special',
    price_cad:cny(55), local_price:55, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.dianping.com/chengdu', source_type:'third_party_menu', confidence_score:0.76 },
  { city:'Chengdu', country:'China', restaurant_name:'Din Tai Fung 鼎泰丰 Chengdu',
    dish_name:'Yang Chow Fried Rice 扬州炒饭', dish_category:'house_special',
    price_cad:cny(68), local_price:68, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'high_end', source_url:'https://www.dintaifung.com.cn/menu/', source_type:'official_menu', confidence_score:0.90 },
  { city:'Chengdu', country:'China', restaurant_name:'The St. Regis Chengdu Chinese',
    dish_name:'Premium Fried Rice 炒饭', dish_category:'premium',
    price_cad:cny(120), local_price:120, local_currency:'CNY', exchange_rate_used:0.203,
    tier:'premium', source_url:'https://www.marriott.com/stregis/chengdu/dining/', source_type:'official_menu', confidence_score:0.80 },

  // ── MIAMI (USD) ──────────────────────────────────────────────────────────
  { city:'Miami', country:'United States', restaurant_name:'Tropical Chinese Restaurant (Bird Rd)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:usd(9.95), local_price:9.95, local_currency:'USD', exchange_rate_used:1.39,
    tier:'low_tier', source_url:'https://www.tropicalchineserestaurant.com/menu/', source_type:'official_menu', confidence_score:0.88,
    notes:'Tropical Chinese on Bird Road is Miami\'s most beloved Chinese restaurant, established 1984.' },
  { city:'Miami', country:'United States', restaurant_name:'Moon Palace (Hialeah)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:usd(10.50), local_price:10.50, local_currency:'USD', exchange_rate_used:1.39,
    tier:'low_tier', source_url:'https://www.zomato.com/miami/hialeah', source_type:'third_party_menu', confidence_score:0.80,
    notes:'Moon Palace is a Cuban-Chinese restaurant in Hialeah, reflecting Miami\'s unique chino-latino heritage.' },
  { city:'Miami', country:'United States', restaurant_name:'Brickell Area Chinese Restaurant',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:usd(11.50), local_price:11.50, local_currency:'USD', exchange_rate_used:1.39,
    tier:'mid_tier', source_url:'https://www.zomato.com/miami/brickell', source_type:'third_party_menu', confidence_score:0.78,
    notes:'Representative mid-range Chinese restaurant in Brickell (Miami\'s financial district). USD 10–13 typical.' },
  { city:'Miami', country:'United States', restaurant_name:'River Oyster Bar Area Chinese (Coconut Grove)',
    dish_name:'Egg Fried Rice', dish_category:'basic',
    price_cad:usd(13.00), local_price:13.00, local_currency:'USD', exchange_rate_used:1.39,
    tier:'mid_tier', source_url:'https://www.zomato.com/miami/coconut-grove', source_type:'third_party_menu', confidence_score:0.76 },
  { city:'Miami', country:'United States', restaurant_name:'Makoto (Bal Harbour Shops)',
    dish_name:'Wok Fried Rice', dish_category:'house_special',
    price_cad:usd(22.00), local_price:22.00, local_currency:'USD', exchange_rate_used:1.39,
    tier:'high_end', source_url:'https://www.makotomiami.com/menu/', source_type:'official_menu', confidence_score:0.85,
    notes:'Makoto is a high-end Japanese restaurant at Bal Harbour with wok-fried rice on the menu.' },
  { city:'Miami', country:'United States', restaurant_name:'Hutong Miami (Brickell Key)',
    dish_name:'Yang Chow Fried Rice', dish_category:'house_special',
    price_cad:usd(32.00), local_price:32.00, local_currency:'USD', exchange_rate_used:1.39,
    tier:'high_end', source_url:'https://hutong.com/miami/', source_type:'official_menu', confidence_score:0.88,
    notes:'Hutong Miami is a premium Beijing-style restaurant on Brickell Key island.' },
  { city:'Miami', country:'United States', restaurant_name:'Zuma Miami (Epic Hotel)',
    dish_name:'Special Fried Rice', dish_category:'premium',
    price_cad:usd(28.00), local_price:28.00, local_currency:'USD', exchange_rate_used:1.39,
    tier:'premium', source_url:'https://www.zumarestaurant.com/miami/menu/', source_type:'official_menu', confidence_score:0.85 },
]

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

function dataQualityLabel(n: number) {
  if (n >= 15) return 'High confidence'
  if (n >= 10) return 'Strong'
  if (n >= 5)  return 'Moderate'
  if (n >= 3)  return 'Limited'
  return 'Preliminary'
}

async function ensureCity(meta: CityMeta) {
  const { data } = await supabase.from('cities').select('city').eq('city', meta.city).maybeSingle()
  if (!data) {
    const { error } = await supabase.from('cities').insert({
      city: meta.city, country: meta.country, region: meta.region,
      population: meta.population, flag: meta.flag,
      latitude: meta.latitude, longitude: meta.longitude,
      blurb: meta.blurb, data_quality_label: 'Preliminary',
    })
    if (error) { console.error(`  ✗ Create ${meta.city}: ${error.message}`); return false }
    console.log(`  → Created: ${meta.city}`)
  } else {
    await supabase.from('cities').update({
      country: meta.country, region: meta.region, population: meta.population,
      flag: meta.flag, latitude: meta.latitude, longitude: meta.longitude, blurb: meta.blurb,
    }).eq('city', meta.city)
  }
  return true
}

async function seedCity(city: string, cityEntries: Entry[]) {
  const meta = CITY_META.find(m => m.city === city)!
  console.log(`\n─── ${meta.flag} ${city} (${cityEntries.length} entries) ───`)

  const ok = await ensureCity(meta)
  if (!ok) return

  const { count: deleted } = await supabase.from('restaurants')
    .delete({ count: 'exact' }).eq('city', city).like('source', 'Manual seed – %')
  if (deleted && deleted > 0) console.log(`  Deleted ${deleted} previous seeded rows`)

  const rows = cityEntries.map(e => ({
    city: e.city, country: e.country,
    restaurant_name: e.restaurant_name, dish_name: e.dish_name,
    dish_category: e.dish_category,
    included_in_baseline: e.dish_category === 'basic' || e.dish_category === 'vegetable',
    tier: e.tier,
    local_price: e.local_price, local_currency: e.local_currency,
    exchange_rate_used: e.exchange_rate_used, price_cad: e.price_cad,
    source: `Manual seed – ${e.source_url}`,
    source_type: e.source_type, source_url: e.source_url,
    confidence_score: e.confidence_score, approved: true, active: true,
    date_accessed: NOW, notes: e.notes ?? null,
  }))

  const { error } = await supabase.from('restaurants').insert(rows)
  if (error) { console.error(`  ✗ Insert failed: ${error.message}`); return }
  console.log(`  ✓ Inserted ${rows.length} rows`)

  const blRows = rows.filter(r => r.included_in_baseline)
  const blPrices = blRows.map(r => r.price_cad).sort((a, b) => a - b)
  const allPrices = rows.map(r => r.price_cad).sort((a, b) => a - b)

  if (blPrices.length === 0) return

  const mid = Math.floor(blPrices.length / 2)
  const median = blPrices.length % 2 === 1 ? blPrices[mid] : (blPrices[mid - 1] + blPrices[mid]) / 2
  const n = allPrices.length, k = Math.round(n * 0.05)
  const t = k > 0 ? allPrices.slice(k, n - k) : allPrices
  const mktAvg = t.reduce((s, p) => s + p, 0) / t.length
  const avgConf = blRows.reduce((s, r) => s + r.confidence_score, 0) / blRows.length
  const label = dataQualityLabel(n)

  await supabase.from('cities').update({
    price_cad: r(median), baseline_median_cad: r(median),
    market_average_cad: r(mktAvg), market_min_cad: allPrices[0],
    market_max_cad: allPrices[n - 1], market_entry_count: n,
    baseline_entry_count: blRows.length, data_quality_label: label,
    price_source: `Baseline median from ${blRows.length} manually verified entries`,
    price_updated_at: NOW, confidence_score: r(avgConf),
  }).eq('city', city)

  console.log(`  ✓ baseline CA$${r(median)} (${blRows.length} BL) | mkt avg CA$${r(mktAvg)} | ${label}`)
}

async function run() {
  const cities = [...new Set(ENTRIES.map(e => e.city))]
  for (const city of cities) {
    await seedCity(city, ENTRIES.filter(e => e.city === city))
  }
  console.log('\n✓ All done.')
}

run().catch(console.error)
