/**
 * Seed script v7 — Massive expansion of all undercovered cities.
 *
 * Cities fully reseeded (delete all manual-seed rows → reinsert):
 *   Tokyo    7 → 21 entries  Osaka     6 → 15  Beijing  7 → 20
 *   Shanghai 7 → 20          Seoul     7 → 15  Singapore 7 → 15
 *   Calgary  9 → 13          Phoenix   7 → 11  Toronto  15 → 20
 *
 * Also demotes Great NY Noodletown "Plain Fried Rice" from baseline:
 *   $18.95 USD plain fried rice is unusual for NYC; reclassified as house_special
 *   to avoid inflating the NYC median.
 *
 * Run with:
 *   export $(grep -v '^#' .env.local | xargs) && npx tsx scripts/seed-update-v7.ts
 */

import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
)

const NOW = new Date().toISOString()

// ── Exchange rate helpers ─────────────────────────────────────────────────────
const USD_TO_CAD = 1.39
const SGD_TO_CAD = 1.08
const JPY_TO_CAD = 0.00869
const CNY_TO_CAD = 0.203
const KRW_TO_CAD = 0.00091

const r  = (n: number) => Math.round(n * 100) / 100
const usd  = (p: number) => r(p * USD_TO_CAD)
const sgd  = (p: number) => r(p * SGD_TO_CAD)
const jpy  = (p: number) => r(p * JPY_TO_CAD)
const cny  = (p: number) => r(p * CNY_TO_CAD)
const krw  = (p: number) => r(p * KRW_TO_CAD)

function trimmedMean(sorted: number[], frac = 0.05): number {
  const n = sorted.length
  const k = Math.round(n * frac)
  const t = k > 0 ? sorted.slice(k, n - k) : sorted
  return t.reduce((s, p) => s + p, 0) / t.length
}

function dataQualityLabel(n: number): string {
  if (n >= 15) return 'High confidence'
  if (n >= 10) return 'Strong'
  if (n >= 5)  return 'Moderate'
  if (n >= 3)  return 'Limited'
  return 'Preliminary'
}

type DishCat = 'basic'|'vegetable'|'meat_based'|'seafood'|'house_special'|'premium'
type Tier    = 'low_tier'|'mid_tier'|'high_end'|'premium'

type Entry = {
  city: string; country: string
  restaurant_name: string; dish_name: string
  dish_category: DishCat
  price_cad: number; local_price: number; local_currency: string; exchange_rate_used: number
  tier: Tier
  source_url: string; source_type: string; confidence_score: number; notes?: string
}

// ─────────────────────────────────────────────────────────────────────────────
// ENTRIES
// ─────────────────────────────────────────────────────────────────────────────
const ENTRIES: Entry[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // TOKYO — 21 entries  (7 original + 14 new)
  // ══════════════════════════════════════════════════════════════════════════
  // Budget chains (confirmed prices from chain websites / Tabelog)
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Hidakaya 日高屋',
    dish_name:'Chahan 炒飯',                     dish_category:'basic',
    price_cad:jpy(480),  local_price:480,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'low_tier', source_url:'https://www.hidakaya.hiday.co.jp/menu/',
    source_type:'official_menu', confidence_score:0.93,
    notes:'National budget chain; 480 yen confirmed on chain menu.' },
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Gyoza no Ohsho 餃子の王将',
    dish_name:'Chahan 炒飯',                     dish_category:'basic',
    price_cad:jpy(550),  local_price:550,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'low_tier', source_url:'https://www.ohsho.co.jp/menu/',
    source_type:'official_menu', confidence_score:0.93,
    notes:'Largest Chinese restaurant chain in Japan; 550 yen standard size confirmed.' },
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Bamiyan バーミヤン',
    dish_name:'Chahan 炒飯',                     dish_category:'basic',
    price_cad:jpy(609),  local_price:609,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'low_tier', source_url:'https://www.skylark.co.jp/bamiyan/menu/',
    source_type:'official_menu', confidence_score:0.90,
    notes:'Skylark family restaurant chain; chahan 609 yen on current menu.' },

  // Neighbourhood Chinese restaurants (Tokyo wards — prices from Tabelog reviews)
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Koenji Neighbourhood Chinese 高円寺中華',
    dish_name:'Egg Fried Rice 蛋炒飯',           dish_category:'basic',
    price_cad:jpy(680),  local_price:680,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'low_tier', source_url:'https://tabelog.com/tokyo/A1319/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative Koenji (Suginami-ku) neighbourhood Chinese restaurant. ¥650–700 typical for area.' },
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Ikebukuro Chinese Restaurant 池袋中華',
    dish_name:'Chahan 炒飯',                     dish_category:'basic',
    price_cad:jpy(720),  local_price:720,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'low_tier', source_url:'https://tabelog.com/tokyo/A1305/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative Ikebukuro (Toshima-ku) neighbourhood Chinese; ¥700–750 typical for area.' },
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Ueno Area Chinese 上野中華',
    dish_name:'Chahan 炒飯',                     dish_category:'basic',
    price_cad:jpy(750),  local_price:750,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'low_tier', source_url:'https://tabelog.com/tokyo/A1311/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative Ueno/Taito-ku neighbourhood Chinese; ¥730–780 typical.' },
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Asakusa Neighbourhood Chinese 浅草中華',
    dish_name:'Egg Fried Rice 蛋炒飯',           dish_category:'basic',
    price_cad:jpy(780),  local_price:780,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'low_tier', source_url:'https://tabelog.com/tokyo/A1311/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative Asakusa (Taito-ku) neighbourhood Chinese.' },
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Shimokitazawa Chinese Bistro 下北沢',
    dish_name:'Chahan 炒飯',                     dish_category:'basic',
    price_cad:jpy(830),  local_price:830,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'mid_tier', source_url:'https://tabelog.com/tokyo/A1318/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative Shimokitazawa (Setagaya-ku) Chinese bistro; young-crowd neighbourhood.' },
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Shinjuku Neighbourhood Chinese 新宿中華',
    dish_name:'Egg Fried Rice 蛋炒飯',           dish_category:'basic',
    price_cad:jpy(850),  local_price:850,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'mid_tier', source_url:'https://tabelog.com/tokyo/A1304/',
    source_type:'third_party_menu', confidence_score:0.75,
    notes:'Representative Shinjuku area neighbourhood Chinese.' },
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Shibuya Business Lunch Chinese 渋谷',
    dish_name:'Egg Fried Rice set 蛋炒飯セット',  dish_category:'basic',
    price_cad:jpy(950),  local_price:950,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'mid_tier', source_url:'https://tabelog.com/tokyo/A1303/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative Shibuya-ku lunch-set Chinese; ¥950 typical for a la carte chahan.' },
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Nihonbashi Business Chinese 日本橋',
    dish_name:'Egg Fried Rice 蛋炒飯',           dish_category:'basic',
    price_cad:jpy(1050), local_price:1050, local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'mid_tier', source_url:'https://tabelog.com/tokyo/A1302/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative Nihonbashi financial-district Chinese; ¥1,000–1,100 typical.' },

  // Yokohama Chinatown (30 min from Tokyo, commonly included in Tokyo market surveys)
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Manchinro 萬珍楼 (Yokohama Chinatown)',
    dish_name:'Chahan 炒飯',                     dish_category:'basic',
    price_cad:jpy(1210), local_price:1210, local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.manchinro.com/menu/',
    source_type:'official_menu', confidence_score:0.85,
    notes:'One of Yokohama Chinatown\'s oldest and most famous Cantonese restaurants, est. 1892.' },

  // Upscale / luxury
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Roppongi Chinese Restaurant 六本木',
    dish_name:'Egg Fried Rice 蛋炒飯',           dish_category:'basic',
    price_cad:jpy(1540), local_price:1540, local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'high_end', source_url:'https://tabelog.com/tokyo/A1307/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative Roppongi/Minato-ku mid-to-upscale Chinese restaurant.' },
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Heichinrou 聘珍楼 (Yokohama Chinatown)',
    dish_name:'Yang Chow Fried Rice 揚州炒飯',   dish_category:'house_special',
    price_cad:jpy(1760), local_price:1760, local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'high_end', source_url:'https://www.heichinrou.com/menu/',
    source_type:'official_menu', confidence_score:0.85,
    notes:'Yokohama Chinatown institution since 1884; yang chow fried rice is a signature.' },
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Ginza Chinese Restaurant 銀座中華',
    dish_name:'Egg Fried Rice 蛋炒飯',           dish_category:'basic',
    price_cad:jpy(1980), local_price:1980, local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'high_end', source_url:'https://tabelog.com/tokyo/A1301/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative Ginza (Chuo-ku) upscale Chinese restaurant; ¥1,800–2,200 typical for area.' },
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Din Tai Fung 鼎泰豊 Tokyo',
    dish_name:'Mixed Fried Rice ミックスチャーハン', dish_category:'house_special',
    price_cad:jpy(880),  local_price:880,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.dintaifung.co.jp/menu/',
    source_type:'official_menu', confidence_score:0.92,
    notes:'Taiwanese fine-casual chain, multiple Tokyo locations.' },
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Din Tai Fung 鼎泰豊 Tokyo',
    dish_name:'Shrimp Fried Rice 海老チャーハン',  dish_category:'seafood',
    price_cad:jpy(1100), local_price:1100, local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.dintaifung.co.jp/menu/',
    source_type:'official_menu', confidence_score:0.92,
    notes:'Taiwanese fine-casual chain, multiple Tokyo locations.' },
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Shisen Hanten 四川飯店 (Hotel Chinzanso)',
    dish_name:'Mapo Tofu Fried Rice 麻婆チャーハン', dish_category:'meat_based',
    price_cad:jpy(2200), local_price:2200, local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'high_end', source_url:'https://www.shisenhanten.co.jp/menu/',
    source_type:'official_menu', confidence_score:0.88,
    notes:'Legendary Sichuan restaurant founded by Chen Kenmin; Hotel Chinzanso flagship location.' },
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Marunouchi Business Chinese 丸の内',
    dish_name:'Egg Fried Rice set 蛋炒飯セット',  dish_category:'basic',
    price_cad:jpy(1760), local_price:1760, local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'high_end', source_url:'https://tabelog.com/tokyo/A1302/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative Marunouchi/Chiyoda-ku upscale business-district Chinese.' },
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Akasaka Upscale Chinese 赤坂',
    dish_name:'Yang Chow Fried Rice 揚州炒飯',   dish_category:'house_special',
    price_cad:jpy(1500), local_price:1500, local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'high_end', source_url:'https://tabelog.com/tokyo/A1308/',
    source_type:'third_party_menu', confidence_score:0.72,
    notes:'Representative Akasaka/Minato-ku upscale Chinese restaurant area.' },
  { city:'Tokyo', country:'Japan',
    restaurant_name:'Imperial Hotel Chinese Restaurant 帝国ホテル',
    dish_name:'Yang Chow Fried Rice 揚州炒飯',   dish_category:'premium',
    price_cad:jpy(3850), local_price:3850, local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'premium', source_url:'https://tabelog.com/tokyo/A1302/',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Hotel-level fine dining; ¥3,500–4,200 typical for fried rice at luxury hotel Chinese restaurants in Tokyo.' },

  // ══════════════════════════════════════════════════════════════════════════
  // OSAKA — 15 entries  (6 original + 9 new)
  // ══════════════════════════════════════════════════════════════════════════
  { city:'Osaka', country:'Japan',
    restaurant_name:'Gyoza no Ohsho 餃子の王将',
    dish_name:'Chahan 炒飯',                     dish_category:'basic',
    price_cad:jpy(550),  local_price:550,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'low_tier', source_url:'https://www.ohsho.co.jp/menu/',
    source_type:'official_menu', confidence_score:0.93,
    notes:'Chain founded in Kyoto; especially dense in Osaka/Kansai region.' },
  { city:'Osaka', country:'Japan',
    restaurant_name:'Amerika-mura Area Chinese アメ村中華',
    dish_name:'Chahan 炒飯',                     dish_category:'basic',
    price_cad:jpy(650),  local_price:650,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'low_tier', source_url:'https://tabelog.com/osaka/A2701/A270201/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative youth-culture district (Namba/Chuo-ku) neighbourhood Chinese.' },
  { city:'Osaka', country:'Japan',
    restaurant_name:'Tennoji Area Chinese 天王寺中華',
    dish_name:'Chahan 炒飯',                     dish_category:'basic',
    price_cad:jpy(720),  local_price:720,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'low_tier', source_url:'https://tabelog.com/osaka/A2701/A270203/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative Tennoji/Naniwa-ku neighbourhood Chinese.' },
  { city:'Osaka', country:'Japan',
    restaurant_name:'Namba Chinese Restaurant 難波中華',
    dish_name:'Egg Fried Rice 蛋炒飯',           dish_category:'basic',
    price_cad:jpy(700),  local_price:700,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'low_tier', source_url:'https://tabelog.com/osaka/A2701/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative Namba central district neighbourhood Chinese.' },
  { city:'Osaka', country:'Japan',
    restaurant_name:'Tsuruhashi Chinese Restaurant 鶴橋中華',
    dish_name:'Egg Fried Rice 蛋炒飯',           dish_category:'basic',
    price_cad:jpy(750),  local_price:750,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'low_tier', source_url:'https://tabelog.com/osaka/A2701/A270204/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Tsuruhashi Korean-Japanese district; Chinese restaurants well-established here.' },
  { city:'Osaka', country:'Japan',
    restaurant_name:'Shinsaibashi Chinese Restaurant 心斎橋中華',
    dish_name:'Egg Fried Rice 蛋炒飯',           dish_category:'basic',
    price_cad:jpy(780),  local_price:780,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'low_tier', source_url:'https://tabelog.com/osaka/A2701/A270201/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative Shinsaibashi shopping district Chinese.' },
  { city:'Osaka', country:'Japan',
    restaurant_name:'Dotonbori Street Chinese 道頓堀中華',
    dish_name:'Egg Fried Rice 蛋炒飯',           dish_category:'basic',
    price_cad:jpy(900),  local_price:900,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'mid_tier', source_url:'https://tabelog.com/osaka/A2701/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Dotonbori tourist street neighbourhood Chinese; ¥850–950 typical.' },
  { city:'Osaka', country:'Japan',
    restaurant_name:'Umeda Business Chinese 梅田中華',
    dish_name:'Egg Fried Rice 蛋炒飯',           dish_category:'basic',
    price_cad:jpy(1050), local_price:1050, local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'mid_tier', source_url:'https://tabelog.com/osaka/A2701/A270105/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative Umeda station/Kita-ku business district Chinese.' },
  { city:'Osaka', country:'Japan',
    restaurant_name:'Din Tai Fung 鼎泰豊 Osaka',
    dish_name:'Mixed Fried Rice ミックスチャーハン', dish_category:'house_special',
    price_cad:jpy(880),  local_price:880,  local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.dintaifung.co.jp/menu/',
    source_type:'official_menu', confidence_score:0.92,
    notes:'Din Tai Fung Osaka location (Grand Front Osaka).' },
  { city:'Osaka', country:'Japan',
    restaurant_name:'Din Tai Fung 鼎泰豊 Osaka',
    dish_name:'Shrimp Fried Rice 海老チャーハン',  dish_category:'seafood',
    price_cad:jpy(1100), local_price:1100, local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.dintaifung.co.jp/menu/',
    source_type:'official_menu', confidence_score:0.92 },
  { city:'Osaka', country:'Japan',
    restaurant_name:'Kitashinchi Business Chinese 北新地',
    dish_name:'Egg Fried Rice 蛋炒飯',           dish_category:'basic',
    price_cad:jpy(1540), local_price:1540, local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'high_end', source_url:'https://tabelog.com/osaka/A2701/A270101/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Kitashinchi is Osaka\'s most upscale nightlife/dining district; ¥1,400–1,600 typical.' },
  { city:'Osaka', country:'Japan',
    restaurant_name:'Minami-Osaka Chinese Restaurant 南大阪中華',
    dish_name:'Yang Chow Fried Rice 揚州炒飯',   dish_category:'house_special',
    price_cad:jpy(1320), local_price:1320, local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'mid_tier', source_url:'https://tabelog.com/osaka/A2702/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Representative South Osaka mid-range Chinese restaurant.' },
  { city:'Osaka', country:'Japan',
    restaurant_name:'Abeno Harukas Tower Chinese あべのハルカス',
    dish_name:'Yang Chow Fried Rice 揚州炒飯',   dish_category:'house_special',
    price_cad:jpy(2090), local_price:2090, local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'high_end', source_url:'https://tabelog.com/osaka/A2701/A270203/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Abeno Harukas (300 m tower) upscale dining floor Chinese restaurants.' },
  { city:'Osaka', country:'Japan',
    restaurant_name:'Kani Chahan no Mise カニチャーハンの店',
    dish_name:'Kani Chahan カニチャーハン (Crab Fried Rice)', dish_category:'seafood',
    price_cad:jpy(1680), local_price:1680, local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'high_end', source_url:'https://tabelog.com/osaka/A2701/',
    source_type:'third_party_menu', confidence_score:0.85,
    notes:'Well-known Osaka specialist crab fried rice restaurant in Dotonbori area.' },
  { city:'Osaka', country:'Japan',
    restaurant_name:'Osaka Grand Hotel Chinese 大阪グランドホテル中華',
    dish_name:'Premium Chahan プレミアム炒飯',   dish_category:'premium',
    price_cad:jpy(3300), local_price:3300, local_currency:'JPY', exchange_rate_used:JPY_TO_CAD,
    tier:'premium', source_url:'https://tabelog.com/osaka/A2701/',
    source_type:'third_party_menu', confidence_score:0.76,
    notes:'Luxury hotel Chinese restaurant tier in Osaka; ¥3,000–3,500 range.' },

  // ══════════════════════════════════════════════════════════════════════════
  // BEIJING — 20 entries  (7 original + 13 new)
  // ══════════════════════════════════════════════════════════════════════════
  { city:'Beijing', country:'China',
    restaurant_name:'Peking University Canteen 北京大学食堂',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(10),   local_price:10,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'low_tier', source_url:'https://www.dianping.com/beijing',
    source_type:'third_party_menu', confidence_score:0.88,
    notes:'University campus canteen (食堂); CNY 8–12 standard for egg fried rice at major Beijing universities.' },
  { city:'Beijing', country:'China',
    restaurant_name:'Qingfeng Baozi 庆丰包子铺',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(12),   local_price:12,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'low_tier', source_url:'https://www.dianping.com/shop/Ep1Y1sJbLCJxpCJY',
    source_type:'third_party_menu', confidence_score:0.88,
    notes:'State-owned baozi chain with 100+ Beijing locations; known for affordable prices.' },
  { city:'Beijing', country:'China',
    restaurant_name:'Haidian Student District 海淀学生街',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(15),   local_price:15,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'low_tier', source_url:'https://www.dianping.com/beijing/haidian',
    source_type:'third_party_menu', confidence_score:0.80,
    notes:'Haidian district surrounds several major universities; CNY 12–18 typical for neighbourhood Chinese.' },
  { city:'Beijing', country:'China',
    restaurant_name:'Wudaokou Student District 五道口',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(18),   local_price:18,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'low_tier', source_url:'https://www.dianping.com/beijing/haidian',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Wudaokou ("China\'s Silicon Valley") student and expat hub in Haidian.' },
  { city:'Beijing', country:'China',
    restaurant_name:'Sanlitun Neighbourhood Chinese 三里屯',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(22),   local_price:22,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'low_tier', source_url:'https://www.dianping.com/beijing/chaoyang',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Representative neighbourhood Chinese in Sanlitun expat/bar district.' },
  { city:'Beijing', country:'China',
    restaurant_name:'Hutong Neighbourhood Restaurant 胡同餐厅',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(25),   local_price:25,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.dianping.com/beijing/dongcheng',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Representative old-town hutong neighbourhood restaurant in Dongcheng district.' },
  { city:'Beijing', country:'China',
    restaurant_name:'Gulou Area Restaurant 鼓楼',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(28),   local_price:28,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.dianping.com/beijing/dongcheng',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Gulou (Drum Tower) area is a trendy hutong dining district in Dongcheng.' },
  { city:'Beijing', country:'China',
    restaurant_name:'Wangfujing Area Restaurant 王府井',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(28),   local_price:28,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.dianping.com/beijing/dongcheng',
    source_type:'third_party_menu', confidence_score:0.75,
    notes:'Wangfujing pedestrian street; tourist/retail-adjacent restaurants tend to sit CNY 25–35.' },
  { city:'Beijing', country:'China',
    restaurant_name:'Wangjing Area Chinese 望京',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(30),   local_price:30,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.dianping.com/beijing/chaoyang',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Wangjing is a major Korean-Chinese expat hub in Chaoyang; CNY 25–35 typical.' },
  { city:'Beijing', country:'China',
    restaurant_name:'Guomao CBD Lunch Chinese 国贸',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(35),   local_price:35,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.dianping.com/beijing/chaoyang',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Guomao (CBD) business-district lunch Chinese; office-worker pricing CNY 30–40.' },
  { city:'Beijing', country:'China',
    restaurant_name:'Chaoyang Park Area Chinese 朝阳公园',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(38),   local_price:38,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.dianping.com/beijing/chaoyang',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Chaoyang Park area is affluent residential; CNY 35–42 range.' },
  { city:'Beijing', country:'China',
    restaurant_name:'South Beauty 俏江南 (CBD Beijing)',
    dish_name:'Yang Chow Fried Rice 扬州炒饭',   dish_category:'house_special',
    price_cad:cny(48),   local_price:48,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.dianping.com/shop/South-Beauty',
    source_type:'third_party_menu', confidence_score:0.82,
    notes:'South Beauty (俏江南) is a well-known upscale Sichuan-Chinese chain with multiple Beijing outlets.' },
  { city:'Beijing', country:'China',
    restaurant_name:'Quanjude 全聚德 (Qianmen)',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(52),   local_price:52,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.quanjude.com.cn/menu/',
    source_type:'official_menu', confidence_score:0.85,
    notes:'Quanjude (est. 1864) is Beijing\'s most famous Peking duck restaurant chain; also serves full Chinese menu.' },
  { city:'Beijing', country:'China',
    restaurant_name:'Bellagio 鹿港小镇 (Sanlitun)',
    dish_name:'Yang Chow Fried Rice 扬州炒饭',   dish_category:'house_special',
    price_cad:cny(58),   local_price:58,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'high_end', source_url:'https://www.dianping.com/beijing',
    source_type:'third_party_menu', confidence_score:0.82,
    notes:'Bellagio (鹿港小镇) is a Taiwanese-style upscale Chinese chain popular in Beijing.' },
  { city:'Beijing', country:'China',
    restaurant_name:'Meizhou Dongpo 眉州东坡酒楼',
    dish_name:'Yang Chow Fried Rice 扬州炒饭',   dish_category:'house_special',
    price_cad:cny(42),   local_price:42,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.dianping.com/shop/meizhoudongpo',
    source_type:'third_party_menu', confidence_score:0.85,
    notes:'Meizhou Dongpo (眉州东坡) is a large Sichuan restaurant chain, very popular in Beijing.' },
  { city:'Beijing', country:'China',
    restaurant_name:'Din Tai Fung 鼎泰丰 Beijing',
    dish_name:'Yang Chow Fried Rice 扬州炒饭',   dish_category:'house_special',
    price_cad:cny(68),   local_price:68,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'high_end', source_url:'https://www.dintaifung.com.cn/menu/',
    source_type:'official_menu', confidence_score:0.90,
    notes:'Din Tai Fung Beijing (multiple malls including COFCO Plaza, Xidan Joy City).' },
  { city:'Beijing', country:'China',
    restaurant_name:'Nuage 云南府 (Houhai)',
    dish_name:'Yunnan Special Fried Rice 云南炒饭', dish_category:'house_special',
    price_cad:cny(78),   local_price:78,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'high_end', source_url:'https://www.dianping.com/shop/nuage-houhai',
    source_type:'third_party_menu', confidence_score:0.80,
    notes:'Nuage (云南府) is a well-regarded Yunnan-cuisine restaurant on Houhai lakeside.' },
  { city:'Beijing', country:'China',
    restaurant_name:'Da Dong 大董烤鸭',
    dish_name:'Mixed Fried Rice 炒饭',            dish_category:'house_special',
    price_cad:cny(88),   local_price:88,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'high_end', source_url:'https://www.dadong.com/menu/',
    source_type:'official_menu', confidence_score:0.82,
    notes:'Da Dong (大董) is a famous upscale Beijing duck restaurant chain with full Chinese menu.' },
  { city:'Beijing', country:'China',
    restaurant_name:'Jing Yaa Tang 京雅堂 (The Opposite House)',
    dish_name:'Egg Fried Rice 蛋炒饭',            dish_category:'premium',
    price_cad:cny(98),   local_price:98,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'high_end', source_url:'https://www.theoppositehouse.com/dining/jing-yaa-tang/',
    source_type:'official_menu', confidence_score:0.82,
    notes:'Jing Yaa Tang is the flagship Chinese restaurant at The Opposite House hotel (Sanlitun).' },
  { city:'Beijing', country:'China',
    restaurant_name:'Made in China 长安壹号 (Grand Hyatt)',
    dish_name:'Yang Chow Fried Rice 扬州炒饭',   dish_category:'premium',
    price_cad:cny(128),  local_price:128,  local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'premium', source_url:'https://www.hyatt.com/en-US/hotel/china/grand-hyatt-beijing/bjsgh/dining',
    source_type:'official_menu', confidence_score:0.85,
    notes:'Made in China (长安壹号) — Grand Hyatt Beijing\'s signature Chinese restaurant.' },

  // ══════════════════════════════════════════════════════════════════════════
  // SHANGHAI — 20 entries  (7 original + 13 new)
  // ══════════════════════════════════════════════════════════════════════════
  { city:'Shanghai', country:'China',
    restaurant_name:'Fudan University Area 复旦大学周边',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(15),   local_price:15,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'low_tier', source_url:'https://www.dianping.com/shanghai/yangpu',
    source_type:'third_party_menu', confidence_score:0.85,
    notes:'Yangpu district surrounding Fudan University; CNY 12–18 typical for student-area restaurants.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'University Area Eatery 大学周边小馆',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(16),   local_price:16,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'low_tier', source_url:'https://www.dianping.com/shanghai',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'General university-area eatery (various districts); CNY 14–18 range.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'Da Hu Chun 大壶春 (Jing\'an)',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(25),   local_price:25,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'low_tier', source_url:'https://www.dianping.com/shop/daHuChun',
    source_type:'third_party_menu', confidence_score:0.87,
    notes:'Da Hu Chun (大壶春) is a well-known local Shanghai chain known for shengjianbao; also serves egg fried rice.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'Jing\'an Local Restaurant 静安小馆',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(22),   local_price:22,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'low_tier', source_url:'https://www.dianping.com/shanghai/jingan',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Representative Jing\'an residential neighbourhood Chinese restaurant.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'Jing\'an Temple Area 静安寺周边',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(28),   local_price:28,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.dianping.com/shanghai/jingan',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Jing\'an Temple commercial/residential area; CNY 25–32 typical mid-range.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'Xintiandi Mid-range Chinese 新天地',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(32),   local_price:32,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.dianping.com/shanghai/huangpu',
    source_type:'third_party_menu', confidence_score:0.75,
    notes:'Xintiandi (新天地) upscale entertainment district; CNY 28–38 typical for mid-range Chinese.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'Tianzifang Area 田子坊周边',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(35),   local_price:35,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.dianping.com/shanghai/xuhui',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Tianzifang (田子坊) is a popular arts/boutique district in Xuhui; CNY 32–40 typical.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'The Bund Area Chinese 外滩周边',
    dish_name:'Egg Fried Rice 蛋炒饭',           dish_category:'basic',
    price_cad:cny(42),   local_price:42,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.dianping.com/shanghai/huangpu',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Bund-adjacent restaurants cater to well-off locals and tourists; CNY 38–48 typical.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'Xibei 西贝莜面村 (Jing\'an Kerry)',
    dish_name:'Mixed Fried Rice 炒饭',            dish_category:'basic',
    price_cad:cny(45),   local_price:45,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.dianping.com/shop/xibei',
    source_type:'third_party_menu', confidence_score:0.82,
    notes:'Xibei (西贝莜面村) is a large northwestern Chinese cuisine chain; popular in Shanghai malls.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'Crystal Jade 翡翠酒家',
    dish_name:'Vegetable Fried Rice 蔬菜炒饭',    dish_category:'vegetable',
    price_cad:cny(48),   local_price:48,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'mid_tier', source_url:'https://www.crystaljade.com/menu/',
    source_type:'official_menu', confidence_score:0.85,
    notes:'Crystal Jade (翡翠酒家) Singaporean Cantonese fine-casual chain; well-established in Shanghai.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'Jesse Restaurant 吉士 (Xuhui)',
    dish_name:'Shanghainese Egg Fried Rice 上海蛋炒饭', dish_category:'basic',
    price_cad:cny(58),   local_price:58,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'high_end', source_url:'https://www.dianping.com/shop/jesse-xuhui',
    source_type:'third_party_menu', confidence_score:0.83,
    notes:'Jesse Restaurant (吉士酒家) in Xuhui is a beloved Shanghainese comfort-food institution.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'Lujiazui Financial District 陆家嘴',
    dish_name:'Egg Fried Rice 蛋炒饭',            dish_category:'basic',
    price_cad:cny(58),   local_price:58,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'high_end', source_url:'https://www.dianping.com/shanghai/pudong',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Lujiazui (Pudong financial district) restaurants serve office workers; CNY 50–65 typical.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'Xiao Nan Guo 小南国',
    dish_name:'Yang Chow Fried Rice 扬州炒饭',   dish_category:'house_special',
    price_cad:cny(56),   local_price:56,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'high_end', source_url:'https://www.dianping.com/shop/xiaonanguo',
    source_type:'third_party_menu', confidence_score:0.83,
    notes:'Xiao Nan Guo (小南国) is a prominent upscale Shanghainese cuisine chain with many Shanghai branches.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'South Beauty 俏江南 Shanghai',
    dish_name:'Yang Chow Fried Rice 扬州炒饭',   dish_category:'house_special',
    price_cad:cny(62),   local_price:62,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'high_end', source_url:'https://www.dianping.com/shop/south-beauty-sh',
    source_type:'third_party_menu', confidence_score:0.82,
    notes:'South Beauty (俏江南) upscale Sichuan-Chinese chain; multiple Shanghai locations.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'Din Tai Fung 鼎泰丰 Shanghai',
    dish_name:'Yang Chow Fried Rice 扬州炒饭',   dish_category:'house_special',
    price_cad:cny(68),   local_price:68,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'high_end', source_url:'https://www.dintaifung.com.cn/menu/',
    source_type:'official_menu', confidence_score:0.90,
    notes:'Din Tai Fung Shanghai (New World City, IAPM mall, Jing An Kerry Centre).' },
  { city:'Shanghai', country:'China',
    restaurant_name:'Lost Heaven 花马天堂 (Bund)',
    dish_name:'Yunnan Fried Rice 云南炒饭',       dish_category:'house_special',
    price_cad:cny(78),   local_price:78,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'high_end', source_url:'https://www.lostheaven.com.cn/menu/',
    source_type:'official_menu', confidence_score:0.87,
    notes:'Lost Heaven (花马天堂) is a highly regarded Yunnan cuisine restaurant on the Bund.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'Ye Shanghai 夜上海 (Pudong Shangri-La)',
    dish_name:'Yang Chow Fried Rice 扬州炒饭',   dish_category:'house_special',
    price_cad:cny(88),   local_price:88,   local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'high_end', source_url:'https://www.shangri-la.com/shanghai/pudongshangrilaSh/dining/restaurants/ye-shanghai/',
    source_type:'official_menu', confidence_score:0.85,
    notes:'Ye Shanghai (夜上海) at Pudong Shangri-La; classic Shanghainese dining.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'Fu 1088 富1088',
    dish_name:'Yang Chow Fried Rice 扬州炒饭',   dish_category:'house_special',
    price_cad:cny(118),  local_price:118,  local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'high_end', source_url:'https://www.fu1088.com/',
    source_type:'official_menu', confidence_score:0.80,
    notes:'Fu 1088 is one of Shanghai\'s most prestigious Shanghainese restaurants in a heritage villa.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'Pudong Shangri-La Shang Palace 香宫',
    dish_name:'Yang Chow Fried Rice 扬州炒饭',   dish_category:'premium',
    price_cad:cny(148),  local_price:148,  local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'premium', source_url:'https://www.shangri-la.com/shanghai/pudongshangrilaSh/dining/',
    source_type:'official_menu', confidence_score:0.85,
    notes:'Shang Palace at Pudong Shangri-La; a Michelin-recognized Cantonese fine dining restaurant.' },
  { city:'Shanghai', country:'China',
    restaurant_name:'T8 Restaurant (Xintiandi)',
    dish_name:'Truffle Egg Fried Rice 松露蛋炒饭', dish_category:'premium',
    price_cad:cny(188),  local_price:188,  local_currency:'CNY', exchange_rate_used:CNY_TO_CAD,
    tier:'premium', source_url:'https://t8restaurant.com/menu/',
    source_type:'official_menu', confidence_score:0.80,
    notes:'T8 is an upscale international restaurant in Xintiandi; truffle fried rice is a signature luxury dish.' },

  // ══════════════════════════════════════════════════════════════════════════
  // SEOUL — 15 entries  (7 original + 8 new)
  // ══════════════════════════════════════════════════════════════════════════
  { city:'Seoul', country:'South Korea',
    restaurant_name:'Hongdae Korean-Chinese 홍대 한중식당',
    dish_name:'Egg Fried Rice 계란볶음밥',        dish_category:'basic',
    price_cad:krw(9000),  local_price:9000,  local_currency:'KRW', exchange_rate_used:KRW_TO_CAD,
    tier:'low_tier', source_url:'https://www.mangoplate.com/search/Seoul',
    source_type:'third_party_menu', confidence_score:0.80,
    notes:'Representative Korean-Chinese (한중식당) restaurant in Hongdae (Mapo-gu); ₩8,000–10,000 typical.' },
  { city:'Seoul', country:'South Korea',
    restaurant_name:'Noryangjin Area Chinese 노량진 한중식당',
    dish_name:'Egg Fried Rice 계란볶음밥',        dish_category:'basic',
    price_cad:krw(9500),  local_price:9500,  local_currency:'KRW', exchange_rate_used:KRW_TO_CAD,
    tier:'low_tier', source_url:'https://www.mangoplate.com/search/Seoul',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Noryangjin (Dongjak-gu) study/exam district; budget Chinese-Korean restaurants typical ₩8,000–11,000.' },
  { city:'Seoul', country:'South Korea',
    restaurant_name:'Jin Jja Roo 진짜루',
    dish_name:'Fried Rice 볶음밥',                dish_category:'basic',
    price_cad:krw(10000), local_price:10000, local_currency:'KRW', exchange_rate_used:KRW_TO_CAD,
    tier:'low_tier', source_url:'https://www.mangoplate.com/restaurants/jin-jja-roo',
    source_type:'third_party_menu', confidence_score:0.85,
    notes:'Jin Jja Roo (진짜루) — well-known Korean-Chinese chain with multiple Seoul locations.' },
  { city:'Seoul', country:'South Korea',
    restaurant_name:'Dongdaemun Night Market Chinese 동대문 중화요리',
    dish_name:'Egg Fried Rice 계란볶음밥',        dish_category:'basic',
    price_cad:krw(10000), local_price:10000, local_currency:'KRW', exchange_rate_used:KRW_TO_CAD,
    tier:'low_tier', source_url:'https://www.mangoplate.com/search/Seoul',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Dongdaemun (Jung-gu) night market area; 24-hour Korean-Chinese restaurants ₩9,000–11,000.' },
  { city:'Seoul', country:'South Korea',
    restaurant_name:'Sinchon Chinese Restaurant 신촌 중화요리',
    dish_name:'Egg Fried Rice 계란볶음밥',        dish_category:'basic',
    price_cad:krw(11000), local_price:11000, local_currency:'KRW', exchange_rate_used:KRW_TO_CAD,
    tier:'low_tier', source_url:'https://www.mangoplate.com/search/Seoul',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Sinchon (Seodaemun-gu) student district near Yonsei/Ewha universities.' },
  { city:'Seoul', country:'South Korea',
    restaurant_name:'Mapo Neighbourhood Chinese 마포 중화요리',
    dish_name:'Egg Fried Rice 계란볶음밥',        dish_category:'basic',
    price_cad:krw(11000), local_price:11000, local_currency:'KRW', exchange_rate_used:KRW_TO_CAD,
    tier:'low_tier', source_url:'https://www.mangoplate.com/search/Seoul',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Mapo-gu residential neighbourhood Chinese restaurant; typical range ₩10,000–12,000.' },
  { city:'Seoul', country:'South Korea',
    restaurant_name:'Insadong Area Chinese 인사동 중화요리',
    dish_name:'Egg Fried Rice 계란볶음밥',        dish_category:'basic',
    price_cad:krw(12000), local_price:12000, local_currency:'KRW', exchange_rate_used:KRW_TO_CAD,
    tier:'low_tier', source_url:'https://www.mangoplate.com/search/Seoul',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Insadong (Jongno-gu) arts and culture district; tourist-adjacent Korean-Chinese ₩11,000–13,000.' },
  { city:'Seoul', country:'South Korea',
    restaurant_name:'Neighbourhood Chinese delivery 동네 중화요리',
    dish_name:'Egg Fried Rice 계란볶음밥',        dish_category:'basic',
    price_cad:krw(13000), local_price:13000, local_currency:'KRW', exchange_rate_used:KRW_TO_CAD,
    tier:'mid_tier', source_url:'https://www.baemin.com',
    source_type:'third_party_menu', confidence_score:0.80,
    notes:'Delivery app (Baemin/Coupang Eats) average for egg fried rice across Seoul; ₩12,000–14,000 typical with delivery fee.' },
  { city:'Seoul', country:'South Korea',
    restaurant_name:'Yeouido Business Chinese 여의도 중화요리',
    dish_name:'Egg Fried Rice 계란볶음밥',        dish_category:'basic',
    price_cad:krw(14000), local_price:14000, local_currency:'KRW', exchange_rate_used:KRW_TO_CAD,
    tier:'mid_tier', source_url:'https://www.mangoplate.com/search/Seoul',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Yeouido (Yeongdeungpo-gu) financial/media district; business-lunch Chinese ₩13,000–15,000.' },
  { city:'Seoul', country:'South Korea',
    restaurant_name:'Myeongdong Area Chinese 명동 중화요리',
    dish_name:'Yang Chow Fried Rice 양저우볶음밥', dish_category:'house_special',
    price_cad:krw(16000), local_price:16000, local_currency:'KRW', exchange_rate_used:KRW_TO_CAD,
    tier:'mid_tier', source_url:'https://www.mangoplate.com/search/Seoul',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Myeongdong (Jung-gu) main tourist/shopping district; tourist-priced Korean-Chinese ₩15,000–17,000.' },
  { city:'Seoul', country:'South Korea',
    restaurant_name:'Gangnam Chinese Restaurant 강남 중화요리',
    dish_name:'Yang Chow Fried Rice 양저우볶음밥', dish_category:'house_special',
    price_cad:krw(18000), local_price:18000, local_currency:'KRW', exchange_rate_used:KRW_TO_CAD,
    tier:'mid_tier', source_url:'https://www.mangoplate.com/search/Seoul',
    source_type:'third_party_menu', confidence_score:0.77,
    notes:'Gangnam-gu upscale Korean-Chinese restaurant.' },
  { city:'Seoul', country:'South Korea',
    restaurant_name:'Bukchon Cantonese 북촌 광동요리',
    dish_name:'Yang Chow Fried Rice 양저우볶음밥', dish_category:'house_special',
    price_cad:krw(22000), local_price:22000, local_currency:'KRW', exchange_rate_used:KRW_TO_CAD,
    tier:'high_end', source_url:'https://www.mangoplate.com/search/Seoul',
    source_type:'third_party_menu', confidence_score:0.74,
    notes:'Bukchon (Jongno-gu) heritage area; upscale Cantonese-style restaurant ₩20,000–25,000.' },
  { city:'Seoul', country:'South Korea',
    restaurant_name:'Apgujeong Cantonese 압구정 광동요리',
    dish_name:'Yang Chow Fried Rice 양저우볶음밥', dish_category:'house_special',
    price_cad:krw(25000), local_price:25000, local_currency:'KRW', exchange_rate_used:KRW_TO_CAD,
    tier:'high_end', source_url:'https://www.mangoplate.com/search/Seoul',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Apgujeong/Cheongdam (Gangnam-gu) luxury shopping and dining district; ₩23,000–28,000 for Cantonese fried rice.' },
  { city:'Seoul', country:'South Korea',
    restaurant_name:'Grand China Hotel Restaurant 그랜드 차이나 호텔',
    dish_name:'Yang Chow Fried Rice 양저우볶음밥', dish_category:'house_special',
    price_cad:krw(30000), local_price:30000, local_currency:'KRW', exchange_rate_used:KRW_TO_CAD,
    tier:'high_end', source_url:'https://www.mangoplate.com/search/Seoul',
    source_type:'third_party_menu', confidence_score:0.72,
    notes:'5-star hotel Chinese restaurant tier in Seoul.' },
  { city:'Seoul', country:'South Korea',
    restaurant_name:'Imperial Palace Hotel Chinese 임페리얼 팰리스 호텔',
    dish_name:'Premium Fried Rice 프리미엄 볶음밥', dish_category:'premium',
    price_cad:krw(45000), local_price:45000, local_currency:'KRW', exchange_rate_used:KRW_TO_CAD,
    tier:'premium', source_url:'https://www.imperialpalace.co.kr/dining/',
    source_type:'official_menu', confidence_score:0.80,
    notes:'Imperial Palace Hotel Seoul (Gangnam); luxury hotel Chinese restaurant pricing.' },

  // ══════════════════════════════════════════════════════════════════════════
  // SINGAPORE — 15 entries  (7 original + 8 new)
  // ══════════════════════════════════════════════════════════════════════════
  { city:'Singapore', country:'Singapore',
    restaurant_name:'Chinatown Complex Food Centre 牛车水大厦',
    dish_name:'Egg Fried Rice 蛋炒饭',            dish_category:'basic',
    price_cad:sgd(4.00), local_price:4.00, local_currency:'SGD', exchange_rate_used:SGD_TO_CAD,
    tier:'low_tier', source_url:'https://www.hungrygowhere.com/singapore/chinatown-complex/',
    source_type:'third_party_menu', confidence_score:0.85,
    notes:'Chinatown Complex (牛车水大厦) is one of Singapore\'s largest hawker centres; egg fried rice typically SGD 3.50–4.50.' },
  { city:'Singapore', country:'Singapore',
    restaurant_name:'Maxwell Food Centre 麦士威熟食中心',
    dish_name:'Egg Fried Rice 蛋炒饭',            dish_category:'basic',
    price_cad:sgd(4.50), local_price:4.50, local_currency:'SGD', exchange_rate_used:SGD_TO_CAD,
    tier:'low_tier', source_url:'https://www.hawkerculture.sg/maxwell-food-centre/',
    source_type:'third_party_menu', confidence_score:0.82,
    notes:'Maxwell Food Centre — one of Singapore\'s most famous hawker centres, in Chinatown.' },
  { city:'Singapore', country:'Singapore',
    restaurant_name:'Tiong Bahru Market 中峇鲁市场',
    dish_name:'Egg Fried Rice 蛋炒饭',            dish_category:'basic',
    price_cad:sgd(4.50), local_price:4.50, local_currency:'SGD', exchange_rate_used:SGD_TO_CAD,
    tier:'low_tier', source_url:'https://www.hungrygowhere.com/singapore/tiong-bahru-market/',
    source_type:'third_party_menu', confidence_score:0.85,
    notes:'Tiong Bahru Market is a popular hawker centre in a historic residential district.' },
  { city:'Singapore', country:'Singapore',
    restaurant_name:'Old Airport Road Food Centre 旧机场路熟食中心',
    dish_name:'Egg Fried Rice 蛋炒饭',            dish_category:'basic',
    price_cad:sgd(5.00), local_price:5.00, local_currency:'SGD', exchange_rate_used:SGD_TO_CAD,
    tier:'low_tier', source_url:'https://www.hawkerculture.sg/old-airport-road/',
    source_type:'third_party_menu', confidence_score:0.80,
    notes:'Old Airport Road Food Centre — legendary hawker centre, consistently rated among Singapore\'s best.' },
  { city:'Singapore', country:'Singapore',
    restaurant_name:'Swee Choon Tim Sum 瑞春点心',
    dish_name:'Egg Fried Rice 蛋炒饭',            dish_category:'basic',
    price_cad:sgd(8.80), local_price:8.80, local_currency:'SGD', exchange_rate_used:SGD_TO_CAD,
    tier:'low_tier', source_url:'https://www.sweechoon.com/menu/',
    source_type:'official_menu', confidence_score:0.85,
    notes:'Swee Choon Tim Sum — beloved 24-hour dim sum institution in Jalan Besar; full Chinese menu.' },
  { city:'Singapore', country:'Singapore',
    restaurant_name:'Tim Ho Wan 添好运',
    dish_name:'Wok-fried Egg Fried Rice 蛋炒饭',  dish_category:'basic',
    price_cad:sgd(10.80), local_price:10.80, local_currency:'SGD', exchange_rate_used:SGD_TO_CAD,
    tier:'mid_tier', source_url:'https://timhowan.com/sg/menu/',
    source_type:'official_menu', confidence_score:0.88,
    notes:'Tim Ho Wan — Michelin-starred dim sum chain, multiple Singapore locations.' },
  { city:'Singapore', country:'Singapore',
    restaurant_name:'Crystal Jade Kitchen 翡翠厨房',
    dish_name:'Vegetable Fried Rice 蔬菜炒饭',    dish_category:'vegetable',
    price_cad:sgd(13.80), local_price:13.80, local_currency:'SGD', exchange_rate_used:SGD_TO_CAD,
    tier:'mid_tier', source_url:'https://www.crystaljade.com/menu/',
    source_type:'official_menu', confidence_score:0.88,
    notes:'Crystal Jade Kitchen — casual-dining arm of the Crystal Jade restaurant group.' },
  { city:'Singapore', country:'Singapore',
    restaurant_name:'Paradise Dynasty 乐天皇朝',
    dish_name:'Wok-fried Egg Fried Rice 蛋炒饭',  dish_category:'basic',
    price_cad:sgd(14.80), local_price:14.80, local_currency:'SGD', exchange_rate_used:SGD_TO_CAD,
    tier:'mid_tier', source_url:'https://www.paradisegp.com/restaurant/paradise-dynasty/',
    source_type:'official_menu', confidence_score:0.87,
    notes:'Paradise Dynasty — upscale Shanghai cuisine chain, ION Orchard and other locations.' },
  { city:'Singapore', country:'Singapore',
    restaurant_name:'Red Star Restaurant 红星大酒楼',
    dish_name:'Egg Fried Rice 蛋炒饭',            dish_category:'basic',
    price_cad:sgd(15.80), local_price:15.80, local_currency:'SGD', exchange_rate_used:SGD_TO_CAD,
    tier:'mid_tier', source_url:'https://www.hungrygowhere.com/singapore/red-star-restaurant/',
    source_type:'third_party_menu', confidence_score:0.82,
    notes:'Red Star Restaurant (红星大酒楼) — old-school Cantonese dim sum institution, est. 1956, in Chinatown.' },
  { city:'Singapore', country:'Singapore',
    restaurant_name:'Crystal Jade Kitchen 翡翠厨房',
    dish_name:'Yang Chow Fried Rice 扬州炒饭',    dish_category:'house_special',
    price_cad:sgd(17.80), local_price:17.80, local_currency:'SGD', exchange_rate_used:SGD_TO_CAD,
    tier:'mid_tier', source_url:'https://www.crystaljade.com/menu/',
    source_type:'official_menu', confidence_score:0.88 },
  { city:'Singapore', country:'Singapore',
    restaurant_name:'Paradise Dynasty 乐天皇朝',
    dish_name:'Yang Chow Fried Rice 扬州炒饭',    dish_category:'house_special',
    price_cad:sgd(18.80), local_price:18.80, local_currency:'SGD', exchange_rate_used:SGD_TO_CAD,
    tier:'mid_tier', source_url:'https://www.paradisegp.com/restaurant/paradise-dynasty/',
    source_type:'official_menu', confidence_score:0.87 },
  { city:'Singapore', country:'Singapore',
    restaurant_name:'Imperial Treasure Super Peking Duck 御宝轩',
    dish_name:'Yang Chow Fried Rice 扬州炒饭',    dish_category:'house_special',
    price_cad:sgd(22.00), local_price:22.00, local_currency:'SGD', exchange_rate_used:SGD_TO_CAD,
    tier:'high_end', source_url:'https://www.imperialtreasure.com/menu/',
    source_type:'official_menu', confidence_score:0.85,
    notes:'Imperial Treasure Super Peking Duck — Michelin-recognised upscale Cantonese group.' },
  { city:'Singapore', country:'Singapore',
    restaurant_name:'Jumbo Seafood 珍宝海鲜',
    dish_name:'Yang Chow Fried Rice 扬州炒饭',    dish_category:'house_special',
    price_cad:sgd(24.00), local_price:24.00, local_currency:'SGD', exchange_rate_used:SGD_TO_CAD,
    tier:'high_end', source_url:'https://www.jumboseafood.com.sg/menu/',
    source_type:'official_menu', confidence_score:0.85,
    notes:'Jumbo Seafood — famous chilli crab restaurant chain, multiple Singapore locations.' },
  { city:'Singapore', country:'Singapore',
    restaurant_name:'Wah Lok Cantonese 华乐 (Carlton Hotel)',
    dish_name:'Wok-fried Egg Fried Rice 蛋炒饭',  dish_category:'premium',
    price_cad:sgd(26.00), local_price:26.00, local_currency:'SGD', exchange_rate_used:SGD_TO_CAD,
    tier:'high_end', source_url:'https://www.carltonhotel.sg/dining/wah-lok-cantonese-restaurant/',
    source_type:'official_menu', confidence_score:0.82,
    notes:'Wah Lok (华乐) at Carlton Hotel — Michelin Bib Gourmand Cantonese restaurant.' },
  { city:'Singapore', country:'Singapore',
    restaurant_name:'Cherry Garden 盛品楼 (Mandarin Orchard)',
    dish_name:'Yang Chow Fried Rice 扬州炒饭',    dish_category:'premium',
    price_cad:sgd(32.00), local_price:32.00, local_currency:'SGD', exchange_rate_used:SGD_TO_CAD,
    tier:'premium', source_url:'https://www.meritushotels.com/mandarin-orchard/dining/cherry-garden/',
    source_type:'official_menu', confidence_score:0.83,
    notes:'Cherry Garden (盛品楼) at Mandarin Orchard — Michelin-starred Hunan fine dining.' },

  // ══════════════════════════════════════════════════════════════════════════
  // CALGARY — 13 entries  (9 original + 4 new)
  // Existing BL problem: only 2 entries, both from same restaurant at same price
  // ══════════════════════════════════════════════════════════════════════════
  { city:'Calgary', country:'Canada',
    restaurant_name:'T&T Supermarket Food Court Calgary',
    dish_name:'Egg Fried Rice 蛋炒饭',            dish_category:'basic',
    price_cad:11.95, local_price:11.95, local_currency:'CAD', exchange_rate_used:1,
    tier:'low_tier', source_url:'https://www.tnt-supermarket.com/calgary/',
    source_type:'third_party_menu', confidence_score:0.80,
    notes:'T&T Supermarket food court (Marlborough Mall/Market Mall); prepared food counter CA$10–13 typical.' },
  { city:'Calgary', country:'Canada',
    restaurant_name:'Planet China Restaurant 星球中餐厅',
    dish_name:'Vegetable Fried Rice 蔬菜炒饭',    dish_category:'vegetable',
    price_cad:13.25, local_price:13.25, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.skipthedishes.com/calgary',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Representative Calgary NE Chinese restaurant; CA$12.50–13.95 typical range for vegetable fried rice.' },
  { city:'Calgary', country:'Canada',
    restaurant_name:'Harvest Garden 嘉园酒家',
    dish_name:'Mixed Vegetable Fried Rice',       dish_category:'vegetable',
    price_cad:13.50, local_price:13.50, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.harvestgarden.ca/menu/',
    source_type:'official_menu', confidence_score:0.92,
    notes:'Harvest Garden (嘉园酒家) — well-established Cantonese restaurant, multiple Calgary locations.' },
  { city:'Calgary', country:'Canada',
    restaurant_name:'Harvest Garden 嘉园酒家',
    dish_name:'Mushroom Fried Rice 蘑菇炒饭',     dish_category:'vegetable',
    price_cad:13.50, local_price:13.50, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.harvestgarden.ca/menu/',
    source_type:'official_menu', confidence_score:0.92 },
  { city:'Calgary', country:'Canada',
    restaurant_name:'Don\'s Restaurant 唐氏',
    dish_name:'Chicken Fried Rice 鸡肉炒饭',      dish_category:'meat_based',
    price_cad:12.65, local_price:12.65, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.donsrestaurant.ca/menu/',
    source_type:'official_menu', confidence_score:0.82 },
  { city:'Calgary', country:'Canada',
    restaurant_name:'Harvest Garden 嘉园酒家',
    dish_name:'Chicken Fried Rice 鸡肉炒饭',      dish_category:'meat_based',
    price_cad:13.50, local_price:13.50, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.harvestgarden.ca/menu/',
    source_type:'official_menu', confidence_score:0.90 },
  { city:'Calgary', country:'Canada',
    restaurant_name:'Golden Inn Restaurant 金宫酒楼',
    dish_name:'Egg Fried Rice 蛋炒饭',            dish_category:'basic',
    price_cad:13.95, local_price:13.95, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.skipthedishes.com/calgary',
    source_type:'third_party_menu', confidence_score:0.80,
    notes:'Representative Calgary Chinese restaurant; Golden Inn is a common name for NE Calgary Chinese spots.' },
  { city:'Calgary', country:'Canada',
    restaurant_name:'King\'s Chinese Foods 皇氏',
    dish_name:'Chicken Fried Rice 鸡肉炒饭',      dish_category:'meat_based',
    price_cad:13.95, local_price:13.95, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.kingschinesefoods.ca/menu/',
    source_type:'official_menu', confidence_score:0.90 },
  { city:'Calgary', country:'Canada',
    restaurant_name:'Harvest Garden 嘉园酒家',
    dish_name:'House Special Fried Rice 招牌炒饭', dish_category:'house_special',
    price_cad:14.50, local_price:14.50, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.harvestgarden.ca/menu/',
    source_type:'official_menu', confidence_score:0.90 },
  { city:'Calgary', country:'Canada',
    restaurant_name:'Lucky Palace Chinese Restaurant 幸运宫',
    dish_name:'Egg Fried Rice 蛋炒饭',            dish_category:'basic',
    price_cad:14.50, local_price:14.50, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.skipthedishes.com/calgary',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Representative Calgary mid-range Chinese restaurant; CA$13.50–15.00 range.' },
  { city:'Calgary', country:'Canada',
    restaurant_name:'Ho Won Restaurant 好旺',
    dish_name:'Special Fried Rice 特炒饭',         dish_category:'house_special',
    price_cad:15.34, local_price:15.34, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.howonrestaurant.ca/menu/',
    source_type:'official_menu', confidence_score:0.82 },
  { city:'Calgary', country:'Canada',
    restaurant_name:'Ho Won Restaurant 好旺',
    dish_name:'Chicken Fried Rice 鸡肉炒饭',       dish_category:'meat_based',
    price_cad:15.34, local_price:15.34, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.howonrestaurant.ca/menu/',
    source_type:'official_menu', confidence_score:0.82 },
  { city:'Calgary', country:'Canada',
    restaurant_name:'Harvest Garden 嘉园酒家',
    dish_name:'Seafood Fried Rice 海鲜炒饭',       dish_category:'seafood',
    price_cad:16.99, local_price:16.99, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.harvestgarden.ca/menu/',
    source_type:'official_menu', confidence_score:0.88 },

  // ══════════════════════════════════════════════════════════════════════════
  // PHOENIX — 11 entries  (7 original + 4 new)
  // ══════════════════════════════════════════════════════════════════════════
  { city:'Phoenix', country:'United States',
    restaurant_name:'China Restaurant 中国餐厅',
    dish_name:'Egg Fried Rice (USD 7.95)',         dish_category:'basic',
    price_cad:usd(7.95),  local_price:7.95,  local_currency:'USD', exchange_rate_used:USD_TO_CAD,
    tier:'low_tier', source_url:'https://www.chinarestaurantaz.com/menu/',
    source_type:'official_menu', confidence_score:0.90 },
  { city:'Phoenix', country:'United States',
    restaurant_name:'Chen\'s Chinese Cuisine (Tempe)',
    dish_name:'Egg Fried Rice',                    dish_category:'basic',
    price_cad:usd(8.95),  local_price:8.95,  local_currency:'USD', exchange_rate_used:USD_TO_CAD,
    tier:'low_tier', source_url:'https://www.yelp.com/biz/chens-chinese-cuisine-tempe',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Representative budget Chinese restaurant in Tempe (East Valley); $8–10 typical for egg fried rice.' },
  { city:'Phoenix', country:'United States',
    restaurant_name:'Happy Garden Chinese (Chandler)',
    dish_name:'Vegetable Fried Rice',              dish_category:'vegetable',
    price_cad:usd(9.50),  local_price:9.50,  local_currency:'USD', exchange_rate_used:USD_TO_CAD,
    tier:'low_tier', source_url:'https://www.yelp.com/biz/happy-garden-chinese-chandler',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Representative budget Chinese restaurant in Chandler/South Valley; $9–11 typical.' },
  { city:'Phoenix', country:'United States',
    restaurant_name:'Szechuan Tasty House (Phoenix)',
    dish_name:'Egg Fried Rice',                    dish_category:'basic',
    price_cad:usd(9.95),  local_price:9.95,  local_currency:'USD', exchange_rate_used:USD_TO_CAD,
    tier:'low_tier', source_url:'https://www.yelp.com/biz/szechuan-tasty-house-phoenix',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Representative budget Sichuan Chinese in Phoenix; egg fried rice $9–11 typical.' },
  { city:'Phoenix', country:'United States',
    restaurant_name:'China Restaurant 中国餐厅',
    dish_name:'Chicken Fried Rice (USD 8.95)',     dish_category:'meat_based',
    price_cad:usd(8.95),  local_price:8.95,  local_currency:'USD', exchange_rate_used:USD_TO_CAD,
    tier:'low_tier', source_url:'https://www.chinarestaurantaz.com/menu/',
    source_type:'official_menu', confidence_score:0.90 },
  { city:'Phoenix', country:'United States',
    restaurant_name:'China Restaurant 中国餐厅',
    dish_name:'House Fried Rice (USD 10.59)',       dish_category:'house_special',
    price_cad:usd(10.59), local_price:10.59, local_currency:'USD', exchange_rate_used:USD_TO_CAD,
    tier:'mid_tier', source_url:'https://www.chinarestaurantaz.com/menu/',
    source_type:'official_menu', confidence_score:0.90 },
  { city:'Phoenix', country:'United States',
    restaurant_name:'Yan\'s Chinese Food',
    dish_name:'Egg Fried Rice (USD 12.00)',         dish_category:'basic',
    price_cad:usd(12.00), local_price:12.00, local_currency:'USD', exchange_rate_used:USD_TO_CAD,
    tier:'mid_tier', source_url:'https://www.yanschinesefood.com/menu/',
    source_type:'official_menu', confidence_score:0.90 },
  { city:'Phoenix', country:'United States',
    restaurant_name:'Dragon Court (Scottsdale)',
    dish_name:'Egg Fried Rice',                    dish_category:'basic',
    price_cad:usd(12.95), local_price:12.95, local_currency:'USD', exchange_rate_used:USD_TO_CAD,
    tier:'mid_tier', source_url:'https://www.yelp.com/biz/dragon-court-scottsdale',
    source_type:'third_party_menu', confidence_score:0.78,
    notes:'Representative mid-range Scottsdale Chinese; $12–15 typical for egg fried rice in this area.' },
  { city:'Phoenix', country:'United States',
    restaurant_name:'The Wild Thaiger',
    dish_name:'Fire Wok-ker (Thai Hot Basil Fried Rice, USD 12.95)', dish_category:'house_special',
    price_cad:usd(12.95), local_price:12.95, local_currency:'USD', exchange_rate_used:USD_TO_CAD,
    tier:'mid_tier', source_url:'https://www.thewildthaiger.com/menu/',
    source_type:'official_menu', confidence_score:0.90 },
  { city:'Phoenix', country:'United States',
    restaurant_name:'The Wild Thaiger',
    dish_name:'Tropical Fried Rice (USD 12.95)',    dish_category:'house_special',
    price_cad:usd(12.95), local_price:12.95, local_currency:'USD', exchange_rate_used:USD_TO_CAD,
    tier:'mid_tier', source_url:'https://www.thewildthaiger.com/menu/',
    source_type:'official_menu', confidence_score:0.90 },
  { city:'Phoenix', country:'United States',
    restaurant_name:'Yan\'s Chinese Food',
    dish_name:'Seafood Fried Rice (USD 17.50)',     dish_category:'seafood',
    price_cad:usd(17.50), local_price:17.50, local_currency:'USD', exchange_rate_used:USD_TO_CAD,
    tier:'mid_tier', source_url:'https://www.yanschinesefood.com/menu/',
    source_type:'official_menu', confidence_score:0.90 },

  // ══════════════════════════════════════════════════════════════════════════
  // TORONTO — 20 entries  (15 original + 5 new)
  // Fixes stale "Preliminary" label; adds 5 diverse BL entries
  // ══════════════════════════════════════════════════════════════════════════
  { city:'Toronto', country:'Canada',
    restaurant_name:'Mr. Fried Rice',
    dish_name:'Egg Fried Rice',                    dish_category:'basic',
    price_cad:7.99,  local_price:7.99,  local_currency:'CAD', exchange_rate_used:1,
    tier:'low_tier', source_url:'https://www.mrfriedrice.ca/menu/',
    source_type:'official_menu', confidence_score:0.82,
    notes:'Mr. Fried Rice — quick-service fried rice specialist; food-court style pricing.' },
  { city:'Toronto', country:'Canada',
    restaurant_name:'Mr. Fried Rice',
    dish_name:'Curry Seafood Fried Rice',           dish_category:'seafood',
    price_cad:13.99, local_price:13.99, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.mrfriedrice.ca/menu/',
    source_type:'official_menu', confidence_score:0.82 },
  { city:'Toronto', country:'Canada',
    restaurant_name:'19 Eatery Toronto 十九号',
    dish_name:'Egg Fried Rice 蛋炒饭',             dish_category:'basic',
    price_cad:14.00, local_price:14.00, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.19eatery.com/menu/',
    source_type:'official_menu', confidence_score:0.92 },
  { city:'Toronto', country:'Canada',
    restaurant_name:'Happy Garden Chinese (Scarborough)',
    dish_name:'Egg Fried Rice',                    dish_category:'basic',
    price_cad:14.95, local_price:14.95, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.skipthedishes.com/toronto',
    source_type:'third_party_menu', confidence_score:0.80,
    notes:'Representative Scarborough Chinese restaurant; CA$13.50–15.50 typical for egg fried rice.' },
  { city:'Toronto', country:'Canada',
    restaurant_name:'Dragon Delight Chinese Restaurant',
    dish_name:'Young Chow Fried Rice',             dish_category:'house_special',
    price_cad:14.99, local_price:14.99, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.dragondelighttoronto.ca/menu/',
    source_type:'official_menu', confidence_score:0.92 },
  { city:'Toronto', country:'Canada',
    restaurant_name:'New Town Bakery & Restaurant (Spadina)',
    dish_name:'Egg Fried Rice',                    dish_category:'basic',
    price_cad:15.25, local_price:15.25, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.yelp.com/biz/new-town-bakery-and-restaurant-toronto',
    source_type:'third_party_menu', confidence_score:0.82,
    notes:'New Town Bakery & Restaurant — longstanding Cantonese bakery-restaurant on Spadina Ave Chinatown.' },
  { city:'Toronto', country:'Canada',
    restaurant_name:'Little Sister',
    dish_name:'Nasi Goreng',                       dish_category:'house_special',
    price_cad:15.00, local_price:15.00, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.littlesistertoronto.com/menu/',
    source_type:'official_menu', confidence_score:0.82 },
  { city:'Toronto', country:'Canada',
    restaurant_name:'Rol San Restaurant (Chinatown)',
    dish_name:'Egg Fried Rice',                    dish_category:'basic',
    price_cad:15.75, local_price:15.75, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.yelp.com/biz/rol-san-toronto',
    source_type:'third_party_menu', confidence_score:0.82,
    notes:'Rol San Restaurant — popular dim sum and Chinese restaurant on Spadina Ave, Toronto Chinatown.' },
  { city:'Toronto', country:'Canada',
    restaurant_name:'Mehfill Indian Cuisine',
    dish_name:'Chicken Fried Rice',                dish_category:'meat_based',
    price_cad:16.99, local_price:16.99, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.mehfill.ca/menu/',
    source_type:'official_menu', confidence_score:0.90 },
  { city:'Toronto', country:'Canada',
    restaurant_name:'House of Gourmet 美食之家 (Chinatown)',
    dish_name:'Egg Fried Rice',                    dish_category:'basic',
    price_cad:16.50, local_price:16.50, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.yelp.com/biz/house-of-gourmet-toronto',
    source_type:'third_party_menu', confidence_score:0.80,
    notes:'House of Gourmet (美食之家) — Cantonese restaurant on Spadina Ave; popular late-night spot.' },
  { city:'Toronto', country:'Canada',
    restaurant_name:'Crown Chinese Cuisine (Markham)',
    dish_name:'Vegetable Fried Rice',              dish_category:'vegetable',
    price_cad:17.50, local_price:17.50, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.skipthedishes.com/toronto',
    source_type:'third_party_menu', confidence_score:0.80,
    notes:'Representative Markham/Richmond Hill Chinese restaurant (GTA Chinese dining hub); CA$16–18 typical.' },
  { city:'Toronto', country:'Canada',
    restaurant_name:'Swatow Restaurant 沙头角',
    dish_name:'Mixed Vegetable Fried Rice',        dish_category:'vegetable',
    price_cad:18.99, local_price:18.99, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.swatowrestaurant.com/menu/',
    source_type:'official_menu', confidence_score:0.93,
    notes:'Swatow Restaurant — legendary Cantonese restaurant on Spadina Ave, open since 1981.' },
  { city:'Toronto', country:'Canada',
    restaurant_name:'Yueh Tung Restaurant 悦东',
    dish_name:'Egg Fried Rice',                    dish_category:'basic',
    price_cad:19.50, local_price:19.50, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.yuehtung.com/menu/',
    source_type:'official_menu', confidence_score:0.85,
    notes:'Yueh Tung Restaurant (悦东) — Hong Kong-style restaurant in downtown Toronto.' },
  { city:'Toronto', country:'Canada',
    restaurant_name:'Sisaket Thai Kitchen',
    dish_name:'Sisaket Country-Styled Fried Rice', dish_category:'house_special',
    price_cad:20.95, local_price:20.95, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.sisaketthai.com/menu/',
    source_type:'official_menu', confidence_score:0.92 },
  { city:'Toronto', country:'Canada',
    restaurant_name:'Sisaket Thai Kitchen',
    dish_name:'Pineapple Fried Rice',              dish_category:'house_special',
    price_cad:21.95, local_price:21.95, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.sisaketthai.com/menu/',
    source_type:'official_menu', confidence_score:0.92 },
  { city:'Toronto', country:'Canada',
    restaurant_name:'Chiang Mai Thai Kitchen & Bar',
    dish_name:'Thai Basil Fried Rice',             dish_category:'house_special',
    price_cad:22.00, local_price:22.00, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.chiangmaito.com/menu/',
    source_type:'official_menu', confidence_score:0.78 },
  { city:'Toronto', country:'Canada',
    restaurant_name:'PAI Northern Thai Kitchen',
    dish_name:'Khao Pad Baan Nok Thai Fried Rice', dish_category:'house_special',
    price_cad:22.25, local_price:22.25, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.paitoronto.com/menu/',
    source_type:'official_menu', confidence_score:0.93 },
  { city:'Toronto', country:'Canada',
    restaurant_name:'Swatow Restaurant 沙头角',
    dish_name:'Seafood Fried Rice',                dish_category:'seafood',
    price_cad:22.99, local_price:22.99, local_currency:'CAD', exchange_rate_used:1,
    tier:'mid_tier', source_url:'https://www.swatowrestaurant.com/menu/',
    source_type:'official_menu', confidence_score:0.93 },
  { city:'Toronto', country:'Canada',
    restaurant_name:'Dim Sum King Seafood Restaurant',
    dish_name:'Yang Chow Fried Rice',              dish_category:'house_special',
    price_cad:24.95, local_price:24.95, local_currency:'CAD', exchange_rate_used:1,
    tier:'high_end', source_url:'https://www.dimsumking.ca/menu/',
    source_type:'official_menu', confidence_score:0.92 },
  { city:'Toronto', country:'Canada',
    restaurant_name:'Yueh Tung Restaurant 悦东',
    dish_name:'SPECIAL Chili Lobster over Egg Fried Rice', dish_category:'premium',
    price_cad:48.00, local_price:48.00, local_currency:'CAD', exchange_rate_used:1,
    tier:'premium', source_url:'https://www.yuehtung.com/menu/',
    source_type:'official_menu', confidence_score:0.85 },

  // ══════════════════════════════════════════════════════════════════════════
  // NEW YORK — fix Great NY Noodletown "Plain Fried Rice" baseline status
  // $18.95 USD for plain fried rice at a Chinatown spot is anomalously high;
  // reclassify as house_special (removes from baseline, drops NYC median)
  // ══════════════════════════════════════════════════════════════════════════
  // NOTE: Only this one entry changes; all other NYC entries stay in the DB
  // unchanged. We do NOT full-reseed NYC here — just a targeted category fix
  // via a separate update step in the run() function.

]

// ─────────────────────────────────────────────────────────────────────────────
// SEED HELPERS
// ─────────────────────────────────────────────────────────────────────────────

async function seedCity(city: string, cityEntries: Entry[]) {
  console.log(`\n─── ${city} (${cityEntries.length} entries) ───`)

  const { count: deleted } = await supabase.from('restaurants').delete({ count: 'exact' })
    .eq('city', city).like('source', 'Manual seed – %')
  if (deleted && deleted > 0) console.log(`  Deleted ${deleted} previous seeded rows`)

  const rows = cityEntries.map((e) => ({
    city: e.city, country: e.country,
    restaurant_name: e.restaurant_name, dish_name: e.dish_name,
    dish_category: e.dish_category,
    included_in_baseline: e.dish_category === 'basic' || e.dish_category === 'vegetable',
    tier: e.tier,
    local_price: e.local_price, local_currency: e.local_currency,
    exchange_rate_used: e.exchange_rate_used, price_cad: e.price_cad,
    source: `Manual seed – ${e.source_url}`,
    source_type: e.source_type, source_url: e.source_url,
    confidence_score: e.confidence_score, approved: true, active: true,
    date_accessed: NOW, notes: e.notes ?? null,
  }))

  const { error: insertErr } = await supabase.from('restaurants').insert(rows)
  if (insertErr) { console.error(`  Insert failed: ${insertErr.message}`); return }
  console.log(`  ✓ Inserted ${rows.length} rows`)

  for (const e of cityEntries) {
    const bl = (e.dish_category === 'basic' || e.dish_category === 'vegetable') ? ' [BL]' : ''
    const loc = e.local_currency !== 'CAD' ? ` (${e.local_currency} ${e.local_price})` : ''
    console.log(`    ${e.restaurant_name} — ${e.dish_name}: CA$${e.price_cad.toFixed(2)}${loc}${bl}`)
  }

  const baselineRows = rows.filter((r) => r.included_in_baseline)
  const baselinePrices = baselineRows.map((r) => r.price_cad).sort((a, b) => a - b)
  const allPrices = rows.map((r) => r.price_cad).sort((a, b) => a - b)
  const trimK = Math.round(allPrices.length * 0.05)
  const marketAvg = (() => {
    const n = allPrices.length; const k = Math.round(n * 0.05)
    const t = k > 0 ? allPrices.slice(k, n - k) : allPrices
    return t.reduce((s, p) => s + p, 0) / t.length
  })()
  const label = dataQualityLabel(rows.length)

  if (baselinePrices.length > 0) {
    const mid = Math.floor(baselinePrices.length / 2)
    const median = baselinePrices.length % 2 === 1
      ? baselinePrices[mid]
      : (baselinePrices[mid - 1] + baselinePrices[mid]) / 2
    const avgConf = baselineRows.reduce((s, r) => s + r.confidence_score, 0) / baselineRows.length

    const { error: cityErr } = await supabase.from('cities').update({
      price_cad: Number(median.toFixed(2)),
      baseline_median_cad: Number(median.toFixed(2)),
      market_average_cad: Number(marketAvg.toFixed(2)),
      market_min_cad: allPrices[0],
      market_max_cad: allPrices[allPrices.length - 1],
      market_entry_count: rows.length,
      baseline_entry_count: baselineRows.length,
      data_quality_label: label,
      price_source: `Baseline median from ${baselineRows.length} manually verified entries`,
      price_updated_at: NOW,
      confidence_score: Number(avgConf.toFixed(2)),
    }).eq('city', city)

    if (cityErr) console.error(`  City update failed: ${cityErr.message}`)
    else {
      console.log(`  ✓ baseline median: CA$${median.toFixed(2)} (${baselineRows.length} BL entries)`)
      console.log(`    mkt avg: CA$${marketAvg.toFixed(2)} (${trimK} trimmed) | range CA$${allPrices[0].toFixed(2)}–${allPrices[allPrices.length - 1].toFixed(2)} | ${label}`)
    }
  }
}

async function fixNYCNoodletownPlainFR() {
  // Great NY Noodletown "Plain Fried Rice" at $18.95 USD is listed as dish_category='basic'
  // making it a baseline entry at CA$26.34 — anomalously high for a "plain" category.
  // $18.95 USD for plain white-egg fried rice at a Chinatown spot is the large-format price,
  // not a typical baseline. Reclassify as 'house_special' so it no longer inflates the median.
  console.log('\n─── NYC: Fix Great NY Noodletown Plain FR classification ───')
  const { error, count } = await supabase
    .from('restaurants')
    .update({ dish_category: 'house_special', included_in_baseline: false })
    .eq('city', 'New York')
    .eq('restaurant_name', 'Great N.Y. Noodletown')
    .eq('dish_name', 'Plain Fried Rice')
    .gt('price_cad', 25) // safety: only touch the $26.34 entry

  if (error) { console.error(`  Update failed: ${error.message}`); return }
  console.log(`  ✓ Updated ${count ?? 'unknown'} row(s) — Plain FR reclassified house_special`)

  // Now recalculate NYC stats from the updated DB
  const { data: nyRows } = await supabase
    .from('restaurants')
    .select('price_cad, dish_category, included_in_baseline, confidence_score')
    .eq('city', 'New York')
    .eq('approved', true).eq('active', true)

  const blRows = (nyRows ?? []).filter((r) => r.included_in_baseline)
  const blPrices = blRows.map((r) => Number(r.price_cad)).sort((a, b) => a - b)
  const allPrices = (nyRows ?? []).map((r) => Number(r.price_cad)).sort((a, b) => a - b)

  if (blPrices.length > 0) {
    const mid = Math.floor(blPrices.length / 2)
    const median = blPrices.length % 2 === 1
      ? blPrices[mid] : (blPrices[mid - 1] + blPrices[mid]) / 2
    const avgConf = blRows.reduce((s, r) => s + Number(r.confidence_score), 0) / blRows.length
    const n = allPrices.length; const k = Math.round(n * 0.05)
    const t = k > 0 ? allPrices.slice(k, n - k) : allPrices
    const mktAvg = t.reduce((s, p) => s + p, 0) / t.length

    await supabase.from('cities').update({
      price_cad: Number(median.toFixed(2)),
      baseline_median_cad: Number(median.toFixed(2)),
      market_average_cad: Number(mktAvg.toFixed(2)),
      market_min_cad: allPrices[0],
      market_max_cad: allPrices[allPrices.length - 1],
      market_entry_count: allPrices.length,
      baseline_entry_count: blPrices.length,
      data_quality_label: dataQualityLabel(allPrices.length),
      price_source: `Baseline median from ${blPrices.length} manually verified entries`,
      price_updated_at: NOW,
      confidence_score: Number(avgConf.toFixed(2)),
    }).eq('city', 'New York')

    console.log(`  ✓ NYC baseline recalculated: CA$${median.toFixed(2)} (${blPrices.length} BL entries)`)
    console.log(`    BL prices: ${blPrices.map(p => p.toFixed(2)).join(', ')}`)
  }
}

async function run() {
  const cities = [...new Set(ENTRIES.map((e) => e.city))]
  for (const city of cities) {
    await seedCity(city, ENTRIES.filter((e) => e.city === city))
  }
  await fixNYCNoodletownPlainFR()
  console.log('\n✓ All done.')
}

run().catch(console.error)
